import { type Locale } from '@/lib/i18n/config';
import { getDisplayLocale } from '@/lib/i18n/display-locale';

export type BookingCopy = {
  lawyerNotFoundTitle: string;
  signInTitle: string;
  signInBody: string;
  steps: [string, string, string];
  selectMode: string;
  selectDate: string;
  selectTime: string;
  issueTitle: string;
  issueHint: string;
  issuePlaceholder: string;
  uploadTitle: string;
  uploadComingSoon: string;
  orderSummary: string;
  lawyerLabel: string;
  scheduleLabel: string;
  modeLabel: string;
  totalLabel: string;
  amountLabel: string;
  bookingIdLabel: string;
  firstFree: string;
  free: string;
  firstConsultationFree: string;
  legalExpert: string;
  confirmedTitle: string;
  confirmedMessage: string;
  goToDashboard: string;
  securePaymentNote: string;
  confirmFreeBooking: string;
  termsPrefix: string;
  termsSuffix: string;
  slotTaken: string;
  paymentLoadFailed: string;
  paymentVerifyFailed: string;
  networkError: string;
  modes: {
    VIDEO: string;
    CALL: string;
    CHAT: string;
    IN_PERSON: string;
  };
};

const ENGLISH_COPY: BookingCopy = {
  lawyerNotFoundTitle: 'Lawyer not found',
  signInTitle: 'Sign in to continue',
  signInBody: 'You need an account to book a consultation.',
  steps: ['Mode & time', 'Details', 'Confirm'],
  selectMode: '1. Select consultation mode',
  selectDate: '2. Select date',
  selectTime: '3. Select time slot',
  issueTitle: 'Briefly describe your legal issue',
  issueHint: 'Minimum 20 characters so the lawyer can prepare.',
  issuePlaceholder: 'Example: I have a dispute about a rental deposit.',
  uploadTitle: 'Documents',
  uploadComingSoon: 'Document upload is coming soon.',
  orderSummary: 'Order summary',
  lawyerLabel: 'Lawyer',
  scheduleLabel: 'Date and time',
  modeLabel: 'Mode',
  totalLabel: 'Total amount',
  amountLabel: 'Amount',
  bookingIdLabel: 'Booking ID',
  firstFree: 'First free',
  free: 'Free',
  firstConsultationFree: 'First consultation free',
  legalExpert: 'Legal expert',
  confirmedTitle: 'Booking confirmed',
  confirmedMessage: 'Your consultation is scheduled. Review the details below.',
  goToDashboard: 'Go to my dashboard',
  securePaymentNote: 'Secure payment. Full refund if the lawyer cancels or reschedules.',
  confirmFreeBooking: 'Confirm free booking',
  termsPrefix: "By confirming, you agree to LexIndia's ",
  termsSuffix: '.',
  slotTaken: 'This time slot was just taken. Please choose another.',
  paymentLoadFailed: 'Payment gateway failed to load. Please check your connection.',
  paymentVerifyFailed: 'Payment verification failed. Please contact support.',
  networkError: 'Network error. Please try again.',
  modes: {
    VIDEO: 'Video call',
    CALL: 'Voice call',
    CHAT: 'Chat',
    IN_PERSON: 'In-person',
  },
};

const HINDI_COPY: BookingCopy = {
  lawyerNotFoundTitle: 'वकील नहीं मिला',
  signInTitle: 'आगे बढ़ने के लिए साइन इन करें',
  signInBody: 'परामर्श बुक करने के लिए आपको साइन इन करना होगा।',
  steps: ['मोड और समय', 'विवरण', 'पुष्टि'],
  selectMode: '1. परामर्श मोड चुनें',
  selectDate: '2. तारीख चुनें',
  selectTime: '3. समय स्लॉट चुनें',
  issueTitle: 'अपनी कानूनी समस्या संक्षेप में बताएं',
  issueHint: 'कम से कम 20 अक्षर लिखें ताकि वकील तैयारी कर सके।',
  issuePlaceholder: 'उदाहरण: किराये की जमा राशि को लेकर मेरा विवाद है।',
  uploadTitle: 'दस्तावेज़',
  uploadComingSoon: 'दस्तावेज़ अपलोड सुविधा जल्द आ रही है।',
  orderSummary: 'ऑर्डर सारांश',
  lawyerLabel: 'वकील',
  scheduleLabel: 'तारीख और समय',
  modeLabel: 'मोड',
  totalLabel: 'कुल राशि',
  amountLabel: 'राशि',
  bookingIdLabel: 'बुकिंग आईडी',
  firstFree: 'पहला निःशुल्क',
  free: 'निःशुल्क',
  firstConsultationFree: 'पहला परामर्श निःशुल्क',
  legalExpert: 'कानूनी विशेषज्ञ',
  confirmedTitle: 'बुकिंग की पुष्टि हो गई',
  confirmedMessage: 'आपका परामर्श तय हो गया है। नीचे विवरण देखें।',
  goToDashboard: 'मेरे डैशबोर्ड पर जाएं',
  securePaymentNote: 'भुगतान सुरक्षित है। वकील रद्द करे या समय बदले तो पूरा रिफंड मिलेगा।',
  confirmFreeBooking: 'निःशुल्क बुकिंग की पुष्टि करें',
  termsPrefix: 'पुष्टि करके आप LexIndia की ',
  termsSuffix: ' से सहमत होते हैं।',
  slotTaken: 'यह समय स्लॉट अभी लिया जा चुका है। कृपया दूसरा चुनें।',
  paymentLoadFailed: 'पेमेंट गेटवे लोड नहीं हो सका। कृपया कनेक्शन जांचें।',
  paymentVerifyFailed: 'भुगतान सत्यापन विफल रहा। कृपया सहायता से संपर्क करें।',
  networkError: 'नेटवर्क त्रुटि। कृपया फिर से प्रयास करें।',
  modes: {
    VIDEO: 'वीडियो कॉल',
    CALL: 'वॉइस कॉल',
    CHAT: 'चैट',
    IN_PERSON: 'सामने-सामने',
  },
};

const BENGALI_COPY: BookingCopy = {
  lawyerNotFoundTitle: 'আইনজীবী খুঁজে পাওয়া যায়নি',
  signInTitle: 'চালিয়ে যেতে সাইন ইন করুন',
  signInBody: 'পরামর্শ বুক করতে আপনাকে সাইন ইন করতে হবে।',
  steps: ['মোড ও সময়', 'বিস্তারিত', 'নিশ্চিতকরণ'],
  selectMode: '1. পরামর্শের ধরন বেছে নিন',
  selectDate: '2. তারিখ বেছে নিন',
  selectTime: '3. সময় বেছে নিন',
  issueTitle: 'আপনার আইনি সমস্যাটি সংক্ষেপে লিখুন',
  issueHint: 'কমপক্ষে ২০টি অক্ষর লিখুন যাতে আইনজীবী প্রস্তুতি নিতে পারেন।',
  issuePlaceholder: 'উদাহরণ: ভাড়ার জামানত নিয়ে আমার বিরোধ আছে।',
  uploadTitle: 'নথি',
  uploadComingSoon: 'নথি আপলোড সুবিধা শীঘ্রই আসছে।',
  orderSummary: 'অর্ডারের সারাংশ',
  lawyerLabel: 'আইনজীবী',
  scheduleLabel: 'তারিখ ও সময়',
  modeLabel: 'মোড',
  totalLabel: 'মোট পরিমাণ',
  amountLabel: 'পরিমাণ',
  bookingIdLabel: 'বুকিং আইডি',
  firstFree: 'প্রথমটি ফ্রি',
  free: 'ফ্রি',
  firstConsultationFree: 'প্রথম পরামর্শ ফ্রি',
  legalExpert: 'আইনি বিশেষজ্ঞ',
  confirmedTitle: 'বুকিং নিশ্চিত হয়েছে',
  confirmedMessage: 'আপনার পরামর্শ নির্ধারিত হয়েছে। নিচের বিবরণ দেখুন।',
  goToDashboard: 'আমার ড্যাশবোর্ডে যান',
  securePaymentNote: 'পেমেন্ট নিরাপদ। আইনজীবী বাতিল বা সময় বদলালে সম্পূর্ণ রিফান্ড পাবেন।',
  confirmFreeBooking: 'ফ্রি বুকিং নিশ্চিত করুন',
  termsPrefix: 'নিশ্চিত করার মাধ্যমে আপনি LexIndia-এর ',
  termsSuffix: ' মেনে নিচ্ছেন।',
  slotTaken: 'এই সময়টি সদ্য বুক হয়ে গেছে। অনুগ্রহ করে অন্যটি বেছে নিন।',
  paymentLoadFailed: 'পেমেন্ট গেটওয়ে লোড করা যায়নি। সংযোগ পরীক্ষা করুন।',
  paymentVerifyFailed: 'পেমেন্ট যাচাই ব্যর্থ হয়েছে। সহায়তার সাথে যোগাযোগ করুন।',
  networkError: 'নেটওয়ার্ক ত্রুটি। আবার চেষ্টা করুন।',
  modes: {
    VIDEO: 'ভিডিও কল',
    CALL: 'ভয়েস কল',
    CHAT: 'চ্যাট',
    IN_PERSON: 'সরাসরি সাক্ষাৎ',
  },
};

const TELUGU_COPY: BookingCopy = {
  lawyerNotFoundTitle: 'న్యాయవాది కనబడలేదు',
  signInTitle: 'కొనసాగించడానికి సైన్ ఇన్ చేయండి',
  signInBody: 'సలహాను బుక్ చేయడానికి మీరు సైన్ ఇన్ కావాలి.',
  steps: ['మోడ్ & సమయం', 'వివరాలు', 'నిర్ధారణ'],
  selectMode: '1. సలహా మోడ్ ఎంచుకోండి',
  selectDate: '2. తేదీ ఎంచుకోండి',
  selectTime: '3. సమయాన్ని ఎంచుకోండి',
  issueTitle: 'మీ న్యాయ సమస్యను సంక్షిప్తంగా వివరించండి',
  issueHint: 'న్యాయవాది సిద్ధం కావడానికి కనీసం 20 అక్షరాలు వ్రాయండి.',
  issuePlaceholder: 'ఉదాహరణ: అద్దె డిపాజిట్‌పై నాకు వివాదం ఉంది.',
  uploadTitle: 'పత్రాలు',
  uploadComingSoon: 'పత్రాల అప్‌లోడ్ ఫీచర్ త్వరలో వస్తుంది.',
  orderSummary: 'ఆర్డర్ సారాంశం',
  lawyerLabel: 'న్యాయవాది',
  scheduleLabel: 'తేదీ మరియు సమయం',
  modeLabel: 'మోడ్',
  totalLabel: 'మొత్తం',
  amountLabel: 'మొత్తం',
  bookingIdLabel: 'బుకింగ్ ఐడి',
  firstFree: 'మొదటిది ఉచితం',
  free: 'ఉచితం',
  firstConsultationFree: 'మొదటి సలహా ఉచితం',
  legalExpert: 'న్యాయ నిపుణుడు',
  confirmedTitle: 'బుకింగ్ నిర్ధారించబడింది',
  confirmedMessage: 'మీ సలహా షెడ్యూల్ అయింది. కింది వివరాలను చూడండి.',
  goToDashboard: 'నా డ్యాష్‌బోర్డ్‌కు వెళ్లండి',
  securePaymentNote: 'చెల్లింపు సురక్షితం. న్యాయవాది రద్దు చేసినా లేదా మార్చినా పూర్తి రిఫండ్ లభిస్తుంది.',
  confirmFreeBooking: 'ఉచిత బుకింగ్‌ను నిర్ధారించండి',
  termsPrefix: 'నిర్ధారించడం ద్వారా మీరు LexIndia యొక్క ',
  termsSuffix: 'కు అంగీకరిస్తారు.',
  slotTaken: 'ఈ సమయం ఇప్పుడే తీసుకోబడింది. దయచేసి మరొకదాన్ని ఎంచుకోండి.',
  paymentLoadFailed: 'పేమెంట్ గేట్‌వే లోడ్ కాలేదు. కనెక్షన్‌ను తనిఖీ చేయండి.',
  paymentVerifyFailed: 'చెల్లింపు ధృవీకరణ విఫలమైంది. దయచేసి సహాయాన్ని సంప్రదించండి.',
  networkError: 'నెట్‌వర్క్ లోపం. దయచేసి మళ్లీ ప్రయత్నించండి.',
  modes: {
    VIDEO: 'వీడియో కాల్',
    CALL: 'వాయిస్ కాల్',
    CHAT: 'చాట్',
    IN_PERSON: 'ప్రత్యక్షంగా',
  },
};

const MARATHI_COPY: BookingCopy = {
  lawyerNotFoundTitle: 'वकील सापडला नाही',
  signInTitle: 'पुढे जाण्यासाठी साइन इन करा',
  signInBody: 'सल्ला बुक करण्यासाठी तुम्हाला साइन इन करावे लागेल.',
  steps: ['मोड आणि वेळ', 'तपशील', 'पुष्टी'],
  selectMode: '1. सल्ल्याचा मोड निवडा',
  selectDate: '2. तारीख निवडा',
  selectTime: '3. वेळ निवडा',
  issueTitle: 'तुमचा कायदेशीर प्रश्न थोडक्यात लिहा',
  issueHint: 'वकील तयारी करू शकेल म्हणून किमान 20 अक्षरे लिहा.',
  issuePlaceholder: 'उदाहरण: भाडे ठेव रकमेवरून माझा वाद आहे.',
  uploadTitle: 'कागदपत्रे',
  uploadComingSoon: 'कागदपत्र अपलोड सुविधा लवकरच येत आहे.',
  orderSummary: 'ऑर्डर सारांश',
  lawyerLabel: 'वकील',
  scheduleLabel: 'तारीख आणि वेळ',
  modeLabel: 'मोड',
  totalLabel: 'एकूण रक्कम',
  amountLabel: 'रक्कम',
  bookingIdLabel: 'बुकिंग आयडी',
  firstFree: 'पहिले मोफत',
  free: 'मोफत',
  firstConsultationFree: 'पहिला सल्ला मोफत',
  legalExpert: 'कायदेशीर तज्ञ',
  confirmedTitle: 'बुकिंगची पुष्टी झाली',
  confirmedMessage: 'तुमचा सल्ला निश्चित झाला आहे. खालील तपशील पहा.',
  goToDashboard: 'माझ्या डॅशबोर्डवर जा',
  securePaymentNote: 'पेमेंट सुरक्षित आहे. वकील रद्द केल्यास किंवा वेळ बदलल्यास पूर्ण परतावा मिळेल.',
  confirmFreeBooking: 'मोफत बुकिंगची पुष्टी करा',
  termsPrefix: 'पुष्टी करून तुम्ही LexIndia च्या ',
  termsSuffix: 'ना मान्यता देता.',
  slotTaken: 'ही वेळ आत्ताच घेतली गेली आहे. कृपया दुसरी निवडा.',
  paymentLoadFailed: 'पेमेंट गेटवे लोड झाले नाही. कृपया कनेक्शन तपासा.',
  paymentVerifyFailed: 'पेमेंट पडताळणी अयशस्वी झाली. कृपया सहाय्याशी संपर्क साधा.',
  networkError: 'नेटवर्क त्रुटी. कृपया पुन्हा प्रयत्न करा.',
  modes: {
    VIDEO: 'व्हिडिओ कॉल',
    CALL: 'व्हॉइस कॉल',
    CHAT: 'चॅट',
    IN_PERSON: 'प्रत्यक्ष भेट',
  },
};

const TAMIL_COPY: BookingCopy = {
  lawyerNotFoundTitle: 'வழக்கறிஞர் கிடைக்கவில்லை',
  signInTitle: 'தொடர உள்நுழையவும்',
  signInBody: 'ஆலோசனையை முன்பதிவு செய்ய நீங்கள் உள்நுழைந்திருக்க வேண்டும்.',
  steps: ['முறை & நேரம்', 'விவரங்கள்', 'உறுதி'],
  selectMode: '1. ஆலோசனை முறையைத் தேர்ந்தெடுக்கவும்',
  selectDate: '2. தேதியைத் தேர்ந்தெடுக்கவும்',
  selectTime: '3. நேரத்தைத் தேர்ந்தெடுக்கவும்',
  issueTitle: 'உங்கள் சட்ட பிரச்சினையைச் சுருக்கமாக விளக்கவும்',
  issueHint: 'வழக்கறிஞர் தயாராக இருக்க குறைந்தது 20 எழுத்துகள் எழுதவும்.',
  issuePlaceholder: 'உதாரணம்: வாடகை டெபாசிட் குறித்து எனக்கு தகராறு உள்ளது.',
  uploadTitle: 'ஆவணங்கள்',
  uploadComingSoon: 'ஆவணப் பதிவேற்ற வசதி விரைவில் வருகிறது.',
  orderSummary: 'ஆர்டர் சுருக்கம்',
  lawyerLabel: 'வழக்கறிஞர்',
  scheduleLabel: 'தேதி மற்றும் நேரம்',
  modeLabel: 'முறை',
  totalLabel: 'மொத்த தொகை',
  amountLabel: 'தொகை',
  bookingIdLabel: 'முன்பதிவு ஐடி',
  firstFree: 'முதல் இலவசம்',
  free: 'இலவசம்',
  firstConsultationFree: 'முதல் ஆலோசனை இலவசம்',
  legalExpert: 'சட்ட நிபுணர்',
  confirmedTitle: 'முன்பதிவு உறுதி செய்யப்பட்டது',
  confirmedMessage: 'உங்கள் ஆலோசனை திட்டமிடப்பட்டுள்ளது. கீழே உள்ள விவரங்களைப் பாருங்கள்.',
  goToDashboard: 'என் டாஷ்போர்டுக்கு செல்லவும்',
  securePaymentNote: 'பணம் செலுத்துதல் பாதுகாப்பானது. வழக்கறிஞர் ரத்து செய்தால் முழு பணத்தீர்வு கிடைக்கும்.',
  confirmFreeBooking: 'இலவச முன்பதிவை உறுதிசெய்க',
  termsPrefix: 'உறுதிப்படுத்துவதன் மூலம் நீங்கள் LexIndia-ன் ',
  termsSuffix: 'ஐ ஏற்கிறீர்கள்.',
  slotTaken: 'இந்த நேரம் இப்போது எடுக்கப்பட்டுள்ளது. வேறு ஒன்றைத் தேர்ந்தெடுக்கவும்.',
  paymentLoadFailed: 'பணம் செலுத்தும் அமைப்பு ஏற்றப்படவில்லை. உங்கள் இணைப்பைச் சரிபார்க்கவும்.',
  paymentVerifyFailed: 'பணம் செலுத்தல் சரிபார்ப்பு தோல்வியடைந்தது. உதவியைத் தொடர்புகொள்ளவும்.',
  networkError: 'நெட்வொர்க் பிழை. மீண்டும் முயற்சிக்கவும்.',
  modes: {
    VIDEO: 'வீடியோ அழைப்பு',
    CALL: 'குரல் அழைப்பு',
    CHAT: 'அரட்டை',
    IN_PERSON: 'நேருக்கு நேர்',
  },
};

const GUJARATI_COPY: BookingCopy = {
  lawyerNotFoundTitle: 'વકીલ મળ્યા નથી',
  signInTitle: 'આગળ વધવા માટે સાઇન ઇન કરો',
  signInBody: 'કન્સલ્ટેશન બુક કરવા માટે તમારે સાઇન ઇન કરવું પડશે.',
  steps: ['મોડ અને સમય', 'વિગતો', 'પુષ્ટિ'],
  selectMode: '1. કન્સલ્ટેશન મોડ પસંદ કરો',
  selectDate: '2. તારીખ પસંદ કરો',
  selectTime: '3. સમય પસંદ કરો',
  issueTitle: 'તમારો કાનૂની પ્રશ્ન સંક્ષિપ્તમાં લખો',
  issueHint: 'ઓછામાં ઓછા 20 અક્ષર લખો જેથી વકીલ તૈયારી કરી શકે.',
  issuePlaceholder: 'ઉદાહરણ: ભાડાની ડિપોઝિટ અંગે મારો વિવાદ છે.',
  uploadTitle: 'દસ્તાવેજો',
  uploadComingSoon: 'દસ્તાવેજ અપલોડ સુવિધા ટૂંક સમયમાં આવશે.',
  orderSummary: 'ઓર્ડર સારાંશ',
  lawyerLabel: 'વકીલ',
  scheduleLabel: 'તારીખ અને સમય',
  modeLabel: 'મોડ',
  totalLabel: 'કુલ રકમ',
  amountLabel: 'રકમ',
  bookingIdLabel: 'બુકિંગ આઈડી',
  firstFree: 'પહેલું મફત',
  free: 'મફત',
  firstConsultationFree: 'પ્રથમ કન્સલ્ટેશન મફત',
  legalExpert: 'કાનૂની નિષ્ણાત',
  confirmedTitle: 'બુકિંગની પુષ્ટિ થઈ',
  confirmedMessage: 'તમારું કન્સલ્ટેશન નક્કી થયું છે. નીચે વિગતો જુઓ.',
  goToDashboard: 'મારા ડેશબોર્ડ પર જાઓ',
  securePaymentNote: 'ચુકવણી સુરક્ષિત છે. વકીલ રદ કરે અથવા સમય બદલે તો સંપૂર્ણ રિફંડ મળશે.',
  confirmFreeBooking: 'મફત બુકિંગની પુષ્ટિ કરો',
  termsPrefix: 'પુષ્ટિ કરીને તમે LexIndia ના ',
  termsSuffix: 'ને સ્વીકારો છો.',
  slotTaken: 'આ સમય હમણાં જ લેવામાં આવ્યો છે. કૃપા કરીને બીજો પસંદ કરો.',
  paymentLoadFailed: 'પેમેન્ટ ગેટવે લોડ થયું નથી. કૃપા કરીને કનેક્શન તપાસો.',
  paymentVerifyFailed: 'ચુકવણી ચકાસણી નિષ્ફળ રહી. કૃપા કરીને સહાયતા સંપર્ક કરો.',
  networkError: 'નેટવર્ક ભૂલ. કૃપા કરીને ફરી પ્રયત્ન કરો.',
  modes: {
    VIDEO: 'વિડિયો કૉલ',
    CALL: 'વૉઇસ કૉલ',
    CHAT: 'ચેટ',
    IN_PERSON: 'સામે-સામે',
  },
};

const URDU_COPY: BookingCopy = {
  lawyerNotFoundTitle: 'وکیل نہیں ملا',
  signInTitle: 'آگے بڑھنے کے لیے سائن اِن کریں',
  signInBody: 'مشاورت بُک کرنے کے لیے آپ کو سائن اِن کرنا ہوگا۔',
  steps: ['موڈ اور وقت', 'تفصیلات', 'تصدیق'],
  selectMode: '1. مشاورت کا موڈ منتخب کریں',
  selectDate: '2. تاریخ منتخب کریں',
  selectTime: '3. وقت منتخب کریں',
  issueTitle: 'اپنا قانونی مسئلہ مختصر طور پر لکھیں',
  issueHint: 'کم از کم 20 حروف لکھیں تاکہ وکیل تیاری کر سکے۔',
  issuePlaceholder: 'مثال: کرایہ کی ڈپازٹ رقم پر میرا تنازع ہے۔',
  uploadTitle: 'دستاویزات',
  uploadComingSoon: 'دستاویز اپ لوڈ کی سہولت جلد آرہی ہے۔',
  orderSummary: 'آرڈر کا خلاصہ',
  lawyerLabel: 'وکیل',
  scheduleLabel: 'تاریخ اور وقت',
  modeLabel: 'موڈ',
  totalLabel: 'کل رقم',
  amountLabel: 'رقم',
  bookingIdLabel: 'بُکنگ آئی ڈی',
  firstFree: 'پہلی مفت',
  free: 'مفت',
  firstConsultationFree: 'پہلی مشاورت مفت',
  legalExpert: 'قانونی ماہر',
  confirmedTitle: 'بُکنگ کی تصدیق ہوگئی',
  confirmedMessage: 'آپ کی مشاورت طے ہوگئی ہے۔ نیچے تفصیلات دیکھیں۔',
  goToDashboard: 'میرے ڈیش بورڈ پر جائیں',
  securePaymentNote: 'ادائیگی محفوظ ہے۔ وکیل منسوخ کرے یا وقت بدلے تو مکمل رقم واپس ملے گی۔',
  confirmFreeBooking: 'مفت بُکنگ کی تصدیق کریں',
  termsPrefix: 'تصدیق کرکے آپ LexIndia کی ',
  termsSuffix: 'سے متفق ہوتے ہیں۔',
  slotTaken: 'یہ وقت ابھی لیا جا چکا ہے۔ براہ کرم دوسرا منتخب کریں۔',
  paymentLoadFailed: 'ادائیگی کا گیٹ وے لوڈ نہیں ہوا۔ براہ کرم کنکشن چیک کریں۔',
  paymentVerifyFailed: 'ادائیگی کی تصدیق ناکام رہی۔ براہ کرم سپورٹ سے رابطہ کریں۔',
  networkError: 'نیٹ ورک خرابی۔ دوبارہ کوشش کریں۔',
  modes: {
    VIDEO: 'ویڈیو کال',
    CALL: 'وائس کال',
    CHAT: 'چیٹ',
    IN_PERSON: 'رو برو',
  },
};

const KANNADA_COPY: BookingCopy = {
  lawyerNotFoundTitle: 'ವಕೀಲರು ಸಿಗಲಿಲ್ಲ',
  signInTitle: 'ಮುಂದುವರಿಸಲು ಸೈನ್ ಇನ್ ಮಾಡಿ',
  signInBody: 'ಸಲಹೆ ಬುಕ್ ಮಾಡಲು ನೀವು ಸೈನ್ ಇನ್ ಆಗಿರಬೇಕು.',
  steps: ['ಮೋಡ್ ಮತ್ತು ಸಮಯ', 'ವಿವರಗಳು', 'ದೃಢೀಕರಿಸಿ'],
  selectMode: '1. ಸಲಹೆಯ ಮೋಡ್ ಆಯ್ಕೆಮಾಡಿ',
  selectDate: '2. ದಿನಾಂಕ ಆಯ್ಕೆಮಾಡಿ',
  selectTime: '3. ಸಮಯ ಆಯ್ಕೆಮಾಡಿ',
  issueTitle: 'ನಿಮ್ಮ ಕಾನೂನು ಸಮಸ್ಯೆಯನ್ನು ಸಂಕ್ಷಿಪ್ತವಾಗಿ ವಿವರಿಸಿ',
  issueHint: 'ವಕೀಲರು ಸಿದ್ಧರಾಗಲು ಕನಿಷ್ಠ 20 ಅಕ್ಷರಗಳನ್ನು ಬರೆಯಿರಿ.',
  issuePlaceholder: 'ಉದಾಹರಣೆ: ಬಾಡಿಗೆ ಠೇವಣಿಯ ಬಗ್ಗೆ ನನಗೆ ವಿವಾದವಿದೆ.',
  uploadTitle: 'ದಾಖಲೆಗಳು',
  uploadComingSoon: 'ದಾಖಲೆ ಅಪ್‌ಲೋಡ್ ಸೌಲಭ್ಯ ಶೀಘ್ರದಲ್ಲೇ ಬರುತ್ತದೆ.',
  orderSummary: 'ಆರ್ಡರ್ ಸಾರಾಂಶ',
  lawyerLabel: 'ವಕೀಲರು',
  scheduleLabel: 'ದಿನಾಂಕ ಮತ್ತು ಸಮಯ',
  modeLabel: 'ಮೋಡ್',
  totalLabel: 'ಒಟ್ಟು ಮೊತ್ತ',
  amountLabel: 'ಮೊತ್ತ',
  bookingIdLabel: 'ಬುಕ್ಕಿಂಗ್ ಐಡಿ',
  firstFree: 'ಮೊದಲದು ಉಚಿತ',
  free: 'ಉಚಿತ',
  firstConsultationFree: 'ಮೊದಲ ಸಲಹೆ ಉಚಿತ',
  legalExpert: 'ಕಾನೂನು ಪರಿಣಿತಿ',
  confirmedTitle: 'ಬುಕ್ಕಿಂಗ್ ದೃಢೀಕರಿಸಲಾಗಿದೆ',
  confirmedMessage: 'ನಿಮ್ಮ ಸಲಹೆ ನಿಗದಿಯಾಗಿದೆ. ಕೆಳಗಿನ ವಿವರಗಳನ್ನು ನೋಡಿ.',
  goToDashboard: 'ನನ್ನ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್‌ಗೆ ಹೋಗಿ',
  securePaymentNote: 'ಪಾವತಿ ಸುರಕ್ಷಿತವಾಗಿದೆ. ವಕೀಲರು ರದ್ದು ಮಾಡಿದರೆ ಅಥವಾ ಸಮಯ ಬದಲಿಸಿದರೆ ಪೂರ್ಣ ಮರುಪಾವತಿ ಸಿಗುತ್ತದೆ.',
  confirmFreeBooking: 'ಉಚಿತ ಬುಕ್ಕಿಂಗ್ ದೃಢೀಕರಿಸಿ',
  termsPrefix: 'ದೃಢೀಕರಿಸುವ ಮೂಲಕ ನೀವು LexIndia ನ ',
  termsSuffix: 'ಗೆ ಒಪ್ಪುತ್ತೀರಿ.',
  slotTaken: 'ಈ ಸಮಯ ಇತ್ತೀಚೆಗೆ ತೆಗೆದುಕೊಳ್ಳಲಾಗಿದೆ. ದಯವಿಟ್ಟು ಬೇರೆದು ಆಯ್ಕೆಮಾಡಿ.',
  paymentLoadFailed: 'ಪಾವತಿ ಗೇಟ್‌ವೇ ಲೋಡ್ ಆಗಲಿಲ್ಲ. ದಯವಿಟ್ಟು ಸಂಪರ್ಕ ಪರಿಶೀಲಿಸಿ.',
  paymentVerifyFailed: 'ಪಾವತಿ ಪರಿಶೀಲನೆ ವಿಫಲವಾಗಿದೆ. ದಯವಿಟ್ಟು ಸಹಾಯವನ್ನು ಸಂಪರ್ಕಿಸಿ.',
  networkError: 'ನೆಟ್ವರ್ಕ್ ದೋಷ. ದಯವಿಟ್ಟು ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.',
  modes: {
    VIDEO: 'ವೀಡಿಯೊ ಕರೆ',
    CALL: 'ಧ್ವನಿ ಕರೆ',
    CHAT: 'ಚಾಟ್',
    IN_PERSON: 'ಮುಖಾಮುಖಿ',
  },
};

const ORIYA_COPY: BookingCopy = {
  lawyerNotFoundTitle: 'ଓକିଲ ମିଳିଲେ ନାହିଁ',
  signInTitle: 'ଆଗକୁ ବଢିବା ପାଇଁ ସାଇନ୍ ଇନ୍ କରନ୍ତୁ',
  signInBody: 'ପରାମର୍ଶ ବୁକ୍ କରିବା ପାଇଁ ଆପଣଙ୍କୁ ସାଇନ୍ ଇନ୍ କରିବାକୁ ପଡିବ।',
  steps: ['ମୋଡ୍ ଏବଂ ସମୟ', 'ବିବରଣୀ', 'ନିଶ୍ଚିତି'],
  selectMode: '1. ପରାମର୍ଶ ମୋଡ୍ ବାଛନ୍ତୁ',
  selectDate: '2. ତାରିଖ ବାଛନ୍ତୁ',
  selectTime: '3. ସମୟ ବାଛନ୍ତୁ',
  issueTitle: 'ଆପଣଙ୍କ ଆଇନଗତ ସମସ୍ୟାକୁ ସଂକ୍ଷିପ୍ତରେ ଲେଖନ୍ତୁ',
  issueHint: 'ଓକିଲ ପ୍ରସ୍ତୁତ ହେବା ପାଇଁ କମ୍ ସେ କମ୍ 20 ଅକ୍ଷର ଲେଖନ୍ତୁ।',
  issuePlaceholder: 'ଉଦାହରଣ: ଭଡା ଡିପୋଜିଟ୍ ବିଷୟରେ ମୋର ବିବାଦ ଅଛି।',
  uploadTitle: 'ଦଳିଲ',
  uploadComingSoon: 'ଦଳିଲ ଅପଲୋଡ୍ ସୁବିଧା ଶୀଘ୍ର ଆସୁଛି।',
  orderSummary: 'ଅର୍ଡର ସାରାଂଶ',
  lawyerLabel: 'ଓକିଲ',
  scheduleLabel: 'ତାରିଖ ଏବଂ ସମୟ',
  modeLabel: 'ମୋଡ୍',
  totalLabel: 'ମୋଟ ରାଶି',
  amountLabel: 'ରାଶି',
  bookingIdLabel: 'ବୁକିଂ ଆଇଡି',
  firstFree: 'ପ୍ରଥମଟି ମାଗଣା',
  free: 'ମାଗଣା',
  firstConsultationFree: 'ପ୍ରଥମ ପରାମର୍ଶ ମାଗଣା',
  legalExpert: 'ଆଇନଗତ ବିଶେଷଜ୍ଞ',
  confirmedTitle: 'ବୁକିଂ ନିଶ୍ଚିତ ହୋଇଛି',
  confirmedMessage: 'ଆପଣଙ୍କ ପରାମର୍ଶ ନିର୍ଦ୍ଧାରିତ ହୋଇଛି। ତଳେ ବିବରଣୀ ଦେଖନ୍ତୁ।',
  goToDashboard: 'ମୋ ଡ୍ୟାଶବୋର୍ଡକୁ ଯାନ୍ତୁ',
  securePaymentNote: 'ଭୁଗତାନ ସୁରକ୍ଷିତ। ଓକିଲ ବାତିଲ୍ କଲେ କିମ୍ବା ସମୟ ବଦଳାଇଲେ ପୂର୍ଣ୍ଣ ଫେରତ ମିଳିବ।',
  confirmFreeBooking: 'ମାଗଣା ବୁକିଂ ନିଶ୍ଚିତ କରନ୍ତୁ',
  termsPrefix: 'ନିଶ୍ଚିତ କରି ଆପଣ LexIndia ର ',
  termsSuffix: 'କୁ ସ୍ୱୀକାର କରୁଛନ୍ତି।',
  slotTaken: 'ଏହି ସମୟ ଏମିତିକି ନିଆଯାଇଛି। ଦୟାକରି ଅନ୍ୟଟି ବାଛନ୍ତୁ।',
  paymentLoadFailed: 'ପେମେଣ୍ଟ ଗେଟୱେ ଲୋଡ୍ ହେଲା ନାହିଁ। ଦୟାକରି ସଂଯୋଗ ଯାଞ୍ଚ କରନ୍ତୁ।',
  paymentVerifyFailed: 'ଭୁଗତାନ ଯାଞ୍ଚ ବିଫଳ। ଦୟାକରି ସହାୟତା ସହିତ ଯୋଗାଯୋଗ କରନ୍ତୁ।',
  networkError: 'ନେଟୱର୍କ ତ୍ରୁଟି। ଦୟାକରି ପୁନଃଚେଷ୍ଟା କରନ୍ତୁ।',
  modes: {
    VIDEO: 'ଭିଡିଓ କଲ୍',
    CALL: 'ଭଏସ୍ କଲ୍',
    CHAT: 'ଚାଟ୍',
    IN_PERSON: 'ସାକ୍ଷାତ୍',
  },
};

const PUNJABI_COPY: BookingCopy = {
  lawyerNotFoundTitle: 'ਵਕੀਲ ਨਹੀਂ ਮਿਲਿਆ',
  signInTitle: 'ਅੱਗੇ ਵਧਣ ਲਈ ਸਾਈਨ ਇਨ ਕਰੋ',
  signInBody: 'ਮਸ਼ਵਰਾ ਬੁੱਕ ਕਰਨ ਲਈ ਤੁਹਾਨੂੰ ਸਾਈਨ ਇਨ ਕਰਨਾ ਪਵੇਗਾ।',
  steps: ['ਮੋਡ ਅਤੇ ਸਮਾਂ', 'ਵੇਰਵੇ', 'ਪੁਸ਼ਟੀ'],
  selectMode: '1. ਮਸ਼ਵਰੇ ਦਾ ਮੋਡ ਚੁਣੋ',
  selectDate: '2. ਤਾਰੀਖ ਚੁਣੋ',
  selectTime: '3. ਸਮਾਂ ਚੁਣੋ',
  issueTitle: 'ਆਪਣਾ ਕਾਨੂੰਨੀ ਮਸਲਾ ਸੰਖੇਪ ਵਿੱਚ ਲਿਖੋ',
  issueHint: 'ਵਕੀਲ ਨੂੰ ਤਿਆਰੀ ਲਈ ਘੱਟੋ-ਘੱਟ 20 ਅੱਖਰ ਲਿਖੋ।',
  issuePlaceholder: 'ਉਦਾਹਰਨ: ਕਿਰਾਏ ਦੀ ਡਿਪਾਜ਼ਿਟ ਰਕਮ ਉੱਤੇ ਮੇਰਾ ਵਿਵਾਦ ਹੈ।',
  uploadTitle: 'ਦਸਤਾਵੇਜ਼',
  uploadComingSoon: 'ਦਸਤਾਵੇਜ਼ ਅਪਲੋਡ ਸਹੂਲਤ ਜਲਦੀ ਆ ਰਹੀ ਹੈ।',
  orderSummary: 'ਆਰਡਰ ਸੰਖੇਪ',
  lawyerLabel: 'ਵਕੀਲ',
  scheduleLabel: 'ਤਾਰੀਖ ਅਤੇ ਸਮਾਂ',
  modeLabel: 'ਮੋਡ',
  totalLabel: 'ਕੁੱਲ ਰਕਮ',
  amountLabel: 'ਰਕਮ',
  bookingIdLabel: 'ਬੁੱਕਿੰਗ ਆਈਡੀ',
  firstFree: 'ਪਹਿਲਾ ਮੁਫ਼ਤ',
  free: 'ਮੁਫ਼ਤ',
  firstConsultationFree: 'ਪਹਿਲਾ ਮਸ਼ਵਰਾ ਮੁਫ਼ਤ',
  legalExpert: 'ਕਾਨੂੰਨੀ ਮਾਹਿਰ',
  confirmedTitle: 'ਬੁੱਕਿੰਗ ਪੁਸ਼ਟ ਹੋ ਗਈ',
  confirmedMessage: 'ਤੁਹਾਡਾ ਮਸ਼ਵਰਾ ਤੈਅ ਹੋ ਗਿਆ ਹੈ। ਹੇਠਾਂ ਵੇਰਵੇ ਵੇਖੋ।',
  goToDashboard: 'ਮੇਰੇ ਡੈਸ਼ਬੋਰਡ ਤੇ ਜਾਓ',
  securePaymentNote: 'ਭੁਗਤਾਨ ਸੁਰੱਖਿਅਤ ਹੈ। ਵਕੀਲ ਰੱਦ ਕਰੇ ਜਾਂ ਸਮਾਂ ਬਦਲੇ ਤਾਂ ਪੂਰਾ ਰਿਫੰਡ ਮਿਲੇਗਾ।',
  confirmFreeBooking: 'ਮੁਫ਼ਤ ਬੁੱਕਿੰਗ ਦੀ ਪੁਸ਼ਟੀ ਕਰੋ',
  termsPrefix: 'ਪੁਸ਼ਟੀ ਕਰਕੇ ਤੁਸੀਂ LexIndia ਦੀਆਂ ',
  termsSuffix: 'ਨੂੰ ਮਨਜ਼ੂਰ ਕਰਦੇ ਹੋ।',
  slotTaken: 'ਇਹ ਸਮਾਂ ਹੁਣੇ ਹੀ ਲਿਆ ਗਿਆ ਹੈ। ਕਿਰਪਾ ਕਰਕੇ ਹੋਰ ਸਮਾਂ ਚੁਣੋ।',
  paymentLoadFailed: 'ਪੇਮੈਂਟ ਗੇਟਵੇ ਲੋਡ ਨਹੀਂ ਹੋਇਆ। ਕਿਰਪਾ ਕਰਕੇ ਕਨੈਕਸ਼ਨ ਚੈੱਕ ਕਰੋ।',
  paymentVerifyFailed: 'ਭੁਗਤਾਨ ਦੀ ਜਾਂਚ ਅਸਫਲ ਰਹੀ। ਕਿਰਪਾ ਕਰਕੇ ਸਹਾਇਤਾ ਨਾਲ ਸੰਪਰਕ ਕਰੋ।',
  networkError: 'ਨੈੱਟਵਰਕ ਗਲਤੀ। ਕਿਰਪਾ ਕਰਕੇ ਫਿਰ ਕੋਸ਼ਿਸ਼ ਕਰੋ।',
  modes: {
    VIDEO: 'ਵੀਡੀਓ ਕਾਲ',
    CALL: 'ਵੌਇਸ ਕਾਲ',
    CHAT: 'ਚੈਟ',
    IN_PERSON: 'ਸਾਮ੍ਹਣੇ-ਸਾਮ੍ਹਣੇ',
  },
};

const MALAYALAM_COPY: BookingCopy = {
  lawyerNotFoundTitle: 'അഭിഭാഷകനെ കണ്ടെത്താനായില്ല',
  signInTitle: 'തുടരാൻ സൈൻ ഇൻ ചെയ്യുക',
  signInBody: 'കൺസൾട്ടേഷൻ ബുക്ക് ചെയ്യാൻ നിങ്ങൾ സൈൻ ഇൻ ചെയ്യണം.',
  steps: ['മോഡ് & സമയം', 'വിവരങ്ങൾ', 'സ്ഥിരീകരണം'],
  selectMode: '1. കൺസൾട്ടേഷൻ മോഡ് തിരഞ്ഞെടുക്കുക',
  selectDate: '2. തീയതി തിരഞ്ഞെടുക്കുക',
  selectTime: '3. സമയം തിരഞ്ഞെടുക്കുക',
  issueTitle: 'നിങ്ങളുടെ നിയമ പ്രശ്നം ചുരുക്കത്തിൽ വിവരിക്കുക',
  issueHint: 'അഭിഭാഷകൻ തയ്യാറാകാൻ കുറഞ്ഞത് 20 അക്ഷരങ്ങൾ എഴുതുക.',
  issuePlaceholder: 'ഉദാഹരണം: വാടക ഡിപ്പോസിറ്റിനെ കുറിച്ച് എനിക്ക് തർക്കമുണ്ട്.',
  uploadTitle: 'രേഖകൾ',
  uploadComingSoon: 'രേഖ അപ്‌ലോഡ് സൗകര്യം ഉടൻ ലഭ്യമാകും.',
  orderSummary: 'ഓർഡർ സംഗ്രഹം',
  lawyerLabel: 'അഭിഭാഷകൻ',
  scheduleLabel: 'തീയതിയും സമയവും',
  modeLabel: 'മോഡ്',
  totalLabel: 'ആകെ തുക',
  amountLabel: 'തുക',
  bookingIdLabel: 'ബുക്കിംഗ് ഐഡി',
  firstFree: 'ആദ്യത് സൗജന്യം',
  free: 'സൗജന്യം',
  firstConsultationFree: 'ആദ്യ കൺസൾട്ടേഷൻ സൗജന്യം',
  legalExpert: 'നിയമ വിദഗ്ധൻ',
  confirmedTitle: 'ബുക്കിംഗ് സ്ഥിരീകരിച്ചു',
  confirmedMessage: 'നിങ്ങളുടെ കൺസൾട്ടേഷൻ നിശ്ചയിച്ചിരിക്കുന്നു. താഴെയുള്ള വിവരങ്ങൾ കാണുക.',
  goToDashboard: 'എന്റെ ഡാഷ്ബോർഡിലേക്ക് പോകുക',
  securePaymentNote: 'പേയ്മെന്റ് സുരക്ഷിതമാണ്. അഭിഭാഷകൻ റദ്ദാക്കിയാൽ മുഴുവൻ റീഫണ്ട് ലഭിക്കും.',
  confirmFreeBooking: 'സൗജന്യ ബുക്കിംഗ് സ്ഥിരീകരിക്കുക',
  termsPrefix: 'സ്ഥിരീകരിക്കുന്നതിലൂടെ നിങ്ങൾ LexIndiaയുടെ ',
  termsSuffix: ' അംഗീകരിക്കുന്നു.',
  slotTaken: 'ഈ സമയം ഇപ്പോൾ എടുത്തുകഴിഞ്ഞു. ദയവായി മറ്റൊന്ന് തിരഞ്ഞെടുക്കുക.',
  paymentLoadFailed: 'പേയ്മെന്റ് ഗേറ്റ്‌വേ ലോഡ് ചെയ്യാനായില്ല. കണക്ഷൻ പരിശോധിക്കുക.',
  paymentVerifyFailed: 'പേയ്മെന്റ് പരിശോധന പരാജയപ്പെട്ടു. ദയവായി സഹായവുമായി ബന്ധപ്പെടുക.',
  networkError: 'നെറ്റ്വർക്ക് പിശക്. ദയവായി വീണ്ടും ശ്രമിക്കുക.',
  modes: {
    VIDEO: 'വീഡിയോ കോൾ',
    CALL: 'വോയ്സ് കോൾ',
    CHAT: 'ചാറ്റ്',
    IN_PERSON: 'നേരിൽ',
  },
};

const BHOJPURI_COPY: BookingCopy = {
  lawyerNotFoundTitle: 'वकील ना मिलल',
  signInTitle: 'आगे बढ़े खातिर साइन इन करीं',
  signInBody: 'परामर्श बुक करे खातिर रउरा के साइन इन करे के पड़ी।',
  steps: ['मोड आ समय', 'विवरण', 'पुष्टि'],
  selectMode: '1. परामर्श मोड चुनीं',
  selectDate: '2. तारीख चुनीं',
  selectTime: '3. समय चुनीं',
  issueTitle: 'अपना कानूनी समस्या के संक्षेप में बताईं',
  issueHint: 'वकील तैयारी कर सको, एह खातिर कम से कम 20 अक्षर लिखीं।',
  issuePlaceholder: 'उदाहरण: किराया जमा राशि पर हमार विवाद बा।',
  uploadTitle: 'दस्तावेज',
  uploadComingSoon: 'दस्तावेज अपलोड सुविधा जल्दी आई।',
  orderSummary: 'ऑर्डर सारांश',
  lawyerLabel: 'वकील',
  scheduleLabel: 'तारीख आ समय',
  modeLabel: 'मोड',
  totalLabel: 'कुल राशि',
  amountLabel: 'राशि',
  bookingIdLabel: 'बुकिंग आईडी',
  firstFree: 'पहिला मुफ्त',
  free: 'मुफ्त',
  firstConsultationFree: 'पहिला परामर्श मुफ्त',
  legalExpert: 'कानूनी विशेषज्ञ',
  confirmedTitle: 'बुकिंग के पुष्टि हो गइल',
  confirmedMessage: 'रउरा परामर्श तय हो गइल बा। नीचे विवरण देखीं।',
  goToDashboard: 'हमार डैशबोर्ड पर जाईं',
  securePaymentNote: 'भुगतान सुरक्षित बा। वकील रद्द करीं या समय बदलीं त पूरा रिफंड मिली।',
  confirmFreeBooking: 'मुफ्त बुकिंग के पुष्टि करीं',
  termsPrefix: 'पुष्टि करके रउरा LexIndia के ',
  termsSuffix: ' मानत बानी।',
  slotTaken: 'ई समय अभीए ले लिहल गइल बा। कृपया दूसरा चुनीं।',
  paymentLoadFailed: 'पेमेंट गेटवे लोड ना भइल। कृपया कनेक्शन जाँचीं।',
  paymentVerifyFailed: 'भुगतान जाँच असफल रहल। कृपया सहायता से संपर्क करीं।',
  networkError: 'नेटवर्क गलती। फेरु कोशिश करीं।',
  modes: {
    VIDEO: 'वीडियो कॉल',
    CALL: 'आवाज कॉल',
    CHAT: 'चैट',
    IN_PERSON: 'सामने-सामने',
  },
};

const BH_COPY: BookingCopy = {
  lawyerNotFoundTitle: 'वकील नहि भेटल',
  signInTitle: 'आगाँ बढ़बा लेल साइन इन करू',
  signInBody: 'परामर्श बुक करबा लेल अहाँके साइन इन करए पड़त।',
  steps: ['मोड आ समय', 'विवरण', 'पुष्टि'],
  selectMode: '1. परामर्श मोड चुनू',
  selectDate: '2. तारीख चुनू',
  selectTime: '3. समय चुनू',
  issueTitle: 'अपन कानूनी समस्या संक्षेपमे लिखू',
  issueHint: 'वकील तैयारी करि सकथि, एहि लेल कम सँ कम 20 अक्षर लिखू।',
  issuePlaceholder: 'उदाहरण: किराया जमा रकम पर हमर विवाद अछि।',
  uploadTitle: 'दस्तावेज',
  uploadComingSoon: 'दस्तावेज अपलोड सुविधा जल्दी आओत।',
  orderSummary: 'ऑर्डर सारांश',
  lawyerLabel: 'वकील',
  scheduleLabel: 'तारीख आ समय',
  modeLabel: 'मोड',
  totalLabel: 'कुल राशि',
  amountLabel: 'राशि',
  bookingIdLabel: 'बुकिंग आईडी',
  firstFree: 'पहिल मुफ्त',
  free: 'मुफ्त',
  firstConsultationFree: 'पहिल परामर्श मुफ्त',
  legalExpert: 'कानूनी विशेषज्ञ',
  confirmedTitle: 'बुकिंगक पुष्टि भऽ गेल',
  confirmedMessage: 'अहाँक परामर्श निर्धारित भऽ गेल अछि। नीचाँ विवरण देखू।',
  goToDashboard: 'हमर डैशबोर्ड पर जाउ',
  securePaymentNote: 'भुगतान सुरक्षित अछि। वकील रद्द करथि वा समय बदलथि तँ पूर्ण रिफंड भेटत।',
  confirmFreeBooking: 'मुफ्त बुकिंगक पुष्टि करू',
  termsPrefix: 'पुष्टि कऽ कए अहाँ LexIndia क ',
  termsSuffix: ' स्वीकार करैत छी।',
  slotTaken: 'ई समय अखने लेल जा चुकल अछि। कृपया दोसर चुनू।',
  paymentLoadFailed: 'पेमेंट गेटवे लोड नहि भेल। कृपया कनेक्शन जाँचू।',
  paymentVerifyFailed: 'भुगतान जाँच असफल भेल। कृपया सहायता सँ संपर्क करू।',
  networkError: 'नेटवर्क त्रुटि। फेर प्रयास करू।',
  modes: {
    VIDEO: 'वीडियो कॉल',
    CALL: 'वॉइस कॉल',
    CHAT: 'चैट',
    IN_PERSON: 'सामना-सामनी',
  },
};

const BOOKING_COPY: Record<Locale, BookingCopy> = {
  en: ENGLISH_COPY,
  hi: HINDI_COPY,
  bn: BENGALI_COPY,
  te: TELUGU_COPY,
  mr: MARATHI_COPY,
  ta: TAMIL_COPY,
  gu: GUJARATI_COPY,
  ur: URDU_COPY,
  kn: KANNADA_COPY,
  or: ORIYA_COPY,
  pa: PUNJABI_COPY,
  ml: MALAYALAM_COPY,
  bho: BHOJPURI_COPY,
  bh: BH_COPY,
};

export function getBookingCopy(locale: Locale): BookingCopy {
  return BOOKING_COPY[locale] ?? BOOKING_COPY.en;
}

export function getBookingDisplayLocale(locale: Locale): string {
  return getDisplayLocale(locale);
}
