import { getBookingCopy } from '@/lib/content/booking';
import { defineLocalizedText, getLocalizedText } from '@/lib/content/localized';
import type { Locale } from '@/lib/i18n/config';
import { formatCurrency, formatNumber } from '@/lib/i18n/format';

const TEXT = {
  activeState: defineLocalizedText('active', {
    hi: 'सक्रिय',
    bn: 'সক্রিয়',
    te: 'సక్రియం',
    mr: 'सक्रिय',
    ta: 'செயலில்',
    gu: 'સક્રિય',
    ur: 'فعال',
    kn: 'ಸಕ್ರಿಯ',
    or: 'ସକ୍ରିୟ',
    pa: 'ਸਕ੍ਰਿਆ',
    ml: 'സജീവം',
    bho: 'सक्रिय',
    bh: 'सक्रिय',
  }),
  verifiedLawyerAria: defineLocalizedText('Verified lawyer', {
    hi: 'सत्यापित वकील',
    bn: 'যাচাইকৃত আইনজীবী',
    te: 'ధృవీకరించిన న్యాయవాది',
    mr: 'पडताळलेला वकील',
    ta: 'சரிபார்க்கப்பட்ட வழக்கறிஞர்',
    gu: 'ચકાસાયેલ વકીલ',
    ur: 'تصدیق شدہ وکیل',
    kn: 'ಪರಿಶೀಲಿತ ವಕೀಲ',
    or: 'ସତ୍ୟାପିତ ଓକିଲ',
    pa: 'ਤਸਦੀਕ ਕੀਤਾ ਵਕੀਲ',
    ml: 'സ്ഥിരീകരിച്ച അഭിഭാഷകൻ',
    bho: 'सत्यापित वकील',
    bh: 'सत्यापित वकील',
  }),
  eliteBadge: defineLocalizedText('Elite', {
    hi: 'एलीट',
    bn: 'এলিট',
    te: 'ఎలైట్',
    mr: 'एलिट',
    ta: 'எலிட்',
    gu: 'એલાઇટ',
    ur: 'ایلیٹ',
    kn: 'ಎಲೈಟ್',
    or: 'ଏଲିଟ',
    pa: 'ਐਲੀਟ',
    ml: 'എലൈറ്റ്',
    bho: 'एलीट',
    bh: 'एलीट',
  }),
  eliteTitle: defineLocalizedText('Elite member', {
    hi: 'एलीट सदस्य',
    bn: 'এলিট সদস্য',
    te: 'ఎలైట్ సభ్యుడు',
    mr: 'एलिट सदस्य',
    ta: 'எலிட் உறுப்பினர்',
    gu: 'એલાઇટ સભ્ય',
    ur: 'ایلیٹ رکن',
    kn: 'ಎಲೈಟ್ ಸದಸ್ಯ',
    or: 'ଏଲିଟ ସଦସ୍ୟ',
    pa: 'ਐਲੀਟ ਮੈਂਬਰ',
    ml: 'എലൈറ്റ് അംഗം',
    bho: 'एलीट सदस्य',
    bh: 'एलीट सदस्य',
  }),
  proBadge: defineLocalizedText('Pro', {
    hi: 'प्रो',
    bn: 'প্রো',
    te: 'ప్రో',
    mr: 'प्रो',
    ta: 'ப்ரோ',
    gu: 'પ્રો',
    ur: 'پرو',
    kn: 'ಪ್ರೋ',
    or: 'ପ୍ରୋ',
    pa: 'ਪ੍ਰੋ',
    ml: 'പ്രോ',
    bho: 'प्रो',
    bh: 'प्रो',
  }),
  proTitle: defineLocalizedText('Pro member', {
    hi: 'प्रो सदस्य',
    bn: 'প্রো সদস্য',
    te: 'ప్రో సభ్యుడు',
    mr: 'प्रो सदस्य',
    ta: 'ப்ரோ உறுப்பினர்',
    gu: 'પ્રો સભ્ય',
    ur: 'پرو رکن',
    kn: 'ಪ್ರೋ ಸದಸ್ಯ',
    or: 'ପ୍ରୋ ସଦସ୍ୟ',
    pa: 'ਪ੍ਰੋ ਮੈਂਬਰ',
    ml: 'പ്രോ അംഗം',
    bho: 'प्रो सदस्य',
    bh: 'प्रो सदस्य',
  }),
  emptyValue: defineLocalizedText('Not specified', {
    hi: 'निर्दिष्ट नहीं',
    bn: 'উল্লেখ নেই',
    te: 'పేర్కొనలేదు',
    mr: 'नमूद नाही',
    ta: 'குறிப்பிடப்படவில்லை',
    gu: 'ઉલ્લેખિત નથી',
    ur: 'درج نہیں',
    kn: 'ಸೂಚಿಸಲಾಗಿಲ್ಲ',
    or: 'ଉଲ୍ଲେଖ ନାହିଁ',
    pa: 'ਦਰਜ ਨਹੀਂ',
    ml: 'സൂചിപ്പിച്ചിട്ടില്ല',
    bho: 'बतावल नइखे',
    bh: 'उल्लेख नहि',
  }),
  availableConsultationModes: defineLocalizedText('Available consultation modes', {
    hi: 'उपलब्ध परामर्श मोड',
    bn: 'উপলব্ধ পরামর্শ মোড',
    te: 'అందుబాటులో ఉన్న సంప్రదింపు విధానాలు',
    mr: 'उपलब्ध सल्ला मोड',
    ta: 'கிடைக்கும் ஆலோசனை முறைகள்',
    gu: 'ઉપલબ્ધ પરામર્શ મોડ્સ',
    ur: 'دستیاب مشاورتی طریقے',
    kn: 'ಲಭ್ಯ ಸಲಹಾ ಮೋಡ್‌ಗಳು',
    or: 'ଉପଲବ୍ଧ ପରାମର୍ଶ ମୋଡ୍‌ଗୁଡ଼ିକ',
    pa: 'ਉਪਲਬਧ ਮਸ਼ਵਰਾ ਮੋਡ',
    ml: 'ലഭ്യമായ കൺസൾട്ടേഷൻ രീതികൾ',
    bho: 'उपलब्ध सलाह मोड',
    bh: 'उपलब्ध परामर्श मोड',
  }),
  defaultImageAlt: defineLocalizedText('Lawyer portrait', {
    hi: 'वकील की तस्वीर',
    bn: 'আইনজীবীর ছবি',
    te: 'న్యాయవాది చిత్రం',
    mr: 'वकिलाचा फोटो',
    ta: 'வழக்கறிஞர் படம்',
    gu: 'વકીલનો ફોટો',
    ur: 'وکیل کی تصویر',
    kn: 'ವಕೀಲರ ಚಿತ್ರ',
    or: 'ଓକିଲଙ୍କ ଛବି',
    pa: 'ਵਕੀਲ ਦੀ ਤਸਵੀਰ',
    ml: 'അഭിഭാഷകന്റെ ചിത്രം',
    bho: 'वकील के फोटो',
    bh: 'वकीलक फोटो',
  }),
  noLawyersBody: defineLocalizedText('Try changing the law or city filters.', {
    hi: 'कानून या शहर फ़िल्टर बदलकर देखें।',
    bn: 'আইন বা শহরের ফিল্টার বদলে দেখুন।',
    te: 'చట్టం లేదా నగర ఫిల్టర్ మార్చి చూడండి.',
    mr: 'कायदा किंवा शहर फिल्टर बदलून पाहा.',
    ta: 'சட்டம் அல்லது நகர வடிகட்டியை மாற்றிப் பாருங்கள்.',
    gu: 'કાયદો અથવા શહેર ફિલ્ટર બદલીને જુઓ.',
    ur: 'قانون یا شہر کے فلٹر بدل کر دیکھیں۔',
    kn: 'ಕಾನೂನು ಅಥವಾ ನಗರ ಫಿಲ್ಟರ್ ಬದಲಿಸಿ ನೋಡಿ.',
    or: 'ଆଇନ କିମ୍ବା ସହର ଫିଲ୍ଟର ବଦଳାଇ ଦେଖନ୍ତୁ।',
    pa: 'ਕਾਨੂੰਨ ਜਾਂ ਸ਼ਹਿਰ ਦੇ ਫਿਲਟਰ ਬਦਲ ਕੇ ਵੇਖੋ।',
    ml: 'നിയമമോ നഗരമോ ഫിൽറ്റർ മാറ്റി നോക്കൂ.',
    bho: 'कानून भा शहर फिल्टर बदल के देखीं।',
    bh: 'कानून वा शहर फिल्टर बदलि देखू।',
  }),
  notFoundTitle: defineLocalizedText('Lawyer profile not found', {
    hi: 'वकील प्रोफाइल नहीं मिली',
    bn: 'আইনজীবীর প্রোফাইল পাওয়া যায়নি',
    te: 'న్యాయవాది ప్రొఫైల్ కనబడలేదు',
    mr: 'वकील प्रोफाइल सापडली नाही',
    ta: 'வழக்கறிஞர் சுயவிவரம் கிடைக்கவில்லை',
    gu: 'વકીલ પ્રોફાઇલ મળી નથી',
    ur: 'وکیل پروفائل نہیں ملی',
    kn: 'ವಕೀಲರ ಪ್ರೊಫೈಲ್ ಸಿಗಲಿಲ್ಲ',
    or: 'ଓକିଲ ପ୍ରୋଫାଇଲ ମିଳିଲା ନାହିଁ',
    pa: 'ਵਕੀਲ ਪ੍ਰੋਫਾਈਲ ਨਹੀਂ ਮਿਲੀ',
    ml: 'അഭിഭാഷക പ്രൊഫൈൽ ലഭിച്ചില്ല',
    bho: 'वकील प्रोफाइल ना मिलल',
    bh: 'वकील प्रोफाइल नहि भेटल',
  }),
  notFoundBody: defineLocalizedText('This profile may have been removed or the link may be incorrect.', {
    hi: 'यह प्रोफाइल हटाई गई हो सकती है या लिंक गलत हो सकता है।',
    bn: 'এই প্রোফাইল সরানো হয়ে থাকতে পারে বা লিঙ্কটি ভুল হতে পারে।',
    te: 'ఈ ప్రొఫైల్ తొలగించబడివుండవచ్చు లేదా లింక్ తప్పుగా ఉండవచ్చు.',
    mr: 'ही प्रोफाइल काढली गेली असू शकते किंवा लिंक चुकीची असू शकते.',
    ta: 'இந்த சுயவிவரம் நீக்கப்பட்டிருக்கலாம் அல்லது இணைப்பு தவறாக இருக்கலாம்.',
    gu: 'આ પ્રોફાઇલ દૂર કરાઈ હોઈ શકે છે અથવા લિંક ખોટી હોઈ શકે છે.',
    ur: 'یہ پروفائل ہٹائی جا چکی ہو سکتی ہے یا لنک غلط ہو سکتا ہے۔',
    kn: 'ಈ ಪ್ರೊಫೈಲ್ ತೆಗೆದುಹಾಕಲ್ಪಟ್ಟಿರಬಹುದು ಅಥವಾ ಲಿಂಕ್ ತಪ್ಪಾಗಿರಬಹುದು.',
    or: 'ଏହି ପ୍ରୋଫାଇଲ ହଟାଯାଇଥାଇପାରେ କିମ୍ବା ଲିଙ୍କ ଭୁଲ ହୋଇପାରେ।',
    pa: 'ਇਹ ਪ੍ਰੋਫਾਈਲ ਹਟਾਈ ਗਈ ਹੋ ਸਕਦੀ ਹੈ ਜਾਂ ਲਿੰਕ ਗਲਤ ਹੋ ਸਕਦਾ ਹੈ।',
    ml: 'ഈ പ്രൊഫൈൽ നീക്കം ചെയ്തിരിക്കാം അല്ലെങ്കിൽ ലിങ്ക് തെറ്റായിരിക്കാം.',
    bho: 'ई प्रोफाइल हटावल गइल हो सकेला भा लिंक गलत हो सकेला।',
    bh: 'ई प्रोफाइल हटाओल गेल हो सकैत अछि वा लिंक गलत भऽ सकैत अछि।',
  }),
  errorTitle: defineLocalizedText('Something went wrong', {
    hi: 'कुछ गलत हो गया',
    bn: 'কিছু ভুল হয়েছে',
    te: 'ఏదో తప్పు జరిగింది',
    mr: 'काहीतरी चुकले',
    ta: 'ஏதோ தவறு ஏற்பட்டது',
    gu: 'કંઈક ખોટું થયું',
    ur: 'کچھ غلط ہو گیا',
    kn: 'ಏನೋ ತಪ್ಪಾಗಿದೆ',
    or: 'କିଛି ଭୁଲ ହେଲା',
    pa: 'ਕੁਝ ਗਲਤ ਹੋ ਗਿਆ',
    ml: 'ഏതോ പിഴവ് സംഭവിച്ചു',
    bho: 'कुछ गड़बड़ हो गइल',
    bh: 'किछु गलत भऽ गेल',
  }),
  errorBody: defineLocalizedText('Unable to load this lawyer profile right now.', {
    hi: 'अभी इस वकील प्रोफाइल को लोड नहीं किया जा सका।',
    bn: 'এই মুহূর্তে এই আইনজীবীর প্রোফাইল লোড করা যায়নি।',
    te: 'ప్రస్తుతం ఈ న్యాయవాది ప్రొఫైల్‌ను లోడ్ చేయలేకపోయాం.',
    mr: 'सध्या ही वकील प्रोफाइल लोड करता आली नाही.',
    ta: 'இப்போது இந்த வழக்கறிஞர் சுயவிவரத்தை ஏற்ற முடியவில்லை.',
    gu: 'હાલમાં આ વકીલ પ્રોફાઇલ લોડ થઈ શકી નથી.',
    ur: 'فی الحال اس وکیل پروفائل کو لوڈ نہیں کیا جا سکا۔',
    kn: 'ಈ ಕ್ಷಣದಲ್ಲಿ ಈ ವಕೀಲರ ಪ್ರೊಫೈಲ್ ಲೋಡ್ ಆಗಲಿಲ್ಲ.',
    or: 'ଏହି ମୁହୂର୍ତ୍ତରେ ଏହି ଓକିଲ ପ୍ରୋଫାଇଲ ଲୋଡ୍ ହୋଇନାହିଁ।',
    pa: 'ਇਸ ਵੇਲੇ ਇਹ ਵਕੀਲ ਪ੍ਰੋਫਾਈਲ ਲੋਡ ਨਹੀਂ ਹੋ ਸਕੀ।',
    ml: 'ഇപ്പോൾ ഈ അഭിഭാഷകന്റെ പ്രൊഫൈൽ ലോഡ് ചെയ്യാൻ കഴിഞ്ഞില്ല.',
    bho: 'अभी ई वकील प्रोफाइल लोड ना हो पवलस।',
    bh: 'एखन एहि वकील प्रोफाइल केँ लोड नहि कयल जा सकल।',
  }),
  backToLawyers: defineLocalizedText('Back to lawyers', {
    hi: 'वकीलों पर वापस जाएं',
    bn: 'আইনজীবীদের তালিকায় ফিরে যান',
    te: 'న్యాయవాదుల జాబితాకు తిరిగి వెళ్లండి',
    mr: 'वकिलांच्या यादीत परत जा',
    ta: 'வழக்கறிஞர் பட்டியலுக்கு திரும்பவும்',
    gu: 'વકીલોની યાદીમાં પાછા જાઓ',
    ur: 'وکیلوں کی فہرست پر واپس جائیں',
    kn: 'ವಕೀಲರ ಪಟ್ಟಿಗೆ ಹಿಂತಿರುಗಿ',
    or: 'ଓକିଲ ତାଲିକାକୁ ଫେରନ୍ତୁ',
    pa: 'ਵਕੀਲਾਂ ਦੀ ਸੂਚੀ ਵੱਲ ਵਾਪਸ ਜਾਓ',
    ml: 'അഭിഭാഷകരുടെ പട്ടികയിലേക്ക് മടങ്ങുക',
    bho: 'वकील सूची पर लौटीं',
    bh: 'वकील सूची पर वापस जाउ',
  }),
  memberSincePrefix: defineLocalizedText('Member since', {
    hi: 'सदस्यता वर्ष',
    bn: 'সদস্যতা শুরু',
    te: 'సభ్యత్వం మొదలైన సంవత్సరం',
    mr: 'सदस्यत्व पासून',
    ta: 'உறுப்பினர் ஆண்டு',
    gu: 'સભ્યતા શરૂ',
    ur: 'رکنیت منذ',
    kn: 'ಸದಸ್ಯರಾಗಿದ್ದು',
    or: 'ସଦସ୍ୟ ହୋଇଛନ୍ତି',
    pa: 'ਮੈਂਬਰ ਬਣੇ',
    ml: 'അംഗമായത്',
    bho: 'सदस्य बने तबसे',
    bh: 'सदस्य छथि',
  }),
  specialtyNotSpecified: defineLocalizedText('Specialty not specified', {
    hi: 'विशेषज्ञता निर्दिष्ट नहीं',
    bn: 'বিশেষজ্ঞতা উল্লেখ নেই',
    te: 'ప్రత్యేకత పేర్కొనలేదు',
    mr: 'विशेषता नमूद नाही',
    ta: 'சிறப்பு குறிப்பிடப்படவில்லை',
    gu: 'વિશેષતા દર્શાવેલ નથી',
    ur: 'خصوصیت درج نہیں',
    kn: 'ವಿಶೇಷತೆ ಸೂಚಿಸಲಿಲ್ಲ',
    or: 'ବିଶେଷତା ଉଲ୍ଲେଖ ନାହିଁ',
    pa: 'ਵਿਸ਼ੇਸ਼ਤਾ ਦਰਜ ਨਹੀਂ',
    ml: 'വിദഗ്ധത സൂചിപ്പിച്ചിട്ടില്ല',
    bho: 'विशेषज्ञता बतावल नइखे',
    bh: 'विशेषज्ञता उल्लेख नहि',
  }),
  about: defineLocalizedText('About', {
    hi: 'परिचय',
    bn: 'পরিচিতি',
    te: 'గురించి',
    mr: 'परिचय',
    ta: 'அறிமுகம்',
    gu: 'પરિચય',
    ur: 'تعارف',
    kn: 'ಪರಿಚಯ',
    or: 'ପରିଚୟ',
    pa: 'ਪਰਿਚਯ',
    ml: 'പരിചയം',
    bho: 'परिचय',
    bh: 'परिचय',
  }),
  noBio: defineLocalizedText('This lawyer has not added a bio yet.', {
    hi: 'इस वकील ने अभी बायो नहीं जोड़ी है।',
    bn: 'এই আইনজীবী এখনও বায়ো যোগ করেননি।',
    te: 'ఈ న్యాయవాది ఇంకా బయో చేర్చలేదు.',
    mr: 'या वकिलाने अजून बायो जोडलेली नाही.',
    ta: 'இந்த வழக்கறிஞர் இன்னும் சுயவிவரம் சேர்க்கவில்லை.',
    gu: 'આ વકીલે હજુ બાયો ઉમેર્યો નથી.',
    ur: 'اس وکیل نے ابھی تعارف شامل نہیں کیا۔',
    kn: 'ಈ ವಕೀಲರು ಇನ್ನೂ ಬಯೋ ಸೇರಿಸಿಲ್ಲ.',
    or: 'ଏହି ଓକିଲ ଏପର୍ଯ୍ୟନ୍ତ ବାୟୋ ଯୋଡ଼ିନାହାନ୍ତି।',
    pa: 'ਇਸ ਵਕੀਲ ਨੇ ਹਾਲੇ ਬਾਇਓ ਨਹੀਂ ਜੋੜੀ।',
    ml: 'ഈ അഭിഭാഷകൻ ഇനിയും ബയോ ചേർത്തിട്ടില്ല.',
    bho: 'ई वकील अभी बायो ना जोड़ले बा।',
    bh: 'ई वकील एखन बायो नहि जोड़ने छथि।',
  }),
  consultationModes: defineLocalizedText('Consultation modes', {
    hi: 'परामर्श मोड',
    bn: 'পরামর্শের ধরন',
    te: 'సంప్రదింపు విధానాలు',
    mr: 'सल्ला मोड',
    ta: 'ஆலோசனை முறைகள்',
    gu: 'પરામર્શ મોડ્સ',
    ur: 'مشاورتی طریقے',
    kn: 'ಸಲಹಾ ವಿಧಾನಗಳು',
    or: 'ପରାମର୍ଶ ମୋଡ୍‌ଗୁଡ଼ିକ',
    pa: 'ਮਸ਼ਵਰਾ ਮੋਡ',
    ml: 'കൺസൾട്ടേഷൻ രീതികൾ',
    bho: 'सलाह मोड',
    bh: 'परामर्श मोड',
  }),
  modesNotSpecified: defineLocalizedText('Modes not specified', {
    hi: 'मोड निर्दिष्ट नहीं',
    bn: 'মোড উল্লেখ নেই',
    te: 'విధానం పేర్కొనలేదు',
    mr: 'मोड नमूद नाही',
    ta: 'முறைகள் குறிப்பிடப்படவில்லை',
    gu: 'મોડ દર્શાવેલ નથી',
    ur: 'طریقے درج نہیں',
    kn: 'ಮೋಡ್ ಸೂಚಿಸಲಿಲ್ಲ',
    or: 'ମୋଡ୍ ଉଲ୍ଲେଖ ନାହିଁ',
    pa: 'ਮੋਡ ਦਰਜ ਨਹੀਂ',
    ml: 'മോഡുകൾ സൂചിപ്പിച്ചിട്ടില്ല',
    bho: 'मोड बतावल नइखे',
    bh: 'मोड उल्लेख नहि',
  }),
  verifiedLawyerTitle: defineLocalizedText('Verified lawyer', {
    hi: 'सत्यापित वकील',
    bn: 'যাচাইকৃত আইনজীবী',
    te: 'ధృవీకరించిన న్యాయవాది',
    mr: 'पडताळलेला वकील',
    ta: 'சரிபார்க்கப்பட்ட வழக்கறிஞர்',
    gu: 'ચકાસાયેલ વકીલ',
    ur: 'تصدیق شدہ وکیل',
    kn: 'ಪರಿಶೀಲಿತ ವಕೀಲ',
    or: 'ସତ୍ୟାପିତ ଓକିଲ',
    pa: 'ਤਸਦੀਕ ਕੀਤਾ ਵਕੀਲ',
    ml: 'സ്ഥിരീകരിച്ച അഭിഭാഷകൻ',
    bho: 'सत्यापित वकील',
    bh: 'सत्यापित वकील',
  }),
  verifiedLawyerBody: defineLocalizedText('Bar Council enrollment has been verified by LexIndia.', {
    hi: 'Bar Council नामांकन का सत्यापन LexIndia ने किया है।',
    bn: 'Bar Council নথিভুক্তি LexIndia দ্বারা যাচাই করা হয়েছে।',
    te: 'Bar Council నమోదు LexIndia ద్వారా ధృవీకరించబడింది.',
    mr: 'Bar Council नोंदणी LexIndia ने पडताळली आहे.',
    ta: 'Bar Council பதிவு LexIndia மூலம் சரிபார்க்கப்பட்டுள்ளது.',
    gu: 'Bar Council નોંધણી LexIndia દ્વારા ચકાસાઈ છે.',
    ur: 'Bar Council اندراج کی تصدیق LexIndia نے کی ہے۔',
    kn: 'Bar Council ನೋಂದಣಿಯನ್ನು LexIndia ಪರಿಶೀಲಿಸಿದೆ.',
    or: 'Bar Council ନାମଭର୍ତ୍ତି LexIndia ଦ୍ୱାରା ସତ୍ୟାପିତ।',
    pa: 'Bar Council ਦਰਜਾ LexIndia ਵੱਲੋਂ ਤਸਦੀਕ ਕੀਤਾ ਗਿਆ ਹੈ।',
    ml: 'Bar Council രജിസ്ട്രേഷൻ LexIndia സ്ഥിരീകരിച്ചു.',
    bho: 'Bar Council नामांकन के सत्यापन LexIndia कइले बा।',
    bh: 'Bar Council नामांकनक सत्यापन LexIndia केने अछि।',
  }),
  barCouncilId: defineLocalizedText('Bar Council ID', {
    hi: 'बार काउंसिल आईडी',
    bn: 'বার কাউন্সিল আইডি',
    te: 'బార్ కౌన్సిల్ ఐడి',
    mr: 'बार कौन्सिल आयडी',
    ta: 'பார் கவுன்சில் ஐடி',
    gu: 'બાર કાઉન્સિલ આઈડી',
    ur: 'بار کونسل آئی ڈی',
    kn: 'ಬಾರ್ ಕೌನ್ಸಿಲ್ ಐಡಿ',
    or: 'ବାର କାଉନ୍ସିଲ ଆଇଡି',
    pa: 'ਬਾਰ ਕੌਂਸਲ ਆਈਡੀ',
    ml: 'ബാർ കൗൺസിൽ ഐഡി',
    bho: 'बार काउंसिल आईडी',
    bh: 'बार काउंसिल आईडी',
  }),
  legalWarning: defineLocalizedText(
    'LexIndia verifies enrollment, but legal outcomes depend on the lawyer, facts, and court process.',
    {
      hi: 'LexIndia नामांकन सत्यापित करता है, लेकिन कानूनी परिणाम वकील, तथ्य और अदालत प्रक्रिया पर निर्भर करते हैं।',
      bn: 'LexIndia নথিভুক্তি যাচাই করে, তবে আইনি ফল আইনজীবী, তথ্য ও আদালতের প্রক্রিয়ার উপর নির্ভর করে।',
      te: 'LexIndia నమోదు ధృవీకరిస్తుంది, కానీ ఫలితం న్యాయవాది, వాస్తవాలు, న్యాయస్థాన ప్రక్రియపై ఆధారపడుతుంది.',
      mr: 'LexIndia नोंदणी पडताळते, पण निकाल वकील, तथ्य आणि न्यायालयीन प्रक्रियेवर अवलंबून असतो.',
      ta: 'LexIndia பதிவு சரிபார்க்கும், ஆனால் சட்ட முடிவு வழக்கறிஞர், விவரங்கள் மற்றும் நீதிமன்ற செயல்முறையை சார்ந்தது.',
      gu: 'LexIndia નોંધણી ચકાસે છે, પરંતુ કાનૂની પરિણામ વકીલ, હકીકતો અને કોર્ટ પ્રક્રિયા પર આધારિત છે.',
      ur: 'LexIndia اندراج کی تصدیق کرتا ہے، مگر قانونی نتیجہ وکیل، حقائق اور عدالتی عمل پر منحصر ہے۔',
      kn: 'LexIndia ನೋಂದಣಿಯನ್ನು ಪರಿಶೀಲಿಸುತ್ತದೆ, ಆದರೆ ಕಾನೂನು ಫಲಿತಾಂಶವು ವಕೀಲರು, ವಾಸ್ತವಾಂಶಗಳು ಮತ್ತು ನ್ಯಾಯಾಲಯದ ಪ್ರಕ್ರಿಯೆಯ ಮೇಲೆ ಅವಲಂಬಿತವಾಗಿರುತ್ತದೆ.',
      or: 'LexIndia ନାମଭର୍ତ୍ତି ସତ୍ୟାପନ କରେ, କିନ୍ତୁ ଆଇନି ଫଳ ଓକିଲ, ତଥ୍ୟ ଓ ଆଦାଲତ ପ୍ରକ୍ରିୟାରେ ନିର୍ଭର କରେ।',
      pa: 'LexIndia ਦਰਜਾ ਤਸਦੀਕ ਕਰਦਾ ਹੈ, ਪਰ ਕਾਨੂੰਨੀ ਨਤੀਜਾ ਵਕੀਲ, ਤੱਥਾਂ ਅਤੇ ਅਦਾਲਤੀ ਪ੍ਰਕਿਰਿਆ ਤੇ ਨਿਰਭਰ ਕਰਦਾ ਹੈ।',
      ml: 'LexIndia രജിസ്ട്രേഷൻ പരിശോധിക്കും, പക്ഷേ നിയമപരമായ ഫലം അഭിഭാഷകൻ, വസ്തുതകൾ, കോടതി നടപടികൾ എന്നിവയിൽ ആശ്രയിച്ചിരിക്കുന്നു.',
      bho: 'LexIndia नामांकन सत्यापित करेला, बाकिर कानूनी नतीजा वकील, तथ्य आ अदालत प्रक्रिया पर निर्भर होला।',
      bh: 'LexIndia नामांकन सत्यापित करैत अछि, मुदा कानूनी परिणाम वकील, तथ्य आ अदालत प्रक्रिया पर निर्भर करैत अछि।',
    }
  ),
  perConsultation: defineLocalizedText('per consultation', {
    hi: 'प्रति परामर्श',
    bn: 'প্রতি পরামর্শে',
    te: 'ప్రతి సంప్రదింపుకు',
    mr: 'प्रति सल्ला',
    ta: 'ஒவ்வோர் ஆலோசனைக்கும்',
    gu: 'પ્રતિ પરામર્શ',
    ur: 'فی مشاورت',
    kn: 'ಪ್ರತಿ ಸಲಹೆಗೆ',
    or: 'ପ୍ରତି ପରାମର୍ଶ',
    pa: 'ਪ੍ਰਤੀ ਮਸ਼ਵਰਾ',
    ml: 'ഓരോ കൺസൾട്ടേഷനും',
    bho: 'प्रति सलाह',
    bh: 'प्रति परामर्श',
  }),
  firstConsultation: defineLocalizedText('First consultation free', {
    hi: 'पहला परामर्श निःशुल्क',
    bn: 'প্রথম পরামর্শ ফ্রি',
    te: 'మొదటి సంప్రదింపు ఉచితం',
    mr: 'पहिला सल्ला मोफत',
    ta: 'முதல் ஆலோசனை இலவசம்',
    gu: 'પહેલો પરામર્શ મફત',
    ur: 'پہلی مشاورت مفت',
    kn: 'ಮೊದಲ ಸಲಹೆ ಉಚಿತ',
    or: 'ପ୍ରଥମ ପରାମର୍ଶ ମାଗଣା',
    pa: 'ਪਹਿਲਾ ਮਸ਼ਵਰਾ ਮੁਫ਼ਤ',
    ml: 'ആദ്യ കൺസൾട്ടേഷൻ സൗജന്യം',
    bho: 'पहिला सलाह मुफ्त',
    bh: 'पहिल परामर्श नि:शुल्क',
  }),
  pending: defineLocalizedText('Pending', {
    hi: 'लंबित',
    bn: 'বাকি',
    te: 'పెండింగ్',
    mr: 'प्रलंबित',
    ta: 'நிலுவை',
    gu: 'બાકી',
    ur: 'زیر التوا',
    kn: 'ಬಾಕಿ',
    or: 'ଅପେକ୍ଷାରତ',
    pa: 'ਬਾਕੀ',
    ml: 'ബാക്കിയുണ്ട്',
    bho: 'लंबित',
    bh: 'लंबित',
  }),
  notListed: defineLocalizedText('Not listed', {
    hi: 'सूचीबद्ध नहीं',
    bn: 'তালিকাভুক্ত নয়',
    te: 'జాబితాలో లేదు',
    mr: 'सूचीत नाही',
    ta: 'பட்டியலில் இல்லை',
    gu: 'સૂચિમાં નથી',
    ur: 'درج نہیں',
    kn: 'ಪಟ್ಟಿಯಲ್ಲಿ ಇಲ್ಲ',
    or: 'ତାଲିକାଭୁକ୍ତ ନୁହେଁ',
    pa: 'ਸੂਚੀਬੱਧ ਨਹੀਂ',
    ml: 'പട്ടികപ്പെടുത്തിയിട്ടില്ല',
    bho: 'सूची में नइखे',
    bh: 'सूचीमे नहि',
  }),
  needToCompare: defineLocalizedText('Need to compare?', {
    hi: 'तुलना करनी है?',
    bn: 'তুলনা করতে চান?',
    te: 'పోల్చాలనుకుంటున్నారా?',
    mr: 'तुलना करायची आहे का?',
    ta: 'ஒப்பிட வேண்டுமா?',
    gu: 'તુલના કરવી છે?',
    ur: 'موازنہ کرنا ہے؟',
    kn: 'ಹೋಲಿಕೆ ಬೇಕೇ?',
    or: 'ତୁଳନା କରିବେ କି?',
    pa: 'ਤੁਲਨਾ ਕਰਨੀ ਹੈ?',
    ml: 'താരതമ്യം വേണോ?',
    bho: 'तुलना करे के बा?',
    bh: 'तुलना करए चाहैत छी?',
  }),
  compareBody: defineLocalizedText('Browse the full directory of verified lawyers.', {
    hi: 'सत्यापित वकीलों की पूरी डायरेक्टरी देखें।',
    bn: 'যাচাইকৃত আইনজীবীদের পুরো ডিরেক্টরি দেখুন।',
    te: 'ధృవీకరించిన న్యాయవాదుల పూర్తి డైరెక్టరీని చూడండి.',
    mr: 'पडताळलेल्या वकिलांची पूर्ण निर्देशिका पहा.',
    ta: 'சரிபார்க்கப்பட்ட வழக்கறிஞர்களின் முழுப் பட்டியலைப் பாருங்கள்.',
    gu: 'ચકાસાયેલા વકીલોની સંપૂર્ણ ડિરેક્ટરી જુઓ.',
    ur: 'تصدیق شدہ وکیلوں کی مکمل ڈائریکٹری دیکھیں۔',
    kn: 'ಪರಿಶೀಲಿತ ವಕೀಲರ ಪೂರ್ಣ ಡೈರೆಕ್ಟರಿಯನ್ನು ನೋಡಿ.',
    or: 'ସତ୍ୟାପିତ ଓକିଲଙ୍କ ସମ୍ପୂର୍ଣ୍ଣ ତାଲିକା ଦେଖନ୍ତୁ।',
    pa: 'ਤਸਦੀਕ ਕੀਤੇ ਵਕੀਲਾਂ ਦੀ ਪੂਰੀ ਡਾਇਰੈਕਟਰੀ ਵੇਖੋ।',
    ml: 'സ്ഥിരീകരിച്ച അഭിഭാഷകരുടെ മുഴുവൻ ഡയറക്ടറി കാണുക.',
    bho: 'सत्यापित वकीलन के पूरा डायरेक्टरी देखीं।',
    bh: 'सत्यापित वकील सभक पूर्ण डायरेक्टरी देखू।',
  }),
  seeAllLawyers: defineLocalizedText('See all lawyers', {
    hi: 'सभी वकील देखें',
    bn: 'সব আইনজীবী দেখুন',
    te: 'అన్ని న్యాయవాదులను చూడండి',
    mr: 'सर्व वकील पहा',
    ta: 'அனைத்து வழக்கறிஞர்களையும் பார்க்கவும்',
    gu: 'બધા વકીલો જુઓ',
    ur: 'تمام وکیل دیکھیں',
    kn: 'ಎಲ್ಲಾ ವಕೀಲರನ್ನು ನೋಡಿ',
    or: 'ସମସ୍ତ ଓକିଲକୁ ଦେଖନ୍ତୁ',
    pa: 'ਸਾਰੇ ਵਕੀਲ ਵੇਖੋ',
    ml: 'എല്ലാ അഭിഭാഷകരെയും കാണുക',
    bho: 'सभे वकील देखीं',
    bh: 'सभ वकील देखू',
  }),
} as const;

const EXPERIENCE_SHORT = {
  en: (years: number) => `${years} years`,
  hi: (years: number) => `${years} वर्ष`,
  bn: (years: number) => `${years} বছর`,
  te: (years: number) => `${years} సంవత్సరాలు`,
  mr: (years: number) => `${years} वर्षे`,
  ta: (years: number) => `${years} ஆண்டு`,
  gu: (years: number) => `${years} વર્ષ`,
  ur: (years: number) => `${years} سال`,
  kn: (years: number) => `${years} ವರ್ಷ`,
  or: (years: number) => `${years} ବର୍ଷ`,
  pa: (years: number) => `${years} ਸਾਲ`,
  ml: (years: number) => `${years} വർഷം`,
  bho: (years: number) => `${years} साल`,
  bh: (years: number) => `${years} वर्ष`,
} satisfies Record<Locale, (years: number) => string>;

const EXPERIENCE_LONG = {
  en: (years: number) => `${years} years experience`,
  hi: (years: number) => `${years} वर्ष अनुभव`,
  bn: (years: number) => `${years} বছরের অভিজ্ঞতা`,
  te: (years: number) => `${years} సంవత్సరాల అనుభవం`,
  mr: (years: number) => `${years} वर्षांचा अनुभव`,
  ta: (years: number) => `${years} ஆண்டு அனுபவம்`,
  gu: (years: number) => `${years} વર્ષનો અનુભવ`,
  ur: (years: number) => `${years} سال کا تجربہ`,
  kn: (years: number) => `${years} ವರ್ಷದ ಅನುಭವ`,
  or: (years: number) => `${years} ବର୍ଷର ଅନୁଭବ`,
  pa: (years: number) => `${years} ਸਾਲ ਦਾ ਤਜਰਬਾ`,
  ml: (years: number) => `${years} വർഷത്തെ പരിചയം`,
  bho: (years: number) => `${years} साल के अनुभव`,
  bh: (years: number) => `${years} वर्षक अनुभव`,
} satisfies Record<Locale, (years: number) => string>;

const CONSULTATION_COUNT = {
  en: (count: number) => `${count} consultations`,
  hi: (count: number) => `${count} परामर्श`,
  bn: (count: number) => `${count} পরামর্শ`,
  te: (count: number) => `${count} సంప్రదింపులు`,
  mr: (count: number) => `${count} सल्ले`,
  ta: (count: number) => `${count} ஆலோசனைகள்`,
  gu: (count: number) => `${count} પરામર્શ`,
  ur: (count: number) => `${count} مشاورتیں`,
  kn: (count: number) => `${count} ಸಲಹೆಗಳು`,
  or: (count: number) => `${count} ପରାମର୍ଶ`,
  pa: (count: number) => `${count} ਮਸ਼ਵਰੇ`,
  ml: (count: number) => `${count} കൺസൾട്ടേഷനുകൾ`,
  bho: (count: number) => `${count} सलाह`,
  bh: (count: number) => `${count} परामर्श`,
} satisfies Record<Locale, (count: number) => string>;

export function getLawyerDirectoryCopy(locale: Locale) {
  return {
    activeState: getLocalizedText(TEXT.activeState, locale),
    verifiedLawyerAria: getLocalizedText(TEXT.verifiedLawyerAria, locale),
    eliteBadge: getLocalizedText(TEXT.eliteBadge, locale),
    eliteTitle: getLocalizedText(TEXT.eliteTitle, locale),
    proBadge: getLocalizedText(TEXT.proBadge, locale),
    proTitle: getLocalizedText(TEXT.proTitle, locale),
    emptyValue: getLocalizedText(TEXT.emptyValue, locale),
    availableConsultationModes: getLocalizedText(TEXT.availableConsultationModes, locale),
    defaultImageAlt: getLocalizedText(TEXT.defaultImageAlt, locale),
    noLawyersBody: getLocalizedText(TEXT.noLawyersBody, locale),
  };
}

export function getLawyerProfileCopy(locale: Locale) {
  return {
    notFoundTitle: getLocalizedText(TEXT.notFoundTitle, locale),
    notFoundBody: getLocalizedText(TEXT.notFoundBody, locale),
    errorTitle: getLocalizedText(TEXT.errorTitle, locale),
    errorBody: getLocalizedText(TEXT.errorBody, locale),
    backToLawyers: getLocalizedText(TEXT.backToLawyers, locale),
    memberSincePrefix: getLocalizedText(TEXT.memberSincePrefix, locale),
    specialtyNotSpecified: getLocalizedText(TEXT.specialtyNotSpecified, locale),
    about: getLocalizedText(TEXT.about, locale),
    noBio: getLocalizedText(TEXT.noBio, locale),
    consultationModes: getLocalizedText(TEXT.consultationModes, locale),
    modesNotSpecified: getLocalizedText(TEXT.modesNotSpecified, locale),
    verifiedLawyerTitle: getLocalizedText(TEXT.verifiedLawyerTitle, locale),
    verifiedLawyerBody: getLocalizedText(TEXT.verifiedLawyerBody, locale),
    barCouncilId: getLocalizedText(TEXT.barCouncilId, locale),
    legalWarning: getLocalizedText(TEXT.legalWarning, locale),
    perConsultation: getLocalizedText(TEXT.perConsultation, locale),
    firstConsultation: getLocalizedText(TEXT.firstConsultation, locale),
    pending: getLocalizedText(TEXT.pending, locale),
    notListed: getLocalizedText(TEXT.notListed, locale),
    needToCompare: getLocalizedText(TEXT.needToCompare, locale),
    compareBody: getLocalizedText(TEXT.compareBody, locale),
    seeAllLawyers: getLocalizedText(TEXT.seeAllLawyers, locale),
    defaultImageAlt: getLocalizedText(TEXT.defaultImageAlt, locale),
  };
}

export function formatLawyerCurrency(amount: number, locale: Locale) {
  return formatCurrency(amount, locale);
}

export function formatLawyerCompactExperience(years: number, locale: Locale) {
  return EXPERIENCE_SHORT[locale](years).replace(String(years), formatNumber(years, locale));
}

export function formatLawyerLongExperience(years: number, locale: Locale) {
  return EXPERIENCE_LONG[locale](years).replace(String(years), formatNumber(years, locale));
}

export function formatLawyerConsultationCount(count: number, locale: Locale) {
  return CONSULTATION_COUNT[locale](count).replace(String(count), formatNumber(count, locale));
}

export function getLawyerModeLabel(mode: string, locale: Locale) {
  const bookingCopy = getBookingCopy(locale);
  return bookingCopy.modes[mode as keyof typeof bookingCopy.modes] ?? mode;
}
