import { defineLocalizedText } from '@/lib/content/localized';

export const shellCopy = {
  home: defineLocalizedText('Home', {
    hi: 'होम',
    bn: 'হোম',
    te: 'హోమ్',
    mr: 'मुख्यपृष्ठ',
    ta: 'முகப்பு',
    gu: 'હોમ',
    ur: 'ہوم',
    kn: 'ಮುಖಪುಟ',
    or: 'ମୂଳପୃଷ୍ଠା',
    pa: 'ਮੁੱਖ ਪੰਨਾ',
    ml: 'ഹോം',
    bho: 'होम',
    bh: 'होम',
  }),
  noLanguagesFound: defineLocalizedText('No languages found', {
    hi: 'कोई भाषा नहीं मिली',
    bn: 'কোনো ভাষা পাওয়া যায়নি',
    te: 'భాషలు కనబడలేదు',
    mr: 'कोणतीही भाषा सापडली नाही',
    ta: 'மொழிகள் எதுவும் இல்லை',
    gu: 'કોઈ ભાષા મળી નથી',
    ur: 'کوئی زبان نہیں ملی',
    kn: 'ಯಾವುದೇ ಭಾಷೆಗಳು ಸಿಗಲಿಲ್ಲ',
    or: 'କୌଣସି ଭାଷା ମିଳିଲା ନାହିଁ',
    pa: 'ਕੋਈ ਭਾਸ਼ਾ ਨਹੀਂ ਮਿਲੀ',
    ml: 'ഭാഷകൾ കണ്ടെത്താനായില്ല',
    bho: 'कौनो भाषा नइखे मिलल',
    bh: 'कोई भाषा नै भेटल',
  }),
  logout: defineLocalizedText('Logout', {
    hi: 'लॉग आउट',
    bn: 'লগ আউট',
    te: 'లాగ్ అవుట్',
    mr: 'लॉग आउट',
    ta: 'வெளியேறு',
    gu: 'લોગ આઉટ',
    ur: 'لاگ آؤٹ',
    kn: 'ಲಾಗ್ ಔಟ್',
    or: 'ଲଗ୍ ଆଉଟ',
    pa: 'ਲਾਗ ਆਉਟ',
    ml: 'ലോഗ് ഔട്ട്',
    bho: 'लॉग आउट',
    bh: 'लॉग आउट',
  }),
} as const;
