export type Language = 'en' | 'hi' | 'bn' | 'te' | 'mr' | 'ta' | 'gu' | 'ur' | 'kn' | 'or' | 'pa' | 'ml' | 'bho' | 'bh';

export const languageNames: Record<Language, string> = {
  en: 'English',
  hi: 'हिन्दी (Hindi)',
  bn: 'বাংলা (Bengali)',
  te: 'తెలుగు (Telugu)',
  mr: 'मराठी (Marathi)',
  ta: 'தமிழ் (Tamil)',
  gu: 'ગુજરાતી (Gujarati)',
  ur: 'اردو (Urdu)',
  kn: 'ಕನ್ನಡ (Kannada)',
  or: 'ଓଡ଼ିଆ (Odia)',
  pa: 'ਪੰਜਾਬੀ (Punjabi)',
  ml: 'മലയാളം (Malayalam)',
  bho: 'भोजपुरी (Bhojpuri)',
  bh: 'बिहारी (Bihari)'
};

export type Translation = {
  nav: { lawyers: string; knowledge: string; templates: string; rights: string; login: string; signup: string };
  hero: { title: string; subtitle: string; searchLaw: string; searchCity: string; searchBtn: string; forCitizens: string; forLawyers: string };
  features: { title: string; subtitle: string; f1Title: string; f1Desc: string; f2Title: string; f2Desc: string; f3Title: string; f3Desc: string; f4Title: string; f4Desc: string };
  howItWorks: { title: string; subtitle: string; s1Title: string; s1Desc: string; s2Title: string; s2Desc: string; s3Title: string; s3Desc: string };
  categories: { title: string; subtitle: string; viewAll: string; c1: string; c2: string; c3: string; c4: string; c5: string; c6: string; lawyers: string };
  testimonials: { title: string; subtitle: string; startBtn: string; quote: string; role: string };
  footer: { desc: string; forCitizens: string; findLawyer: string; knowledge: string; templates: string; rights: string; forLawyers: string; joinDir: string; dashboard: string; pricing: string; company: string; about: string; contact: string; privacy: string; terms: string; rightsRes: string; disclaimer: string };
  common: { search: string; loading: string; noResults: string; viewDetails: string; save: string; cancel: string; back: string; continue: string; error: string; success: string; filterBy: string; sort: string; all: string };
  auth: { loginTitle: string; loginSub: string; signupTitle: string; signupSub: string; emailLabel: string; passLabel: string; nameLabel: string; forgotPass: string; loginBtn: string; signupBtn: string; noAccount: string; hasAccount: string; continueGoogle: string; roleCitizen: string; roleLawyer: string; emailPh: string; passPh: string; namePh: string; passRequirements: string };
  knowledge: { title: string; subtitle: string; searchPlaceholder: string; categories: string; popular: string; readMore: string; backToList: string; related: string; wasHelpful: string; yes: string; no: string };
  templates: { title: string; subtitle: string; searchPlaceholder: string; downloadBtn: string; preview: string; category: string; format: string; size: string; requirements: string; instructions: string };
  dashboard: { title: string; welcome: string; appointments: string; profile: string; settings: string; messages: string; viewAll: string; upcoming: string; past: string; noAppointments: string; signOut: string; quickActions: string; findLawyer: string; findLawyerDesc: string; legalKnowledge: string; legalKnowledgeDesc: string; legalTemplates: string; legalTemplatesDesc: string; myAppointments: string; myAppointmentsDesc: string; comingSoon: string; comingSoonDesc: string; lawyerPortal: string; statsRating: string; statsReviews: string; statsVerified: string; statsExperience: string; profileDetails: string; editProfile: string; city: string; fee: string; specializations: string; languages: string; completeProfile: string; completeProfileDesc: string; lawyerComingSoon: string; lawyerComingSoonDesc: string };
  lawyersPage: { title: string; subtitle: string; searchPlaceholder: string; filters: string; experience: string; fees: string; languages: string; availability: string; verifiedOnly: string; clearFilters: string; noLawyers: string; bookConsultation: string; viewProfile: string; reviews: string; rating: string; location: string };
};

const en: Translation = {
  nav: { lawyers: 'Lawyers', knowledge: 'Knowledge Base', templates: 'Templates', rights: 'Know Your Rights', login: 'Login', signup: 'Sign Up' },
  hero: { title: 'Get Legal Help in Minutes', subtitle: 'मिनटों में कानूनी सहायता प्राप्त करें', searchLaw: 'Find lawyers by law (e.g., Family, Criminal)', searchCity: 'City or Pincode', searchBtn: 'Search', forCitizens: 'For Citizens', forLawyers: 'For Lawyers' },
  features: { title: 'Everything You Need for Legal Peace of Mind', subtitle: 'Access verified lawyers, free legal information, and essential document templates all in one place.', f1Title: 'Search Lawyers', f1Desc: 'Find verified, top-rated lawyers near you based on expertise and reviews.', f2Title: 'Book Consultations', f2Desc: 'Schedule appointments and chat securely with legal professionals.', f3Title: 'Free Legal Info', f3Desc: 'Understand your rights with our bilingual knowledge base.', f4Title: 'Templates', f4Desc: 'Download standard legal formats like FIRs, Affidavits, and Notices.' },
  howItWorks: { title: 'How LexIndia Works', subtitle: 'Get the legal help you need in three simple steps.', s1Title: 'Search & Filter', s1Desc: 'Enter your legal issue and location to find relevant lawyers.', s2Title: 'Review Profiles', s2Desc: 'Check experience, fees, and client reviews to choose the right fit.', s3Title: 'Book & Chat', s3Desc: 'Schedule a consultation and discuss your case securely.' },
  categories: { title: 'Find Lawyers by Specialization', subtitle: 'Browse top-rated advocates across various legal domains.', viewAll: 'View All', c1: 'Criminal Law', c2: 'Family Law', c3: 'Property Law', c4: 'Corporate Law', c5: 'Civil Law', c6: 'Cyber Law', lawyers: 'Lawyers' },
  testimonials: { title: 'Ready to resolve your legal issues?', subtitle: 'Join thousands of citizens who have successfully found the right legal representation through LexIndia.', startBtn: 'Start Now', quote: "I was struggling to find a reliable property lawyer in Delhi. LexIndia made it incredibly easy to compare profiles, read reviews, and book a consultation. Highly recommended!", role: 'Property Dispute Client' },
  footer: { desc: 'Making legal help accessible, transparent, and efficient for every Indian citizen.', forCitizens: 'For Citizens', findLawyer: 'Find a Lawyer', knowledge: 'Knowledge Base', templates: 'Legal Templates', rights: 'Know Your Rights', forLawyers: 'For Lawyers', joinDir: 'Join Directory', dashboard: 'Lawyer Dashboard', pricing: 'Pricing', company: 'Company', about: 'About Us', contact: 'Contact', privacy: 'Privacy Policy', terms: 'Terms of Service', rightsRes: 'All rights reserved.', disclaimer: 'Disclaimer: This platform is for informational purposes only and is not a substitute for professional legal advice.' },
  common: { search: 'Search', loading: 'Loading...', noResults: 'No results found', viewDetails: 'View Details', save: 'Save', cancel: 'Cancel', back: 'Back', continue: 'Continue', error: 'An error occurred', success: 'Success!', filterBy: 'Filter By', sort: 'Sort', all: 'All' },
  auth: { loginTitle: 'Sign in to LexIndia', loginSub: 'Access your dashboard to book consultations and manage documents.', signupTitle: 'Create an Account', signupSub: 'Join thousands of citizens getting accessible legal help.', emailLabel: 'Email Address', passLabel: 'Password', nameLabel: 'Full Name', forgotPass: 'Forgot password?', loginBtn: 'Sign In', signupBtn: 'Create Account', noAccount: "Don't have an account?", hasAccount: 'Already have an account?', continueGoogle: 'Continue with Google', roleCitizen: 'I am a Citizen', roleLawyer: 'I am a Lawyer', emailPh: 'you@example.com', passPh: 'Min. 8 characters', namePh: 'John Doe', passRequirements: 'Must be at least 8 characters' },
  knowledge: { title: 'Legal Knowledge Base', subtitle: 'Understand your rights, legal procedures, and Indian laws in simple terms.', searchPlaceholder: 'Search articles, laws, rights...', categories: 'Categories', popular: 'Popular Topics', readMore: 'Read Article', backToList: 'Back to Knowledge Base', related: 'Related Articles', wasHelpful: 'Was this helpful?', yes: 'Yes', no: 'No' },
  templates: { title: 'Legal Document Templates', subtitle: 'Download standardized legal formats, notices, and agreements ready to use.', searchPlaceholder: 'Search templates (e.g., Rental Agreement, NDA)...', downloadBtn: 'Download Template', preview: 'Preview', category: 'Category', format: 'Format', size: 'Size', requirements: 'Requirements', instructions: 'Instructions' },
  dashboard: { title: 'Dashboard', welcome: 'Welcome back', appointments: 'Appointments', profile: 'Profile', settings: 'Settings', messages: 'Messages', viewAll: 'View All', upcoming: 'Upcoming', past: 'Past', noAppointments: 'No appointments scheduled', signOut: 'Sign Out', quickActions: 'Quick Actions', findLawyer: 'Find a Lawyer', findLawyerDesc: 'Browse 4+ verified lawyers', legalKnowledge: 'Legal Knowledge', legalKnowledgeDesc: 'Know your legal rights', legalTemplates: 'Legal Templates', legalTemplatesDesc: 'Download free documents', myAppointments: 'My Appointments', myAppointmentsDesc: 'View upcoming consultations', comingSoon: 'More features coming soon', comingSoonDesc: 'Appointment booking, case tracking, and document storage will be available in the next update.', lawyerPortal: 'Lawyer Portal', statsRating: 'Rating', statsReviews: 'Reviews', statsVerified: 'Verified', statsExperience: 'Experience', profileDetails: 'Profile Details', editProfile: 'Edit Profile', city: 'City:', fee: 'Fee:', specializations: 'Specializations:', languages: 'Languages:', completeProfile: 'Complete Your Profile', completeProfileDesc: 'Set up your lawyer profile so clients can find and book you.', lawyerComingSoon: 'Appointment Management Coming Soon', lawyerComingSoonDesc: 'View and manage client appointment requests in the next update.' },
  lawyersPage: { title: 'Find Verified Lawyers', subtitle: 'Browse top-rated advocates across various legal domains in India.', searchPlaceholder: 'Search by name, specialization, or location...', filters: 'Filters', experience: 'Experience', fees: 'Consultation Fee', languages: 'Languages Spoken', availability: 'Availability', verifiedOnly: 'Verified Professionals Only', clearFilters: 'Clear Filters', noLawyers: 'No lawyers found matching your criteria.', bookConsultation: 'Book Consultation', viewProfile: 'View Profile', reviews: 'reviews', rating: 'Rating', location: 'Location' }
};

const hi: Translation = {
  nav: { lawyers: 'वकील', knowledge: 'ज्ञानकोष', templates: 'टेम्पलेट्स', rights: 'अपने अधिकार जानें', login: 'लॉग इन', signup: 'साइन अप' },
  hero: { title: 'मिनटों में कानूनी सहायता प्राप्त करें', subtitle: 'Get Legal Help in Minutes', searchLaw: 'कानून के अनुसार वकील खोजें (उदा., पारिवारिक, आपराधिक)', searchCity: 'शहर या पिनकोड', searchBtn: 'खोजें', forCitizens: 'नागरिकों के लिए', forLawyers: 'वकीलों के लिए' },
  features: { title: 'कानूनी शांति के लिए आपको जो कुछ भी चाहिए', subtitle: 'सत्यापित वकीलों, मुफ्त कानूनी जानकारी और आवश्यक दस्तावेज़ टेम्पलेट्स तक एक ही स्थान पर पहुंचें।', f1Title: 'वकील खोजें', f1Desc: 'विशेषज्ञता और समीक्षाओं के आधार पर अपने आस-पास सत्यापित, शीर्ष-रेटेड वकील खोजें।', f2Title: 'परामर्श बुक करें', f2Desc: 'नियुक्तियां निर्धारित करें और कानूनी पेशेवरों के साथ सुरक्षित रूप से चैट करें।', f3Title: 'मुफ्त कानूनी जानकारी', f3Desc: 'हमारे द्विभाषी ज्ञानकोष के साथ अपने अधिकारों को समझें।', f4Title: 'टेम्पलेट्स', f4Desc: 'प्राथमिकी, हलफनामा और नोटिस जैसे मानक कानूनी प्रारूप डाउनलोड करें।' },
  howItWorks: { title: 'LexIndia कैसे काम करता है', subtitle: 'तीन सरल चरणों में आवश्यक कानूनी सहायता प्राप्त करें।', s1Title: 'खोजें और फ़िल्टर करें', s1Desc: 'प्रासंगिक वकीलों को खोजने के लिए अपना कानूनी मुद्दा और स्थान दर्ज करें।', s2Title: 'प्रोफ़ाइल की समीक्षा करें', s2Desc: 'सही विकल्प चुनने के लिए अनुभव, फीस और ग्राहक समीक्षाओं की जांच करें।', s3Title: 'बुक करें और चैट करें', s3Desc: 'परामर्श निर्धारित करें और अपने मामले पर सुरक्षित रूप से चर्चा करें।' },
  categories: { title: 'विशेषज्ञता के अनुसार वकील खोजें', subtitle: 'विभिन्न कानूनी डोमेन में शीर्ष-रेटेड अधिवक्ताओं को ब्राउज़ करें।', viewAll: 'सभी देखें', c1: 'आपराधिक कानून', c2: 'पारिवारिक कानून', c3: 'संपत्ति कानून', c4: 'कॉर्पोरेट कानून', c5: 'नागरिक कानून', c6: 'साइबर कानून', lawyers: 'वकील' },
  testimonials: { title: 'क्या आप अपने कानूनी मुद्दों को सुलझाने के लिए तैयार हैं?', subtitle: 'उन हजारों नागरिकों से जुड़ें जिन्होंने LexIndia के माध्यम से सफलतापूर्वक सही कानूनी प्रतिनिधित्व पाया है।', startBtn: 'अभी शुरू करें', quote: "मैं दिल्ली में एक विश्वसनीय संपत्ति वकील खोजने के लिए संघर्ष कर रहा था। LexIndia ने प्रोफाइल की तुलना करना, समीक्षा पढ़ना और परामर्श बुक करना अविश्वसनीय रूप से आसान बना दिया। अत्यधिक अनुशंसित!", role: 'संपत्ति विवाद ग्राहक' },
  footer: { desc: 'प्रत्येक भारतीय नागरिक के लिए कानूनी सहायता को सुलभ, पारदर्शी और कुशल बनाना।', forCitizens: 'नागरिकों के लिए', findLawyer: 'वकील खोजें', knowledge: 'ज्ञानकोष', templates: 'कानूनी टेम्पलेट्स', rights: 'अपने अधिकार जानें', forLawyers: 'वकीलों के लिए', joinDir: 'निर्देशिका से जुड़ें', dashboard: 'वकील डैशबोर्ड', pricing: 'मूल्य निर्धारण', company: 'कंपनी', about: 'हमारे बारे में', contact: 'संपर्क करें', privacy: 'गोपनीयता नीति', terms: 'सेवा की शर्तें', rightsRes: 'सर्वाधिकार सुरक्षित।', disclaimer: 'अस्वीकरण: यह मंच केवल सूचनात्मक उद्देश्यों के लिए है और पेशेवर कानूनी सलाह का विकल्प नहीं है।' },
  common: { search: 'खोजें', loading: 'लोड हो रहा है...', noResults: 'कोई परिणाम नहीं मिला', viewDetails: 'विवरण देखें', save: 'सहेजें', cancel: 'रद्द करें', back: 'वापस', continue: 'जारी रखें', error: 'एक त्रुटि हुई', success: 'सफलता!', filterBy: 'फ़िल्टर करें', sort: 'क्रमबद्ध करें', all: 'सभी' },
  auth: { loginTitle: 'LexIndia में साइन इन करें', loginSub: 'परामर्श बुक करने और दस्तावेज़ प्रबंधित करने के लिए अपने डैशबोर्ड तक पहुंचें।', signupTitle: 'एक खाता बनाएं', signupSub: 'उन हजारों नागरिकों से जुड़ें जो सुलभ कानूनी सहायता प्राप्त कर रहे हैं।', emailLabel: 'ईमेल पता', passLabel: 'पासवर्ड', nameLabel: 'पूरा नाम', forgotPass: 'पासवर्ड भूल गए?', loginBtn: 'साइन इन करें', signupBtn: 'खाता बनाएं', noAccount: "क्या आपके पास खाता नहीं है?", hasAccount: 'क्या आपके पास पहले से खाता है?', continueGoogle: 'Google के साथ जारी रखें', roleCitizen: 'मैं एक नागरिक हूँ', roleLawyer: 'मैं एक वकील हूँ', emailPh: 'आप@example.com', passPh: 'न्यूनतम 8 वर्ण', namePh: 'आपका नाम', passRequirements: 'कम से कम 8 अक्षर का होना चाहिए' },
  knowledge: { title: 'कानूनी ज्ञानकोष', subtitle: 'सरल शब्दों में अपने अधिकारों, कानूनी प्रक्रियाओं और भारतीय कानूनों को समझें।', searchPlaceholder: 'लेख, कानून, अधिकार खोजें...', categories: 'श्रेणियाँ', popular: 'लोकप्रिय विषय', readMore: 'लेख पढ़ें', backToList: 'ज्ञानकोष पर वापस जाएं', related: 'संबंधित लेख', wasHelpful: 'क्या यह उपयोगी था?', yes: 'हाँ', no: 'नहीं' },
  templates: { title: 'कानूनी दस्तावेज़ टेम्पलेट्स', subtitle: 'उपयोग के लिए तैयार मानकीकृत कानूनी प्रारूप, नोटिस और समझौते डाउनलोड करें।', searchPlaceholder: 'टेम्पलेट्स खोजें (जैसे, रेंटल एग्रीमेंट, एनडीए)...', downloadBtn: 'टेम्पलेट डाउनलोड करें', preview: 'पूर्वावलोकन', category: 'श्रेणी', format: 'प्रारूप', size: 'आकार', requirements: 'आवश्यकताएं', instructions: 'निर्देश' },
  dashboard: { title: 'डैशबोर्ड', welcome: 'वापसी पर स्वागत है', appointments: 'नियुक्तियां', profile: 'प्रोफ़ाइल', settings: 'सेटिंग्स', messages: 'संदेश', viewAll: 'सभी देखें', upcoming: 'आगामी', past: 'पिछला', noAppointments: 'कोई नियुक्ति निर्धारित नहीं है', signOut: 'साइन आउट', quickActions: 'त्वरित कार्रवाई', findLawyer: 'वकील खोजें', findLawyerDesc: '४+ सत्यापित वकीलों को ब्राउज़ करें', legalKnowledge: 'कानूनी ज्ञान', legalKnowledgeDesc: 'अपने कानूनी अधिकार जानें', legalTemplates: 'कानूनी टेम्पलेट्स', legalTemplatesDesc: 'मुफ्त दस्तावेज़ डाउनलोड करें', myAppointments: 'मेरी नियुक्तियां', myAppointmentsDesc: 'आगामी परामर्श देखें', comingSoon: 'अधिक सुविधाएँ जल्द आ रही हैं', comingSoonDesc: 'नियुक्ति बुकिंग, केस ट्रैकिंग और दस्तावेज़ भंडारण अगले अपडेट में उपलब्ध होंगे।', lawyerPortal: 'वकील पोर्टल', statsRating: 'रेटिंग', statsReviews: 'समीक्षाएँ', statsVerified: 'सत्यापित', statsExperience: 'अनुभव', profileDetails: 'प्रोफ़ाइल विवरण', editProfile: 'प्रोफ़ाइल संपादित करें', city: 'शहर:', fee: 'शुल्क:', specializations: 'विशेषज्ञता:', languages: 'भाषाएँ:', completeProfile: 'अपनी प्रोफ़ाइल पूरी करें', completeProfileDesc: 'अपनी वकील प्रोफ़ाइल सेट करें ताकि ग्राहक आपको ढूंढ सकें और बुक कर सकें।', lawyerComingSoon: 'नियुक्ति प्रबंधन जल्द आ रहा है', lawyerComingSoonDesc: 'अगले अपडेट में क्लाइंट नियुक्ति अनुरोधों को देखें और प्रबंधित करें।' },
  lawyersPage: { title: 'सत्यापित वकील खोजें', subtitle: 'भारत में विभिन्न कानूनी डोमेन में शीर्ष-रेटेड अधिवक्ताओं को ब्राउज़ करें।', searchPlaceholder: 'नाम, विशेषज्ञता, या स्थान से खोजें...', filters: 'फ़िल्टर', experience: 'अनुभव', fees: 'परामर्श शुल्क', languages: 'बोली जाने वाली भाषाएँ', availability: 'उपलब्धता', verifiedOnly: 'केवल सत्यापित पेशेवर', clearFilters: 'फ़िल्टर साफ़ करें', noLawyers: 'आपके मानदंडों से मेल खाने वाला कोई वकील नहीं मिला।', bookConsultation: 'परामर्श बुक करें', viewProfile: 'प्रोफ़ाइल देखें', reviews: 'समीक्षाएँ', rating: 'रेटिंग', location: 'स्थान' }
};

// Partial translations for other languages (falling back to English for missing parts)
const bn: Translation = {
  nav: { lawyers: 'আইনজীবী', knowledge: 'জ্ঞানের ভাণ্ডার', templates: 'টেমপ্লেট', rights: 'আপনার অধিকার জানুন', login: 'লগইন', signup: 'সাইন আপ' },
  hero: { title: 'মিনিটের মধ্যে আইনি সহায়তা পান', subtitle: 'Get Legal Help in Minutes', searchLaw: 'আইন অনুযায়ী আইনজীবী খুঁজুন', searchCity: 'শহর বা পিনকোড', searchBtn: 'অনুসন্ধান', forCitizens: 'নাগরিকদের জন্য', forLawyers: 'আইনজীবীদের জন্য' },
  features: { title: 'আইনি মানসিক শান্তির জন্য আপনার যা কিছু প্রয়োজন', subtitle: 'যাচাইকৃত আইনজীবী, বিনামূল্যে আইনি তথ্য এবং প্রয়োজনীয় নথি টেমপ্লেটগুলি এক জায়গায় অ্যাক্সেস করুন।', f1Title: 'আইনজীবী খুঁজুন', f1Desc: 'দক্ষতা এবং পর্যালোচনার ভিত্তিতে আপনার কাছাকাছি যাচাইকৃত শীর্ষস্থানীয় আইনজীবী খুঁজুন।', f2Title: 'পরামর্শ বুক করুন', f2Desc: 'অ্যাপয়েন্টমেন্ট নির্ধারণ করুন এবং পেশাদারদের সাথে নিরাপদে চ্যাট করুন।', f3Title: 'বিনামূল্যে আইনি তথ্য', f3Desc: 'আমাদের দ্বিভাষিক জ্ঞানের ভাণ্ডার দিয়ে আপনার অধিকারগুলি বুঝুন।', f4Title: 'টেমপ্লেট', f4Desc: 'এফআইআর, এফিডেভিট এবং নোটিশের মতো মানসম্মত আইনি ফর্ম্যাট ডাউনলোড করুন।' },
  howItWorks: { title: 'LexIndia কীভাবে কাজ করে', subtitle: 'তিনটি সহজ ধাপে আপনার প্রয়োজনীয় আইনি সহায়তা পান।', s1Title: 'অনুসন্ধান ও ফিল্টার করুন', s1Desc: 'প্রাসঙ্গিক আইনজীবী খুঁজতে আপনার আইনি সমস্যা এবং অবস্থান লিখুন।', s2Title: 'প্রোফাইল পর্যালোচনা করুন', s2Desc: 'সঠিক বিকল্পটি চয়ন করতে অভিজ্ঞতা, ফি এবং ক্লায়েন্ট পর্যালোচনা দেখুন।', s3Title: 'বুক করুন ও চ্যাট করুন', s3Desc: 'পরামর্শ নির্ধারণ করুন এবং নিরাপদে আপনার মামলা নিয়ে আলোচনা করুন।' },
  categories: { title: 'বিশেষজ্ঞতা অনুযায়ী আইনজীবী খুঁজুন', subtitle: 'বিভিন্ন আইনি ডোমেন জুড়ে শীর্ষ-রেটযুক্ত অ্যাডভোকেট ব্রাউজ করুন।', viewAll: 'সব দেখুন', c1: 'ফৌজদারি আইন', c2: 'পারিবারিক আইন', c3: 'সম্পত্তি আইন', c4: 'কর্পোরেট আইন', c5: 'দেওয়ানি আইন', c6: 'সাইবার আইন', lawyers: 'আইনজীবী' },
  testimonials: { title: 'আপনার আইনি সমস্যা সমাধানে প্রস্তুত?', subtitle: 'সেই হাজার হাজার নাগরিকদের সাথে যোগ দিন যারা LexIndia এর মাধ্যমে সফলভাবে সঠিক আইনি প্রতিনিধিত্ব পেয়েছেন।', startBtn: 'এখন শুরু করুন', quote: "আমি দিল্লিতে একটি নির্ভরযোগ্য সম্পত্তি আইনজীবী খুঁজে পেতে সংগ্রাম করছিলাম। LexIndia প্রোফাইলের তুলনা করাকে সহজ করেছে। অত্যন্ত প্রস্তাবিত!", role: 'সম্পত্তি বিবাদ ক্লায়েন্ট' },
  footer: { desc: 'প্রতিটি ভারতীয় নাগরিকের জন্য আইনি সহায়তা সহজলভ্য এবং দক্ষ করে তোলা।', forCitizens: 'নাগরিকদের জন্য', findLawyer: 'আইনজীবী খুঁজুন', knowledge: 'জ্ঞানের ভাণ্ডার', templates: 'আইনি টেমপ্লেট', rights: 'আপনার অধিকার জানুন', forLawyers: 'আইনজীবীদের জন্য', joinDir: 'ডিরেক্টরিতে যোগ দিন', dashboard: 'আইনজীবী ড্যাশবোর্ড', pricing: 'মূল্য নির্ধারণ', company: 'কোম্পানি', about: 'আমাদের সম্পর্কে', contact: 'যোগাযোগ', privacy: 'গোপনীয়তা নীতি', terms: 'পরিষেবার শর্তাবলী', rightsRes: 'সর্বস্বত্ব সংরক্ষিত।', disclaimer: 'দাবিত্যাগ: এই প্ল্যাটফর্মটি পেশাদার আইনি পরামর্শের বিকল্প নয়।' },
  common: { search: 'অনুসন্ধান', loading: 'লোড হচ্ছে...', noResults: 'কোনো ফলাফল পাওয়া যায়নি', viewDetails: 'বিবরণ দেখুন', save: 'সংরক্ষণ', cancel: 'বাতিল', back: 'পিছনে', continue: 'চালিয়ে যান', error: 'একটি ত্রুটি ঘটেছে', success: 'সফলতা!', filterBy: 'ফিল্টার করুন', sort: 'ক্রমানুসার', all: 'সব' },
  auth: { loginTitle: 'LexIndia এ সাইন ইন করুন', loginSub: 'পরামর্শ বুক করতে আপনার ড্যাশবোর্ডে অ্যাক্সেস করুন।', signupTitle: 'অ্যাকাউন্ট তৈরি করুন', signupSub: 'সহজ আইনি সহায়তা পাওয়া নাগরিকদের সাথে যোগ দিন।', emailLabel: 'ইমেইল ঠিকানা', passLabel: 'পাসওয়ার্ড', nameLabel: 'নাম', forgotPass: 'পাসওয়ার্ড ভুলে গেছেন?', loginBtn: 'সাইন ইন', signupBtn: 'অ্যাকাউন্ট তৈরি করুন', noAccount: "অ্যাকাউন্ট নেই?", hasAccount: 'অ্যাকাউন্ট আছে?', continueGoogle: 'Google এর সাথে চালিয়ে যান', roleCitizen: 'আমি নাগরিক', roleLawyer: 'আমি আইনজীবী', emailPh: 'আপনি@example.com', passPh: 'ন্যূনতম ৮ অক্ষর', namePh: 'আপনার নাম', passRequirements: 'কমপক্ষে ৮ অক্ষরের হতে হবে' },
  knowledge: { title: 'আইনি জ্ঞান', subtitle: 'আপনার অধিকার এবং আইন সহজ শর্তে বুঝুন।', searchPlaceholder: 'প্রবন্ধ, আইন খুঁজুন...', categories: 'বিভাগ', popular: 'জনপ্রিয় বিষয়', readMore: 'পড়ুন', backToList: 'ফিরে যান', related: 'সম্পর্কিত প্রবন্ধ', wasHelpful: 'এটি কি সহায়ক ছিল?', yes: 'হ্যাঁ', no: 'না' },
  templates: { title: 'টেমপ্লেট', subtitle: 'মানসম্মত আইনি বিন্যাস ডাউনলোড করুন।', searchPlaceholder: 'টেমপ্লেট খুঁজুন...', downloadBtn: 'ডাউনলোড করুন', preview: 'প্রাকদর্শন', category: 'বিভাগ', format: 'বিন্যাস', size: 'আকার', requirements: 'প্রয়োজনীয়তা', instructions: 'নির্দেশাবলী' },
  dashboard: { title: 'ড্যাশবোর্ড', welcome: 'স্বাগতম', appointments: 'অ্যাপয়েন্টমেন্ট', profile: 'প্রোফাইল', settings: 'সেটিংস', messages: 'বার্তা', viewAll: 'সব দেখুন', upcoming: 'আসন্ন', past: 'অতীত', noAppointments: 'কোনো অ্যাপয়েন্টমেন্ট নেই', signOut: 'সাইন আউট', quickActions: 'দ্রুত পদক্ষেপ', findLawyer: 'আইনজীবী খুঁজুন', findLawyerDesc: 'যাচাইকৃত আইনজীবী ব্রাউজ করুন', legalKnowledge: 'আইনি জ্ঞান', legalKnowledgeDesc: 'আপনার অধিকার জানুন', legalTemplates: 'আইনি টেমপ্লেট', legalTemplatesDesc: 'নথি ডাউনলোড করুন', myAppointments: 'আমার অ্যাপয়েন্টমেন্ট', myAppointmentsDesc: 'আসন্ন পরামর্শ দেখুন', comingSoon: 'শীঘ্রই আসছে', comingSoonDesc: 'নতুন সুবিধা যোগ করা হবে।', lawyerPortal: 'আইনজীবী পোর্টাল', statsRating: 'রেটিং', statsReviews: 'পর্যালোচনা', statsVerified: 'যাচাইকৃত', statsExperience: 'অভিজ্ঞতা', profileDetails: 'প্রোফাইল বিবরণ', editProfile: 'প্রোফাইল সম্পাদনা', city: 'শহর:', fee: 'ফি:', specializations: 'বিশেষজ্ঞতা:', languages: 'ভাষা:', completeProfile: 'আপনার প্রোফাইল সম্পন্ন করুন', completeProfileDesc: 'যাতে ক্লায়েন্টরা আপনাকে খুঁজে পেতে পারে।', lawyerComingSoon: 'শীঘ্রই আসছে', lawyerComingSoonDesc: 'ক্লায়েন্ট অনুরোধ পরিচালনা করুন।' },
  lawyersPage: { title: 'আইনজীবী খুঁজুন', subtitle: 'শীর্ষ-রেটযুক্ত অ্যাডভোকেট ব্রাউজ করুন।', searchPlaceholder: 'অনুসন্ধান করুন...', filters: 'ফিল্টার', experience: 'অভিজ্ঞতা', fees: 'পরামর্শ ফি', languages: 'ভাষা', availability: 'উপলব্ধতা', verifiedOnly: 'যাচাইকৃত পেশাদার', clearFilters: 'সাফ করুন', noLawyers: 'কোনো আইনজীবী পাওয়া যায়নি।', bookConsultation: 'বুক করুন', viewProfile: 'প্রোফাইল দেখুন', reviews: 'পর্যালোচনা', rating: 'রেটিং', location: 'অবস্থান' }
};

const te: Translation = {
  nav: { lawyers: 'న్యాయవాదులు', knowledge: 'నాలెడ్జ్ బేస్', templates: 'టెంప్లేట్లు', rights: 'మీ హక్కులను తెలుసుకోండి', login: 'లాగిన్', signup: 'సైన్ అప్' },
  hero: { title: 'నిమిషాల్లో చట్టపరమైన సహాయం పొందండి', subtitle: 'Get Legal Help in Minutes', searchLaw: 'చట్టం ద్వారా న్యాయవాదులను కనుగొనండి', searchCity: 'నగరం లేదా పిన్‌కోడ్', searchBtn: 'శోధించండి', forCitizens: 'పౌరుల కోసం', forLawyers: 'న్యాయవాదుల కోసం' },
  features: { title: 'మీకు కావలసినవన్నీ', subtitle: 'ధృవీకరించబడిన న్యాయవాదులు, ఉచిత న్యాయ సమాచారాన్ని యాక్సెస్ చేయండి.', f1Title: 'న్యాయవాదులను శోధించండి', f1Desc: 'మీకు సమీపంలోని న్యాయవాదులను కనుగొనండి.', f2Title: 'సమాలోచనలను బుక్ చేయండి', f2Desc: 'నిపుణులతో చాట్ చేయండి.', f3Title: 'ఉచిత సమాచారం', f3Desc: 'మీ హక్కులను అర్థం చేసుకోండి.', f4Title: 'టెంప్లేట్లు', f4Desc: 'చట్టపరమైన ఫార్మాట్‌లను డౌన్‌లోడ్ చేయండి.' },
  howItWorks: { title: 'లెక్స్‌ఇండియా ఎలా పనిచేస్తుంది', subtitle: 'మూడు సాధారణ దశల్లో సహాయం పొందండి.', s1Title: 'శోధించండి', s1Desc: 'న్యాయవాదులను కనుగొనండి.', s2Title: 'ప్రొఫైల్‌లను సమీక్షించండి', s2Desc: 'అనుభవం మరియు ఫీజులను తనిఖీ చేయండి.', s3Title: 'బుక్ చేయండి & చాట్ చేయండి', s3Desc: 'మీ కేసును చర్చించండి.' },
  categories: { title: 'స్పెషలైజేషన్ ద్వారా న్యాయవాదులను కనుగొనండి', subtitle: 'వివిధ చట్టపరమైన డొమైన్‌లలో అగ్రశ్రేణి న్యాయవాదులను బ్రౌజ్ చేయండి.', viewAll: 'అన్నీ చూడండి', c1: 'క్రిమినల్ లా', c2: 'ఫ్యామిలీ లా', c3: 'ప్రాపర్టీ లా', c4: 'కార్పొరేట్ లా', c5: 'సివిల్ లా', c6: 'సైబర్ లా', lawyers: 'న్యాయవాదులు' },
  testimonials: { title: 'సిద్ధంగా ఉన్నారా?', subtitle: 'వేలాది పౌరులలో చేరండి.', startBtn: 'ప్రారంభించండి', quote: "లెక్స్‌ఇండియా చాలా సులభం చేసింది!", role: 'క్లయింట్' },
  footer: { desc: 'చట్టపరమైన సహాయం అందుబాటులో ఉంచడం.', forCitizens: 'పౌరుల కోసం', findLawyer: 'న్యాయవాదిని కనుగొనండి', knowledge: 'నాలెడ్జ్ బేస్', templates: 'టెంప్లేట్లు', rights: 'మీ హక్కులను తెలుసుకోండి', forLawyers: 'న్యాయవాదుల కోసం', joinDir: 'చేరండి', dashboard: 'డాష్‌బోర్డ్', pricing: 'ధరలు', company: 'కంపెనీ', about: 'మా గురించి', contact: 'సంప్రదించండి', privacy: 'గోప్యత', terms: 'నిబంధనలు', rightsRes: 'సర్వ హక్కులు ప్రత్యేకించబడినవి.', disclaimer: 'న్యాయ సలహాకు ప్రత్యామ్నాయం కాదు.' },
  common: { search: 'శోధించండి', loading: 'లోడ్ అవుతోంది...', noResults: 'ఫలితాలు లేవు', viewDetails: 'వివరాలను చూడండి', save: 'సేవ్ చేయండి', cancel: 'రద్దు చేయండి', back: 'వెనుకకు', continue: 'కొనసాగించండి', error: 'ఒక లోపం ఏర్పడింది', success: 'విజయం!', filterBy: 'ఫిల్టర్ చేయండి', sort: 'క్రమబద్ధీకరించు', all: 'అన్నీ' },
  auth: { loginTitle: 'సైన్ ఇన్ చేయండి', loginSub: 'మీ డాష్‌బోర్డ్‌ని యాక్సెస్ చేయండి.', signupTitle: 'ఖాతాను సృష్టించండి', signupSub: 'మమ్మల్ని చేరండి.', emailLabel: 'ఇమెయిల్', passLabel: 'పాస్‌వర్డ్', nameLabel: 'పేరు', forgotPass: 'మర్చిపోయారా?', loginBtn: 'సైన్ ఇన్ చేయండి', signupBtn: 'సృష్టించండి', noAccount: "ఖాతా లేదా?", hasAccount: 'ఖాతా ఉందా?', continueGoogle: 'Googleతో కొనసాగించండి', roleCitizen: 'నేను పౌరుడిని', roleLawyer: 'నేను న్యాయవాదిని', emailPh: 'మీరు@example.com', passPh: 'కనీసం 8 అక్షరాలు', namePh: 'మీ పేరు', passRequirements: '8 అక్షరాలు ఉండాలి' },
  knowledge: { title: 'న్యాయ సమాచారం', subtitle: 'చట్టాలను అర్థం చేసుకోండి.', searchPlaceholder: 'శోధించండి...', categories: 'కేటగిరీలు', popular: 'అంశాలు', readMore: 'చదవండి', backToList: 'వెనుకకు', related: 'సంబంధిత వ్యాసాలు', wasHelpful: 'ఉపయోగకరంగా ఉందా?', yes: 'అవును', no: 'కాదు' },
  templates: { title: 'టెంప్లేట్లు', subtitle: 'ఫార్మాట్‌లను డౌన్‌లోడ్ చేయండి.', searchPlaceholder: 'శోధించండి...', downloadBtn: 'డౌన్‌లోడ్ చేయండి', preview: 'ప్రివ్యూ', category: 'వర్గం', format: 'ఫార్మాట్', size: 'పరిమాణం', requirements: 'అవసరాలు', instructions: 'సూచనలు' },
  dashboard: { title: 'డాష్‌బోర్డ్', welcome: 'స్వాగతం', appointments: 'అపాయింట్‌మెంట్‌లు', profile: 'ప్రొఫైల్', settings: 'సెట్టింగ్‌లు', messages: 'సందేశాలు', viewAll: 'అన్నీ చూడండి', upcoming: 'రాబోయే', past: 'గత', noAppointments: 'అపాయింట్‌మెంట్‌లు లేవు', signOut: 'సైన్ అవుట్', quickActions: 'చర్యలు', findLawyer: 'న్యాయవాదిని కనుగొనండి', findLawyerDesc: 'న్యాయవాదులను బ్రౌజ్ చేయండి', legalKnowledge: 'చట్టపరమైన జ్ఞానం', legalKnowledgeDesc: 'హక్కులను తెలుసుకోండి', legalTemplates: 'టెంప్లేట్లు', legalTemplatesDesc: 'పత్రాలను డౌన్‌లోడ్ చేయండి', myAppointments: 'నా అపాయింట్‌మెంట్‌లు', myAppointmentsDesc: 'సమాలోచనలను చూడండి', comingSoon: 'త్వరలో రానున్నాయి', comingSoonDesc: 'కొత్త ఫీచర్లు.', lawyerPortal: 'లాయర్ పోర్టల్', statsRating: 'రేటింగ్', statsReviews: 'సమీక్షలు', statsVerified: 'ధృవీకరించబడింది', statsExperience: 'అనుభవం', profileDetails: 'వివరాలు', editProfile: 'సవరించండి', city: 'నగరం:', fee: 'రుసుము:', specializations: 'స్పెషలైజేషన్స్:', languages: 'భాషలు:', completeProfile: 'పూర్తి చేయండి', completeProfileDesc: 'ప్రొఫైల్‌ను సెటప్ చేయండి.', lawyerComingSoon: 'త్వరలో రానుంది', lawyerComingSoonDesc: 'అభ్యర్థనలను నిర్వహించండి.' },
  lawyersPage: { title: 'న్యాయవాదులను కనుగొనండి', subtitle: 'న్యాయవాదులను బ్రౌజ్ చేయండి.', searchPlaceholder: 'శోధించండి...', filters: 'ఫిల్టర్లు', experience: 'అనుభవం', fees: 'ఫీజు', languages: 'భాషలు', availability: 'లభ్యత', verifiedOnly: 'ధృవీకరించబడిన నిపుణులు మాత్రమే', clearFilters: 'క్లియర్ చేయండి', noLawyers: 'న్యాయవాదులు కనుగొనబడలేదు.', bookConsultation: 'బుక్ చేయండి', viewProfile: 'ప్రొఫైల్ చూడండి', reviews: 'సమీక్షలు', rating: 'రేటింగ్', location: 'స్థానం' }
};

const mr: Translation = {
  nav: { lawyers: 'वकील', knowledge: 'ज्ञानकोष', templates: 'टेम्पलेट्स', rights: 'तुमचे अधिकार जाणून घ्या', login: 'लॉगिन', signup: 'साइन अप' },
  hero: { title: 'काही मिनिटांत कायदेशीर मदत मिळवा', subtitle: 'Get Legal Help in Minutes', searchLaw: 'कायद्यानुसार वकील शोधा', searchCity: 'शहर किंवा पिनकोड', searchBtn: 'शोधा', forCitizens: 'नागरिकांसाठी', forLawyers: 'वकिलांसाठी' },
  features: { title: 'कायदेशीर शांततेसाठी सर्व काही', subtitle: 'सत्यापित वकील, विनामूल्य माहिती मिळवा.', f1Title: 'वकील शोधा', f1Desc: 'तुमच्या जवळचे वकील शोधा.', f2Title: 'सल्लामसलत बुक करा', f2Desc: 'सुरक्षितपणे गप्पा मारा.', f3Title: 'कायदेशीर माहिती', f3Desc: 'अधिकार समजून घ्या.', f4Title: 'टेम्पलेट्स', f4Desc: 'कायदेशीर स्वरूप डाउनलोड करा.' },
  howItWorks: { title: 'LexIndia कसे कार्य करते', subtitle: 'तीन सोप्या चरणांमध्ये मदत मिळवा.', s1Title: 'शोधा', s1Desc: 'वकील शोधा.', s2Title: 'प्रोफाइल तपासा', s2Desc: 'अनुभव आणि फी तपासा.', s3Title: 'बुक करा आणि गप्पा मारा', s3Desc: 'तुमच्या प्रकरणावर चर्चा करा.' },
  categories: { title: 'विशेषज्ञतेनुसार वकील शोधा', subtitle: 'विविध कायदेशीर डोमेनमध्ये शीर्ष-रेट केलेले वकील ब्राउझ करा.', viewAll: 'सर्व पहा', c1: 'फौजदारी कायदा', c2: 'कौटुंबिक कायदा', c3: 'मालमत्ता कायदा', c4: 'कॉर्पोरेट कायदा', c5: 'दिवाणी कायदा', c6: 'सायबर कायदा', lawyers: 'वकील' },
  testimonials: { title: 'तयार आहात?', subtitle: 'हजारो नागरिकांमध्ये सामील व्हा.', startBtn: 'सुरुवात करा', quote: "LexIndia ने सोपे केले!", role: 'ग्राहक' },
  footer: { desc: 'कायदेशीर मदत सुलभ करणे.', forCitizens: 'नागरिकांसाठी', findLawyer: 'वकील शोधा', knowledge: 'ज्ञानकोष', templates: 'टेम्पलेट्स', rights: 'अधिकार जाणून घ्या', forLawyers: 'वकिलांसाठी', joinDir: 'सामील व्हा', dashboard: 'डॅशबोर्ड', pricing: 'किंमत', company: 'कंपनी', about: 'आमच्याबद्दल', contact: 'संपर्क', privacy: 'गोपनीयता', terms: 'अटी', rightsRes: 'सर्व हक्क राखीव.', disclaimer: 'व्यावसायिक सल्ल्याला पर्याय नाही.' },
  common: { search: 'शोधा', loading: 'लोड होत आहे...', noResults: 'कोणतेही परिणाम नाहीत', viewDetails: 'तपशील पहा', save: 'सेव्ह करा', cancel: 'रद्द करा', back: 'मागे', continue: 'सुरू ठेवा', error: 'त्रुटी आली', success: 'यश!', filterBy: 'फिल्टर करा', sort: 'क्रमवारी करा', all: 'सर्व' },
  auth: { loginTitle: 'साइन इन करा', loginSub: 'डॅशबोर्डवर प्रवेश करा.', signupTitle: 'खाते तयार करा', signupSub: 'आमच्यात सामील व्हा.', emailLabel: 'ईमेल', passLabel: 'पासवर्ड', nameLabel: 'नाव', forgotPass: 'विसरलात?', loginBtn: 'साइन इन करा', signupBtn: 'तयार करा', noAccount: "खाते नाही?", hasAccount: 'खाते आहे का?', continueGoogle: 'Google सह सुरू ठेवा', roleCitizen: 'मी नागरिक आहे', roleLawyer: 'मी वकील आहे', emailPh: 'तुम्ही@example.com', passPh: 'किमान ८ अक्षरे', namePh: 'तुमचे नाव', passRequirements: 'किमान ८ अक्षरे आवश्यक' },
  knowledge: { title: 'कायदेशीर माहिती', subtitle: 'कायदे समजून घ्या.', searchPlaceholder: 'शोधा...', categories: 'श्रेण्या', popular: 'विषय', readMore: 'वाचा', backToList: 'मागे', related: 'संबंधित लेख', wasHelpful: 'उपयुक्त होते का?', yes: 'होय', no: 'नाही' },
  templates: { title: 'टेम्पलेट्स', subtitle: 'स्वरूप डाउनलोड करा.', searchPlaceholder: 'शोधा...', downloadBtn: 'डाउनलोड करा', preview: 'पूर्वावलोकन', category: 'श्रेणी', format: 'स्वरूप', size: 'आकार', requirements: 'आवश्यकता', instructions: 'सूचना' },
  dashboard: { title: 'डॅशबोर्ड', welcome: 'स्वागत आहे', appointments: 'भेटी', profile: 'प्रोफाइल', settings: 'सेटिंग्ज', messages: 'संदेश', viewAll: 'सर्व पहा', upcoming: 'आगामी', past: 'मागील', noAppointments: 'भेटी नाहीत', signOut: 'साइन आउट करा', quickActions: 'कृती', findLawyer: 'वकील शोधा', findLawyerDesc: 'वकील ब्राउझ करा', legalKnowledge: 'कायदेशीर ज्ञान', legalKnowledgeDesc: 'अधिकार जाणून घ्या', legalTemplates: 'टेम्पलेट्स', legalTemplatesDesc: 'दस्तऐवज डाउनलोड करा', myAppointments: 'माझ्या भेटी', myAppointmentsDesc: 'सल्लामसलत पहा', comingSoon: 'लवकरच येत आहे', comingSoonDesc: 'नवीन वैशिष्ट्ये.', lawyerPortal: 'वकील पोर्टल', statsRating: 'रेटिंग', statsReviews: 'पुनरावलोकने', statsVerified: 'सत्यापित', statsExperience: 'अनुभव', profileDetails: 'तपशील', editProfile: 'संपादित करा', city: 'शहर:', fee: 'फी:', specializations: 'विशेषज्ञता:', languages: 'भाषा:', completeProfile: 'पूर्ण करा', completeProfileDesc: 'प्रोफाइल सेट करा.', lawyerComingSoon: 'लवकरच येत आहे', lawyerComingSoonDesc: 'विनंत्या व्यवस्थापित करा.' },
  lawyersPage: { title: 'वकील शोधा', subtitle: 'वकील ब्राउझ करा.', searchPlaceholder: 'शोधा...', filters: 'फिल्टर', experience: 'अनुभव', fees: 'फी', languages: 'भाषा', availability: 'उपलब्धता', verifiedOnly: 'केवळ सत्यापित व्यावसायिक', clearFilters: 'साफ करा', noLawyers: 'कोणतेही वकील आढळले नाहीत.', bookConsultation: 'बुक करा', viewProfile: 'प्रोफाइल पहा', reviews: 'पुनरावलोकने', rating: 'रेटिंग', location: 'ठिकाण' }
};

const ta: Translation = {
  nav: { lawyers: 'வழக்கறிஞர்கள்', knowledge: 'அறிவு தளம்', templates: 'படிவங்கள்', rights: 'உரிமைகளை அறிவோம்', login: 'உள்நுழைக', signup: 'பதிவு செய்க' },
  hero: { title: 'நிமிடங்களில் சட்ட உதவி பெறுங்கள்', subtitle: 'Get Legal Help in Minutes', searchLaw: 'சட்டரீதியாக வழக்கறிஞர்களைத் தேடுங்கள்', searchCity: 'நகரம் அல்லது பின்கோடு', searchBtn: 'தேடு', forCitizens: 'குடிமக்களுக்கு', forLawyers: 'வழக்கறிஞர்களுக்கு' },
  features: { title: 'உங்களுக்குத் தேவையான அனைத்தும்', subtitle: 'சரிபார்க்கப்பட்ட வழக்கறிஞர்கள், இலவச தகவல்களை அணுகவும்.', f1Title: 'வழக்கறிஞர்களைத் தேடுங்கள்', f1Desc: 'சிறந்த வழக்கறிஞர்களைக் கண்டறியவும்.', f2Title: 'ஆலோசனைக்கு முன்பதிவு', f2Desc: 'சட்ட நிபுணர்களுடன் அரட்டையடிக்கவும்.', f3Title: 'இலவச தகவல்', f3Desc: 'உரிமைகளைப் புரிந்துகொள்ளுங்கள்.', f4Title: 'படிவங்கள்', f4Desc: 'சட்ட வடிவங்களைப் பதிவிறக்கவும்.' },
  howItWorks: { title: 'LexIndia எவ்வாறு செயல்படுகிறது', subtitle: 'மூன்று எளிய படிகளில் உதவி பெறுங்கள்.', s1Title: 'தேடு', s1Desc: 'வழக்கறிஞர்களைக் கண்டறியவும்.', s2Title: 'மதிப்பாய்வு செய்யவும்', s2Desc: 'அனுபவம் மற்றும் கட்டணங்களைச் சரிபார்க்கவும்.', s3Title: 'முன்பதிவு & அரட்டை', s3Desc: 'உங்கள் வழக்கை விவாதிக்கவும்.' },
  categories: { title: 'நிபுணத்துவத்தின்படி வழக்கறிஞர்களைக் கண்டறியவும்', subtitle: 'பல்வேறு சட்ட களங்களில் சிறந்த வழக்கறிஞர்களை உலாவவும்.', viewAll: 'அனைத்தையும் காண்க', c1: 'குற்றவியல் சட்டம்', c2: 'குடும்ப சட்டம்', c3: 'சொத்து சட்டம்', c4: 'கார்ப்பரேட் சட்டம்', c5: 'சிவில் சட்டம்', c6: 'சைபர் சட்டம்', lawyers: 'வழக்கறிஞர்கள்' },
  testimonials: { title: 'தயாரா?', subtitle: 'ஆயிரக்கணக்கான குடிமக்களுடன் சேருங்கள்.', startBtn: 'தொடங்குங்கள்', quote: "LexIndia மிகவும் எளிதாக்கியது!", role: 'வாடிக்கையாளர்' },
  footer: { desc: 'சட்ட உதவியை அணுகக்கூடியதாக மாற்றுதல்.', forCitizens: 'குடிமக்களுக்கு', findLawyer: 'வழக்கறிஞரைக் கண்டறியவும்', knowledge: 'அறிவு தளம்', templates: 'படிவங்கள்', rights: 'உரிமைகளை அறியுங்கள்', forLawyers: 'வழக்கறிஞர்களுக்கு', joinDir: 'சேரவும்', dashboard: 'டாஷ்போர்டு', pricing: 'விலை', company: 'நிறுவனம்', about: 'எங்களை பற்றி', contact: 'தொடர்பு கொள்ள', privacy: 'தனியுரிமை', terms: 'விதிமுறைகள்', rightsRes: 'அனைத்து உரிமைகளும் பாதுகாக்கப்பட்டவை.', disclaimer: 'சட்ட ஆலோசனைக்கு மாற்றாக இல்லை.' },
  common: { search: 'தேடு', loading: 'ஏற்றுகிறது...', noResults: 'முடிவுகள் இல்லை', viewDetails: 'விவரங்களை காண்க', save: 'சேமி', cancel: 'ரத்து செய்', back: 'பின்னோக்கி', continue: 'தொடரவும்', error: 'ஒரு பிழை', success: 'வெற்றி!', filterBy: 'வடிகட்டு', sort: 'வரிசைப்படுத்து', all: 'அனைத்தும்' },
  auth: { loginTitle: 'உள்நுழைக', loginSub: 'உங்கள் டாஷ்போர்டை அணுகவும்.', signupTitle: 'கணக்கை உருவாக்கவும்', signupSub: 'எங்களுடன் சேருங்கள்.', emailLabel: 'மின்னஞ்சல்', passLabel: 'கடவுச்சொல்', nameLabel: 'பெயர்', forgotPass: 'மறந்துவிட்டதா?', loginBtn: 'உள்நுழைக', signupBtn: 'உருவாக்கவும்', noAccount: "கணக்கு இல்லையா?", hasAccount: 'கணக்கு உள்ளதா?', continueGoogle: 'Google உடன் தொடரவும்', roleCitizen: 'நான் குடிமகன்', roleLawyer: 'நான் வழக்கறிஞர்', emailPh: 'நீங்கள்@example.com', passPh: 'குறைந்தபட்சம் 8 எழுத்துக்கள்', namePh: 'பெயர்', passRequirements: '8 எழுத்துகள் இருக்க வேண்டும்' },
  knowledge: { title: 'சட்ட தகவல்', subtitle: 'சட்டங்களை புரிந்து கொள்ளுங்கள்.', searchPlaceholder: 'தேடுங்கள்...', categories: 'வகைகள்', popular: 'தலைப்புகள்', readMore: 'படிக்கவும்', backToList: 'திரும்பு', related: 'தொடர்புடைய கட்டுரைகள்', wasHelpful: 'பயனுள்ளதாக இருந்ததா?', yes: 'ஆம்', no: 'இல்லை' },
  templates: { title: 'படிவங்கள்', subtitle: 'வடிவங்களைப் பதிவிறக்கவும்.', searchPlaceholder: 'தேடுங்கள்...', downloadBtn: 'பதிவிறக்கவும்', preview: 'முன்னோட்டம்', category: 'வகை', format: 'வடிவமைப்பு', size: 'அளவு', requirements: 'தேவைகள்', instructions: 'வழிமுறைகள்' },
  dashboard: { title: 'டாஷ்போர்டு', welcome: 'மீண்டும் வருக', appointments: 'சந்திப்புகள்', profile: 'சுயவிவரம்', settings: 'அமைப்புகள்', messages: 'செய்திகள்', viewAll: 'அனைத்தையும் காண்க', upcoming: 'வரவிருக்கும்', past: 'கடந்த', noAppointments: 'சந்திப்புகள் இல்லை', signOut: 'வெளியேறு', quickActions: 'செயல்கள்', findLawyer: 'வழக்கறிஞரைக் கண்டறியவும்', findLawyerDesc: 'வழக்கறிஞர்களை உலாவவும்', legalKnowledge: 'சட்ட அறிவு', legalKnowledgeDesc: 'உரிமைகளை அறியுங்கள்', legalTemplates: 'படிவங்கள்', legalTemplatesDesc: 'ஆவணங்களைப் பதிவிறக்கவும்', myAppointments: 'எனது சந்திப்புகள்', myAppointmentsDesc: 'ஆலோசனைகளைப் பார்க்கவும்', comingSoon: 'விரைவில் வரும்', comingSoonDesc: 'புதிய அம்சங்கள்.', lawyerPortal: 'போர்ட்டல்', statsRating: 'மதிப்பீடு', statsReviews: 'விமர்சனங்கள்', statsVerified: 'சரிபார்க்கப்பட்டது', statsExperience: 'அனுபவம்', profileDetails: 'விவரங்கள்', editProfile: 'திருத்து', city: 'நகரம்:', fee: 'கட்டணம்:', specializations: 'சிறப்புத் துறைகள்:', languages: 'மொழிகள்:', completeProfile: 'முடிக்கவும்', completeProfileDesc: 'சுயவிவரத்தை அமைக்கவும்.', lawyerComingSoon: 'விரைவில் வரும்', lawyerComingSoonDesc: 'கோரிக்கைகளை நிர்வகிக்கவும்.' },
  lawyersPage: { title: 'வழக்கறிஞர்களைக் கண்டறியவும்', subtitle: 'வழக்கறிஞர்களை உலாவவும்.', searchPlaceholder: 'தேடுங்கள்...', filters: 'வடிகட்டிகள்', experience: 'அனுபவம்', fees: 'கட்டணம்', languages: 'மொழிகள்', availability: 'கிடைக்கும்', verifiedOnly: 'சரிபார்க்கப்பட்ட வல்லுநர்கள்', clearFilters: 'அழிக்கவும்', noLawyers: 'வழக்கறிஞர்கள் யாரும் இல்லை.', bookConsultation: 'முன்பதிவு', viewProfile: 'சுயவிவரத்தைக் காண்க', reviews: 'விமர்சனங்கள்', rating: 'மதிப்பீடு', location: 'இடம்' }
};

const ur: Translation = {
  nav: { lawyers: 'وکیل', knowledge: 'معلومات', templates: 'ٹیمپلیٹس', rights: 'اپنے حقوق جانیں', login: 'لاگ ان', signup: 'سائن اپ' },
  hero: { title: 'منٹوں میں قانونی مدد حاصل کریں', subtitle: 'Get Legal Help in Minutes', searchLaw: 'قانون کے مطابق وکیل تلاش کریں', searchCity: 'شہر یا پن کوڈ', searchBtn: 'تلاش کریں', forCitizens: 'شہریوں کے لیے', forLawyers: 'وکیلوں کے لیے' },
  features: { title: 'آپ کی ضرورت کی ہر چیز', subtitle: 'تصدیق شدہ وکیلوں تک رسائی حاصل کریں۔', f1Title: 'وکیل تلاش کریں', f1Desc: 'قریبی وکیل تلاش کریں۔', f2Title: 'مشاورت بک کریں', f2Desc: 'وکیلوں سے بات کریں۔', f3Title: 'مفت قانونی معلومات', f3Desc: 'اپنے حقوق جانیں۔', f4Title: 'ٹیمپلیٹس', f4Desc: 'قانونی دستاویزات ڈاؤن لوڈ کریں۔' },
  howItWorks: { title: 'LexIndia کیسے کام کرتا ہے', subtitle: 'تین آسان مراحل میں مدد حاصل کریں۔', s1Title: 'تلاش کریں', s1Desc: 'وکیل تلاش کریں۔', s2Title: 'پروفائلز کا جائزہ لیں', s2Desc: 'تجربہ اور فیس چیک کریں۔', s3Title: 'بک کریں اور بات کریں', s3Desc: 'اپنے کیس پر تبادلہ خیال کریں۔' },
  categories: { title: 'مہارت کے لحاظ سے وکیل تلاش کریں', subtitle: 'مختلف قانونی شعبوں میں چوٹی کے وکلاء کو براؤز کریں۔', viewAll: 'سب دیکھیں', c1: 'فوجداری قانون', c2: 'عائلی قانون', c3: 'پراپرٹی کا قانون', c4: 'کارپوریٹ قانون', c5: 'سول قانون', c6: 'سائبر قانون', lawyers: 'وکیل' },
  testimonials: { title: 'کیا آپ تیار ہیں؟', subtitle: 'ہزاروں شہریوں میں شامل ہوں۔', startBtn: 'شروع کریں', quote: "LexIndia نے اسے بہت آسان بنا دیا!", role: 'کلائنٹ' },
  footer: { desc: 'قانونی مدد کو قابل رسائی بنانا۔', forCitizens: 'شہریوں کے لیے', findLawyer: 'وکیل تلاش کریں', knowledge: 'معلومات', templates: 'ٹیمپلیٹس', rights: 'اپنے حقوق جانیں', forLawyers: 'وکیلوں کے لیے', joinDir: 'ڈائرکٹری میں شامل ہوں', dashboard: 'ڈیش بورڈ', pricing: 'قیمتیں', company: 'کمپنی', about: 'ہمارے بارے میں', contact: 'رابطہ کریں', privacy: 'رازداری', terms: 'شرائط', rightsRes: 'جملہ حقوق محفوظ ہیں۔', disclaimer: 'یہ قانونی مشورے کا متبادل نہیں ہے۔' },
  common: { search: 'تلاش کریں', loading: 'لوڈ ہو رہا ہے...', noResults: 'کوئی نتیجہ نہیں ملا', viewDetails: 'تفصیلات دیکھیں', save: 'محفوظ کریں', cancel: 'منسوخ کریں', back: 'پیچھے', continue: 'جاری رکھیں', error: 'ایک خرابی پیش آ گئی', success: 'کامیابی!', filterBy: 'فلٹر کریں', sort: 'ترتیب دیں', all: 'سب' },
  auth: { loginTitle: 'لاگ ان کریں', loginSub: 'اپنے ڈیش بورڈ تک رسائی حاصل کریں۔', signupTitle: 'اکاؤنٹ بنائیں', signupSub: 'ہمارے ساتھ شامل ہوں۔', emailLabel: 'ای میل', passLabel: 'پاس ورڈ', nameLabel: 'نام', forgotPass: 'پاس ورڈ بھول گئے؟', loginBtn: 'لاگ ان کریں', signupBtn: 'اکاؤنٹ بنائیں', noAccount: "اکاؤنٹ نہیں ہے؟", hasAccount: 'کیا آپ کے پاس پہلے سے اکاؤنٹ ہے؟', continueGoogle: 'Google کے ساتھ جاری رکھیں', roleCitizen: 'میں شہری ہوں', roleLawyer: 'میں وکیل ہوں', emailPh: 'آپ@example.com', passPh: 'کم از کم 8 حروف', namePh: 'آپ کا نام', passRequirements: 'کم از کم 8 حروف' },
  knowledge: { title: 'قانونی معلومات', subtitle: 'قوانین کو سمجھیں۔', searchPlaceholder: 'تلاش کریں...', categories: 'اقسام', popular: 'موضوعات', readMore: 'مزید پڑھیں', backToList: 'پیچھے جائیں', related: 'متعلقہ مضامین', wasHelpful: 'کیا یہ مددگار تھا؟', yes: 'ہاں', no: 'نہیں' },
  templates: { title: 'ٹیمپلیٹس', subtitle: 'فارمیٹس ڈاؤن لوڈ کریں۔', searchPlaceholder: 'تلاش کریں...', downloadBtn: 'ڈاؤن لوڈ کریں', preview: 'پیش نظارہ', category: 'قسم', format: 'فارمیٹ', size: 'سائز', requirements: 'ضروریات', instructions: 'ہدایات' },
  dashboard: { title: 'ڈیش بورڈ', welcome: 'خوش آمدید', appointments: 'ملاقاتیں', profile: 'پروفائل', settings: 'ترتیبات', messages: 'پیغامات', viewAll: 'سب دیکھیں', upcoming: 'آنے والی', past: 'گزشتہ', noAppointments: 'کوئی ملاقات نہیں', signOut: 'سائن آؤٹ', quickActions: 'فوری اقدامات', findLawyer: 'وکیل تلاش کریں', findLawyerDesc: 'وکلاء کو براؤز کریں', legalKnowledge: 'قانونی علم', legalKnowledgeDesc: 'اپنے حقوق جانیں', legalTemplates: 'ٹیمپلیٹس', legalTemplatesDesc: 'دستاویزات ڈاؤن لوڈ کریں', myAppointments: 'میری ملاقاتیں', myAppointmentsDesc: 'مشاورت دیکھیں', comingSoon: 'جلد آ رہا ہے', comingSoonDesc: 'نئی خصوصیات۔', lawyerPortal: 'لائر پورٹل', statsRating: 'درجہ بندی', statsReviews: 'جائزے', statsVerified: 'تصدیق شدہ', statsExperience: 'تجربہ', profileDetails: 'تفصیلات', editProfile: 'ترمیم کریں', city: 'شہر:', fee: 'فیس:', specializations: 'مہارتیں:', languages: 'زبانیں:', completeProfile: 'مکمل کریں', completeProfileDesc: 'پروفائل سیٹ اپ کریں۔', lawyerComingSoon: 'جلد آ رہا ہے', lawyerComingSoonDesc: 'درخواستوں کا نظم کریں۔' },
  lawyersPage: { title: 'وکیل تلاش کریں', subtitle: 'وکلاء کو براؤز کریں۔', searchPlaceholder: 'تلاش کریں...', filters: 'فلٹرز', experience: 'تجربہ', fees: 'فیس', languages: 'زبانیں', availability: 'دستیابی', verifiedOnly: 'صرف تصدیق شدہ', clearFilters: 'صاف کریں', noLawyers: 'کوئی وکیل نہیں ملا۔', bookConsultation: 'بک کریں', viewProfile: 'پروفائل دیکھیں', reviews: 'جائزے', rating: 'درجہ بندی', location: 'مقام' }
};

const gu: Translation = {
  nav: { lawyers: 'વકીલો', knowledge: 'જ્ઞાન આધાર', templates: 'ટેમ્પ્લેટ્સ', rights: 'તમારા અધિકારો જાણો', login: 'લૉગિન', signup: 'સાઇન અપ' },
  hero: { title: 'મિનિટોમાં કાનૂની મદદ મેળવો', subtitle: 'Get Legal Help in Minutes', searchLaw: 'કાયદા દ્વારા વકીલો શોધો', searchCity: 'શહેર અથવા પિનકોડ', searchBtn: 'શોધો', forCitizens: 'નાગરિકો માટે', forLawyers: 'વકીલો માટે' },
  features: { title: 'તમને જોઈતી દરેક વસ્તુ', subtitle: 'ચકાસાયેલ વકીલો, મફત કાનૂની માહિતી ઍક્સેસ કરો.', f1Title: 'વકીલ શોધો', f1Desc: 'નજીકના વકીલો શોધો.', f2Title: 'કન્સલ્ટેશન બુક કરો', f2Desc: 'નિષ્ણાતો સાથે ચેટ કરો.', f3Title: 'મફત કાનૂની માહિતી', f3Desc: 'તમારા અધિકારો સમજો.', f4Title: 'ટેમ્પ્લેટ્સ', f4Desc: 'કાનૂની નમૂનાઓ ડાઉનલોડ કરો.' },
  howItWorks: { title: 'LexIndia કેવી રીતે કાર્ય કરે છે', subtitle: 'ત્રણ સરળ પગલાઓમાં મદદ મેળવો.', s1Title: 'શોધો', s1Desc: 'વકીલો શોધો.', s2Title: 'પ્રોફાઇલ્સની સમીક્ષા કરો', s2Desc: 'અનુભવ અને ફી તપાસો.', s3Title: 'બુક કરો અને ચેટ કરો', s3Desc: 'તમારા કેસ વિશે ચર્ચા કરો.' },
  categories: { title: 'નિષ્ણાતતા દ્વારા વકીલો શોધો', subtitle: 'વિવિધ કાનૂની ડોમેન્સમાં ટોચના વકીલો બ્રાઉઝ કરો.', viewAll: 'બધું જુઓ', c1: 'ફોજદારી કાયદો', c2: 'કૌટુંબિક કાયદો', c3: 'મિલકત કાયદો', c4: 'કોર્પોરેટ કાયદો', c5: 'નાગરિક કાયદો', c6: 'સાયબર કાયદો', lawyers: 'વકીલો' },
  testimonials: { title: 'શું તમે તૈયાર છો?', subtitle: 'હજારો નાગરિકો સાથે જોડાઓ.', startBtn: 'શરૂ કરો', quote: "LexIndia એ ખૂબ જ સરળ બનાવ્યું!", role: 'ગ્રાહક' },
  footer: { desc: 'કાનૂની મદદ સુલભ બનાવવી.', forCitizens: 'નાગરિકો માટે', findLawyer: 'વકીલ શોધો', knowledge: 'જ્ઞાન આધાર', templates: 'ટેમ્પ્લેટ્સ', rights: 'અધિકારો જાણો', forLawyers: 'વકીલો માટે', joinDir: 'જોડાવો', dashboard: 'ડેશબોર્ડ', pricing: 'કિંમત', company: 'કંપની', about: 'અમારા વિશે', contact: 'સંપર્ક', privacy: 'ગોપનીયતા', terms: 'શરતો', rightsRes: 'સર્વાધિકાર સુરક્ષિત.', disclaimer: 'કાનૂની સલાહનો વિકલ્પ નથી.' },
  common: { search: 'શોધો', loading: 'લોડ થઈ રહ્યું છે...', noResults: 'કોઈ પરિણામ મળ્યું નથી', viewDetails: 'વિગતો જુઓ', save: 'સાચવો', cancel: 'રદ કરો', back: 'પાછળ', continue: 'ચાલુ રાખો', error: 'ભૂલ આવી', success: 'સફળતા!', filterBy: 'ફિલ્ટર કરો', sort: 'ક્રમમાં ગોઠવો', all: 'બધા' },
  auth: { loginTitle: 'લૉગિન કરો', loginSub: 'તમારા ડેશબોર્ડને ઍક્સેસ કરો.', signupTitle: 'એકાઉન્ટ બનાવો', signupSub: 'અમારી સાથે જોડાઓ.', emailLabel: 'ઇમેઇલ', passLabel: 'પાસવર્ડ', nameLabel: 'નામ', forgotPass: 'પાસવર્ડ ભૂલી ગયા છો?', loginBtn: 'લૉગિન કરો', signupBtn: 'બનાવો', noAccount: "એકાઉન્ટ નથી?", hasAccount: 'શું તમારી પાસે એકાઉન્ટ છે?', continueGoogle: 'Google સાથે ચાલુ રાખો', roleCitizen: 'હું નાગરિક છું', roleLawyer: 'હું વકીલ છું', emailPh: 'તમે@example.com', passPh: 'ઓછામાં ઓછા 8 અક્ષરો', namePh: 'તમારું નામ', passRequirements: '8 અક્ષરો હોવા જોઈએ' },
  knowledge: { title: 'કાનૂની માહિતી', subtitle: 'કાયદા સમજો.', searchPlaceholder: 'શોધો...', categories: 'શ્રેણીઓ', popular: 'વિષયો', readMore: 'વાંચો', backToList: 'પાછળ', related: 'સંબંધિત લેખો', wasHelpful: 'શું આ મદદરૂપ હતું?', yes: 'હા', no: 'ના' },
  templates: { title: 'ટેમ્પ્લેટ્સ', subtitle: 'ફોર્મેટ્સ ડાઉનલોડ કરો.', searchPlaceholder: 'શોધો...', downloadBtn: 'ડાઉનલોડ કરો', preview: 'પૂર્વાવલોકન', category: 'શ્રેણી', format: 'ફોર્મેટ', size: 'કદ', requirements: 'જરૂરિયાતો', instructions: 'સૂચનાઓ' },
  dashboard: { title: 'ડેશબોર્ડ', welcome: 'સ્વાગત છે', appointments: 'એપોઇન્ટમેન્ટ્સ', profile: 'પ્રોફાઇલ', settings: 'સેટિંગ્સ', messages: 'સંદેશાઓ', viewAll: 'બધું જુઓ', upcoming: 'આગામી', past: 'ભૂતકાળ', noAppointments: 'કોઈ એપોઇન્ટમેન્ટ નથી', signOut: 'સાઇન આઉટ', quickActions: 'ક્રિયાઓ', findLawyer: 'વકીલ શોધો', findLawyerDesc: 'વકીલો બ્રાઉઝ કરો', legalKnowledge: 'કાનૂની જ્ઞાન', legalKnowledgeDesc: 'અધિકારો જાણો', legalTemplates: 'ટેમ્પ્લેટ્સ', legalTemplatesDesc: 'દસ્તાવેજો ડાઉનલોડ કરો', myAppointments: 'મારી એપોઇન્ટમેન્ટ્સ', myAppointmentsDesc: 'પરામર્શ જુઓ', comingSoon: 'ટૂંક સમયમાં આવી રહ્યું છે', comingSoonDesc: 'નવી સુવિધાઓ.', lawyerPortal: 'વકીલ પોર્ટલ', statsRating: 'રેટિંગ', statsReviews: 'સમીક્ષાઓ', statsVerified: 'ચકાસાયેલ', statsExperience: 'અનુભવ', profileDetails: 'વિગતો', editProfile: 'ફેરફાર કરો', city: 'શહેર:', fee: 'ફી:', specializations: 'નિષ્ણાતતા:', languages: 'ભાષાઓ:', completeProfile: 'પૂર્ણ કરો', completeProfileDesc: 'પ્રોફાઇલ સેટ કરો.', lawyerComingSoon: 'ટૂંક સમયમાં આવી રહ્યું છે', lawyerComingSoonDesc: 'વિનંતીઓ મેનેજ કરો.' },
  lawyersPage: { title: 'વકીલો શોધો', subtitle: 'વકીલો બ્રાઉઝ કરો.', searchPlaceholder: 'શોધો...', filters: 'ફિલ્ટર્સ', experience: 'અનુભવ', fees: 'ફી', languages: 'ભાષાઓ', availability: 'ઉપલબ્ધતા', verifiedOnly: 'ફક્ત ચકાસાયેલ વ્યાવસાયિકો', clearFilters: 'સાફ કરો', noLawyers: 'કોઈ વકીલ મળ્યા નથી.', bookConsultation: 'બુક કરો', viewProfile: 'પ્રોફાઇલ જુઓ', reviews: 'સમીક્ષાઓ', rating: 'રેટિંગ', location: 'સ્થાન' }
};

const kn: Translation = {
  nav: { lawyers: 'ವಕೀಲರು', knowledge: 'ಜ್ಞಾನ ನೆಲೆ', templates: 'ಟೆಂಪ್ಲೇಟ್‌ಗಳು', rights: 'ನಿಮ್ಮ ಹಕ್ಕುಗಳನ್ನು ತಿಳಿಯಿರಿ', login: 'ಲಾಗಿನ್', signup: 'ಸೈನ್ ಅಪ್' },
  hero: { title: 'ನಿಮಿಷಗಳಲ್ಲಿ ಕಾನೂನು ಸಹಾಯ ಪಡೆಯಿರಿ', subtitle: 'Get Legal Help in Minutes', searchLaw: 'ಕಾನೂನಿನ ಮೂಲಕ ವಕೀಲರನ್ನು ಹುಡುಕಿ', searchCity: 'ನಗರ ಅಥವಾ ಪಿನ್‌ಕೋಡ್', searchBtn: 'ಹುಡುಕಿ', forCitizens: 'ನಾಗರಿಕರಿಗಾಗಿ', forLawyers: 'ವಕೀಲರಿಗಾಗಿ' },
  features: { title: 'ನಿಮಗೆ ಬೇಕಾಗಿರುವುದೆಲ್ಲವೂ', subtitle: 'ಪರಿಶೀಲಿಸಿದ ವಕೀಲರು, ಉಚಿತ ಕಾನೂನು ಮಾಹಿತಿಯನ್ನು ಪ್ರವೇಶಿಸಿ.', f1Title: 'ವಕೀಲರನ್ನು ಹುಡುಕಿ', f1Desc: 'ಹತ್ತಿರದ ವಕೀಲರನ್ನು ಹುಡುಕಿ.', f2Title: 'ಸಮಾಲೋಚನೆ ಕಾಯ್ದಿರಿಸಿ', f2Desc: 'ತಜ್ಞರೊಂದಿಗೆ ಚಾಟ್ ಮಾಡಿ.', f3Title: 'ಉಚಿತ ಕಾನೂನು ಮಾಹಿತಿ', f3Desc: 'ನಿಮ್ಮ ಹಕ್ಕುಗಳನ್ನು ಅರ್ಥಮಾಡಿಕೊಳ್ಳಿ.', f4Title: 'ಟೆಂಪ್ಲೇಟ್‌ಗಳು', f4Desc: 'ಕಾನೂನು ದಾಖಲೆಗಳನ್ನು ಡೌನ್‌ಲೋಡ್ ಮಾಡಿ.' },
  howItWorks: { title: 'LexIndia ಹೇಗೆ ಕೆಲಸ ಮಾಡುತ್ತದೆ', subtitle: 'ಮೂರು ಸುಲಭ ಹಂತಗಳಲ್ಲಿ ಸಹಾಯ ಪಡೆಯಿರಿ.', s1Title: 'ಹುಡುಕಿ', s1Desc: 'ವಕೀಲರನ್ನು ಹುಡುಕಿ.', s2Title: 'ಪ್ರೊಫೈಲ್‌ಗಳನ್ನು ಪರಿಶೀಲಿಸಿ', s2Desc: 'ಅನುಭವ ಮತ್ತು ಶುಲ್ಕವನ್ನು ಪರಿಶೀಲಿಸಿ.', s3Title: 'ಬುಕ್ ಮಾಡಿ ಮತ್ತು ಚಾಟ್ ಮಾಡಿ', s3Desc: 'ನಿಮ್ಮ ಪ್ರಕರಣವನ್ನು ಚರ್ಚಿಸಿ.' },
  categories: { title: 'ಪರಿಣತಿಯ ಮೂಲಕ ವಕೀಲರನ್ನು ಹುಡುಕಿ', subtitle: 'ವಿವಿಧ ಕಾನೂನು ಡೊಮೇನ್‌ಗಳಲ್ಲಿ ಉನ್ನತ ವಕೀಲರನ್ನು ಬ್ರೌಸ್ ಮಾಡಿ.', viewAll: 'ಎಲ್ಲವನ್ನೂ ವೀಕ್ಷಿಸಿ', c1: 'ಕ್ರಿಮಿನಲ್ ಕಾನೂನು', c2: 'ಕುಟುಂಬ ಕಾನೂನು', c3: 'ಆಸ್ತಿ ಕಾನೂನು', c4: 'ಕಾರ್ಪೊರೇಟ್ ಕಾನೂನು', c5: 'ಸಿವಿಲ್ ಕಾನೂನು', c6: 'ಸೈಬರ್ ಕಾನೂನು', lawyers: 'ವಕೀಲರು' },
  testimonials: { title: 'ನೀವು ಸಿದ್ಧರಿದ್ದೀರಾ?', subtitle: 'ಸಾವಿರಾರು ನಾಗರಿಕರೊಂದಿಗೆ ಸೇರಿ.', startBtn: 'ಪ್ರಾರಂಭಿಸಿ', quote: "LexIndia ಇದನ್ನು ತುಂಬಾ ಸುಲಭಗೊಳಿಸಿದೆ!", role: 'ಗ್ರಾಹಕ' },
  footer: { desc: 'ಕಾನೂನು ಸಹಾಯವನ್ನು ಸುಲಭವಾಗಿಸುವುದು.', forCitizens: 'ನಾಗರಿಕರಿಗಾಗಿ', findLawyer: 'ವಕೀಲರನ್ನು ಹುಡುಕಿ', knowledge: 'ಜ್ಞಾನ ನೆಲೆ', templates: 'ಟೆಂಪ್ಲೇಟ್‌ಗಳು', rights: 'ಹಕ್ಕುಗಳನ್ನು ತಿಳಿಯಿರಿ', forLawyers: 'ವಕೀಲರಿಗಾಗಿ', joinDir: 'ಡೈರೆಕ್ಟರಿಗೆ ಸೇರಿ', dashboard: 'ಡ್ಯಾಶ್‌ಬೋರ್ಡ್', pricing: 'ಬೆಲೆ', company: 'ಕಂಪನಿ', about: 'ನಮ್ಮ ಬಗ್ಗೆ', contact: 'ಸಂಪರ್ಕಿಸಿ', privacy: 'ಗೌಪ್ಯತೆ', terms: 'ನಿಯಮಗಳು', rightsRes: 'ಎಲ್ಲಾ ಹಕ್ಕುಗಳನ್ನು ಕಾಯ್ದಿರಿಸಲಾಗಿದೆ.', disclaimer: 'ಕಾನೂನು ಸಲಹೆಗೆ ಪರ್ಯಾಯವಲ್ಲ.' },
  common: { search: 'ಹುಡುಕಿ', loading: 'ಲೋಡ್ ಆಗುತ್ತಿದೆ...', noResults: 'ಯಾವುದೇ ಫಲಿತಾಂಶಗಳಿಲ್ಲ', viewDetails: 'ವಿವರಗಳನ್ನು ವೀಕ್ಷಿಸಿ', save: 'ಉಳಿಸಿ', cancel: 'ರದ್ದುಮಾಡಿ', back: 'ಹಿಂದೆ', continue: 'ಮುಂದುವರಿಸಿ', error: 'ದೋಷ ಸಂಭವಿಸಿದೆ', success: 'ಯಶಸ್ಸು!', filterBy: 'ಫಿಲ್ಟರ್ ಮಾಡಿ', sort: 'ವಿಂಗಡಿಸಿ', all: 'ಎಲ್ಲಾ' },
  auth: { loginTitle: 'ಲಾಗಿನ್ ಮಾಡಿ', loginSub: 'ನಿಮ್ಮ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್ ಪ್ರವೇಶಿಸಿ.', signupTitle: 'ಖಾತೆ ರಚಿಸಿ', signupSub: 'ನಮ್ಮೊಂದಿಗೆ ಸೇರಿ.', emailLabel: 'ಇಮೇಲ್', passLabel: 'ಪಾಸ್‌ವರ್ಡ್', nameLabel: 'ಹೆಸರು', forgotPass: 'ಪಾಸ್‌ವರ್ಡ್ ಮರೆತಿರಾ?', loginBtn: 'ಲಾಗಿನ್ ಮಾಡಿ', signupBtn: 'ಖಾತೆ ರಚಿಸಿ', noAccount: "ಖಾತೆ ಇಲ್ಲವೇ?", hasAccount: 'ಈಗಾಗಲೇ ಖಾತೆ ಹೊಂದಿದ್ದೀರಾ?', continueGoogle: 'Google ನೊಂದಿಗೆ ಮುಂದುವರಿಸಿ', roleCitizen: 'ನಾನು ನಾಗರಿಕ', roleLawyer: 'ನಾನು ವಕೀಲ', emailPh: 'ನೀವು@example.com', passPh: 'ಕನಿಷ್ಠ 8 ಅಕ್ಷರಗಳು', namePh: 'ನಿಮ್ಮ ಹೆಸರು', passRequirements: 'ಕನಿಷ್ಠ 8 ಅಕ್ಷರಗಳು' },
  knowledge: { title: 'ಕಾನೂನು ಮಾಹಿತಿ', subtitle: 'ಕಾನೂನುಗಳನ್ನು ಅರ್ಥಮಾಡಿಕೊಳ್ಳಿ.', searchPlaceholder: 'ಹುಡುಕಿ...', categories: 'ವರ್ಗಗಳು', popular: 'ವಿಷಯಗಳು', readMore: 'ಮತ್ತಷ್ಟು ಓದಿ', backToList: 'ಹಿಂದಕ್ಕೆ ಹಿಂತಿರುಗಿ', related: 'ಸಂಬಂಧಿತ ಲೇಖನಗಳು', wasHelpful: 'ಇದು ಸಹಾಯಕವಾಗಿದೆಯೇ?', yes: 'ಹೌದು', no: 'ಇಲ್ಲ' },
  templates: { title: 'ಟೆಂಪ್ಲೇಟ್‌ಗಳು', subtitle: 'ಫಾರ್ಮ್ಯಾಟ್‌ಗಳನ್ನು ಡೌನ್‌ಲೋಡ್ ಮಾಡಿ.', searchPlaceholder: 'ಹುಡುಕಿ...', downloadBtn: 'ಡೌನ್‌ಲೋಡ್ ಮಾಡಿ', preview: 'ಮುನ್ನೋಟ', category: 'ವರ್ಗ', format: 'ಫಾರ್ಮ್ಯಾಟ್', size: 'ಗಾತ್ರ', requirements: 'ಅವಶ್ಯಕತೆಗಳು', instructions: 'ಸೂಚನೆಗಳು' },
  dashboard: { title: 'ಡ್ಯಾಶ್‌ಬೋರ್ಡ್', welcome: 'ಸ್ವಾಗತ', appointments: 'ನೇಮಕಾತಿಗಳು', profile: 'ಪ್ರೊಫೈಲ್', settings: 'ಸೆಟ್ಟಿಂಗ್‌ಗಳು', messages: 'ಸಂದೇಶಗಳು', viewAll: 'ಎಲ್ಲವನ್ನೂ ವೀಕ್ಷಿಸಿ', upcoming: 'ಮುಂಬರುವ', past: 'ಹಿಂದಿನ', noAppointments: 'ಯಾವುದೇ ನೇಮಕಾತಿಗಳಿಲ್ಲ', signOut: 'ಸೈನ್ ಔಟ್', quickActions: 'ತ್ವರಿತ ಕ್ರಿಯೆಗಳು', findLawyer: 'ವಕೀಲರನ್ನು ಹುಡುಕಿ', findLawyerDesc: 'ವಕೀಲರನ್ನು ಬ್ರೌಸ್ ಮಾಡಿ', legalKnowledge: 'ಕಾನೂನು ಜ್ಜ್ಞಾನ', legalKnowledgeDesc: 'ನಿಮ್ಮ ಹಕ್ಕುಗಳನ್ನು ತಿಳಿಯಿರಿ', legalTemplates: 'ಟೆಂಪ್ಲೇಟ್‌ಗಳು', legalTemplatesDesc: 'ದಾಖಲೆಗಳನ್ನು ಡೌನ್‌ಲೋಡ್ ಮಾಡಿ', myAppointments: 'ನನ್ನ ನೇಮಕಾತಿಗಳು', myAppointmentsDesc: 'ಸಮಾಲೋಚನೆಗಳನ್ನು ವೀಕ್ಷಿಸಿ', comingSoon: 'ಶೀಘ್ರದಲ್ಲೇ ಬರಲಿದೆ', comingSoonDesc: 'ಹೊಸ ವೈಶಿಷ್ಟ್ಯಗಳು.', lawyerPortal: 'ಲಾಯರ್ ಪೋರ್ಟಲ್', statsRating: 'ರೇಟಿಂಗ್', statsReviews: 'ವಿಮರ್ಶೆಗಳು', statsVerified: 'ಪರಿಶೀಲಿಸಲಾಗಿದೆ', statsExperience: 'ಅನುಭವ', profileDetails: 'ವಿವರಗಳು', editProfile: 'ತಿದ್ದುಪಡಿ ಮಾಡಿ', city: 'ನಗರ:', fee: 'ಶುಲ್ಕ:', specializations: 'ಪರಿಣತಿಗಳು:', languages: 'ಭಾಷೆಗಳು:', completeProfile: 'ಪೂರ್ಣಗೊಳಿಸಿ', completeProfileDesc: 'ಪ್ರೊಫೈಲ್ ಹೊಂದಿಸಿ.', lawyerComingSoon: 'ಶೀಘ್ರದಲ್ಲೇ ಬರಲಿದೆ', lawyerComingSoonDesc: 'ವಿನಂತಿಗಳನ್ನು ನಿರ್ವಹಿಸಿ.' },
  lawyersPage: { title: 'ವಕೀಲರನ್ನು ಹುಡುಕಿ', subtitle: 'ವಕೀಲರನ್ನು ಬ್ರೌಸ್ ಮಾಡಿ.', searchPlaceholder: 'ಹುಡುಕಿ...', filters: 'ಫಿಲ್ಟರ್‌ಗಳು', experience: 'ಅನುಭವ', fees: 'ಶುಲ್ಕ', languages: 'ಭಾಷೆಗಳು', availability: 'ಲಭ್ಯತೆ', verifiedOnly: 'ಪರಿಶೀಲಿಸಿದ ವೃತ್ತಿಪರರು ಮಾತ್ರ', clearFilters: 'ತೆರವುಗೊಳಿಸಿ', noLawyers: 'ಯಾವುದೇ ವಕೀಲರು ಕಂಡುಬಂದಿಲ್ಲ.', bookConsultation: 'ಕಾಯ್ದಿರಿಸಿ', viewProfile: 'ಪ್ರೊಫೈಲ್ ವೀಕ್ಷಿಸಿ', reviews: 'ವಿಮರ್ಶೆಗಳು', rating: 'ರೇಟಿಂಗ್', location: 'ಸ್ಥಳ' }
};

const or: Translation = {
  nav: { lawyers: 'ଓକିଲମାନେ', knowledge: 'ଜ୍ଞାନ ଆଧାର', templates: 'ଟେମ୍ପଲେଟଗୁଡିକ', rights: 'ଆପଣଙ୍କ ଅଧିକାର ଜାଣନ୍ତୁ', login: 'ଲଗଇନ୍', signup: 'ସାଇନ୍ ଅପ୍' },
  hero: { title: 'ମିନିଟରେ ଆଇନଗତ ସହାୟତା ପାଆନ୍ତୁ', subtitle: 'Get Legal Help in Minutes', searchLaw: 'ଆଇନ ଅନୁସାରେ ଓକିଲ ଖୋଜନ୍ତୁ', searchCity: 'ସହର କିମ୍ବା ପିନକୋଡ୍', searchBtn: 'ଖୋଜନ୍ତୁ', forCitizens: 'ନାଗରିକମାନଙ୍କ ପାଇଁ', forLawyers: 'ଓକିଲମାନଙ୍କ ପାଇଁ' },
  features: { title: 'ଆପଣଙ୍କର ଆବଶ୍ୟକ ସବୁକିଛି', subtitle: 'ଯାଞ୍ଚ ହୋଇଥିବା ଓକିଲ, ମାଗଣା ଆଇନଗତ ସୂଚନା ଆକ୍ସେସ୍ କରନ୍ତୁ।', f1Title: 'ଓକିଲ ଖୋଜନ୍ତୁ', f1Desc: 'ନିକଟସ୍ଥ ଓକିଲ ଖୋଜନ୍ତୁ।', f2Title: 'ପରାମର୍ଶ ବୁକ୍ କରନ୍ତୁ', f2Desc: 'ବିଶେଷଜ୍ଞଙ୍କ ସହ କଥା ହୁଅନ୍ତୁ।', f3Title: 'ମାଗଣା ଆଇନଗତ ସୂଚନା', f3Desc: 'ଆପଣଙ୍କ ଅଧିକାର ବୁଝନ୍ତୁ।', f4Title: 'ଟେମ୍ପଲେଟଗୁଡିକ', f4Desc: 'ଆଇନଗତ ଡକ୍ୟୁମେଣ୍ଟ୍ ଡାଉନଲୋଡ୍ କରନ୍ତୁ।' },
  howItWorks: { title: 'LexIndia କିପରି କାମ କରେ', subtitle: 'ତିନୋଟି ସହଜ ପଦକ୍ଷେପରେ ସାହାଯ୍ୟ ପାଆନ୍ତୁ।', s1Title: 'ଖୋଜନ୍ତୁ', s1Desc: 'ଓକିଲ ଖୋଜନ୍ତୁ।', s2Title: 'ପ୍ରୋଫାଇଲ୍ ଯାଞ୍ଚ କରନ୍ତୁ', s2Desc: 'ଅଭିଜ୍ଞତା ଏବଂ ଫିସ୍ ଦେଖନ୍ତୁ।', s3Title: 'ବୁକ୍ କରନ୍ତୁ ଏବଂ କଥା ହୁଅନ୍ତୁ', s3Desc: 'ଆପଣଙ୍କ ମାମଲା ବିଷୟରେ ଚର୍ଚ୍ଚା କରନ୍ତୁ।' },
  categories: { title: 'ବିଶେଷଜ୍ଞତା ଅନୁଯାୟୀ ଓକିଲ ଖୋଜନ୍ତୁ', subtitle: 'ବିଭିନ୍ନ ଆଇନଗତ କ୍ଷେତ୍ରରେ ଶ୍ରେଷ୍ଠ ଓକିଲଙ୍କୁ ବ୍ରାଉଜ୍ କରନ୍ତୁ।', viewAll: 'ସବୁ ଦେଖନ୍ତୁ', c1: 'ଅପରାଧିକ ଆଇନ', c2: 'ପାରିବାରିକ ଆଇନ', c3: 'ସମ୍ପତ୍ତି ଆଇନ', c4: 'କର୍ପୋରେଟ୍ ଆଇନ', c5: 'ଦେୱାନୀ ଆଇନ', c6: 'ସାଇବର ଆଇନ', lawyers: 'ଓକିଲ' },
  testimonials: { title: 'ଆପଣ ପ୍ରସ୍ତୁତ କି?', subtitle: 'ହଜାରେ ନାଗରିକଙ୍କ ସହ ଯୋଡି ହୁଅନ୍ତୁ।', startBtn: 'ଆରମ୍ଭ କରନ୍ତୁ', quote: "LexIndia ଏହାକୁ ବହୁତ ସହଜ କରିଦେଲା!", role: 'ଗ୍ରାହକ' },
  footer: { desc: 'ଆଇନଗତ ସହାୟତାକୁ ସୁଲଭ କରିବା।', forCitizens: 'ନାଗରିକମାନଙ୍କ ପାଇଁ', findLawyer: 'ଓକିଲ ଖୋଜନ୍ତୁ', knowledge: 'ଜ୍ଞାନ ଆଧାର', templates: 'ଟେମ୍ପଲେଟଗୁଡିକ', rights: 'ଅଧିକାର ଜାଣନ୍ତୁ', forLawyers: 'ଓକିଲମାନଙ୍କ ପାଇଁ', joinDir: 'ଲିଷ୍ଟରେ ଯୋଗ ଦିଅନ୍ତୁ', dashboard: 'ଡ୍ୟାସବୋର୍ଡ', pricing: 'ମୂଲ୍ୟ', company: 'କମ୍ପାନୀ', about: 'ଆମ ବିଷୟରେ', contact: 'ଯୋଗାଯୋଗ', privacy: 'ଗୋପନୀୟତା', terms: 'ସର୍ତ୍ତାବଳୀ', rightsRes: 'ସର୍ବସ୍ୱତ୍ୱ ସଂରକ୍ଷିତ।', disclaimer: 'ଆଇନଗତ ପରାମର୍ଶର ବିକଳ୍ପ ନୁହେଁ।' },
  common: { search: 'ଖୋଜନ୍ତୁ', loading: 'ଲୋଡ୍ ହେଉଛି...', noResults: 'କୌଣସି ଫଳାଫଳ ମିଳିଲା ନାହିଁ', viewDetails: 'ବିବରଣୀ ଦେଖନ୍ତୁ', save: 'ସେଭ୍ କରନ୍ତୁ', cancel: 'ବାତିଲ୍ କରନ୍ତୁ', back: 'ପଛକୁ', continue: 'ଜାରି ରଖନ୍ତୁ', error: 'ଗୋଟିଏ ତ୍ରୁଟି ଘଟିଲା', success: 'ସଫଳତା!', filterBy: 'ଫିଲ୍ଟର୍ କରନ୍ତୁ', sort: 'ସଜାନ୍ତୁ', all: 'ସବୁ' },
  auth: { loginTitle: 'ଲଗଇନ୍ କରନ୍ତୁ', loginSub: 'ଆପଣଙ୍କ ଡ୍ୟାସବୋର୍ଡକୁ ଯାଆନ୍ତୁ।', signupTitle: 'ଆକାଉଣ୍ଟ୍ ତିଆରି କରନ୍ତୁ', signupSub: 'ଆମ ସହ ଯୋଗ ଦିଅନ୍ତୁ।', emailLabel: 'ଇମେଲ୍', passLabel: 'ପାସୱାର୍ଡ', nameLabel: 'ନାମ', forgotPass: 'ପାସୱାର୍ଡ ଭୁଲିଗଲେ କି?', loginBtn: 'ଲଗଇନ୍ କରନ୍ତୁ', signupBtn: 'ଅକାଉଣ୍ଟ୍ ତିଆରି କରନ୍ତୁ', noAccount: "ଆକାଉଣ୍ଟ୍ ନାହିଁ?", hasAccount: 'ଆପଣଙ୍କର ପୂର୍ବରୁ ଗୋଟିଏ ଆକାଉଣ୍ଟ୍ ଅଛି କି?', continueGoogle: 'Google ସହିତ ଜାରି ରଖନ୍ତୁ', roleCitizen: 'ମୁଁ ଜଣେ ନାଗରିକ', roleLawyer: 'ମୁଁ ଜଣେ ଓକିଲ', emailPh: 'ଆପଣ@example.com', passPh: 'ଅତିକମରେ ୮ ଟି ଅକ୍ଷର', namePh: 'ଆପଣଙ୍କ ନାମ', passRequirements: 'ଅତିକମରେ ୮ ଟି ଅକ୍ଷର' },
  knowledge: { title: 'ଆଇନଗତ ସୂଚନା', subtitle: 'ଆଇନଗୁଡିକୁ ବୁଝନ୍ତୁ।', searchPlaceholder: 'ଖୋଜନ୍ତୁ...', categories: 'ବିଭାଗ', popular: 'ବିଷୟଗୁଡିକ', readMore: 'ଆହୁରି ପଢନ୍ତୁ', backToList: 'ପଛକୁ ଫେରନ୍ତୁ', related: 'ସମ୍ବନ୍ଧିତ ପ୍ରବନ୍ଧଗୁଡିକ', wasHelpful: 'ଏହା ସହାୟକ ହେଲା କି?', yes: 'ହଁ', no: 'ନା' },
  templates: { title: 'ଟେମ୍ପଲେଟଗୁଡିକ', subtitle: 'ଫର୍ମାଟଗୁଡିକ ଡାଉନଲୋଡ୍ କରନ୍ତୁ।', searchPlaceholder: 'ଖୋଜନ୍ତୁ...', downloadBtn: 'ଡାଉନଲୋଡ୍ କରନ୍ତୁ', preview: 'ପ୍ରିଭ୍ୟୁ', category: 'ବିଭାଗ', format: 'ଫର୍ମାଟ୍', size: 'ଆକାର', requirements: 'ଆବଶ୍ୟକତା', instructions: 'ନିର୍ଦ୍ଦେଶାବଳୀ' },
  dashboard: { title: 'ଡ୍ୟାସବୋର୍ଡ', welcome: 'ସ୍ୱାଗତ', appointments: 'ଆପଏଣ୍ଟମେଣ୍ଟଗୁଡିକ', profile: 'ପ୍ରୋଫାଇଲ୍', settings: 'ସେଟିଂସ୍', messages: 'ମେସେଜ୍ ଗୁଡିକ', viewAll: 'ସବୁ ଦେଖନ୍ତୁ', upcoming: 'ଆସୁଥିବା', past: 'ଅତୀତ', noAppointments: 'କୌଣସି ଆପଏଣ୍ଟମେଣ୍ଟ ନାହିଁ', signOut: 'ସାଇନ୍ ଆଉଟ୍', quickActions: 'ତ୍ୱରିତ କାର୍ଯ୍ୟଗୁଡ଼ିକ', findLawyer: 'ଓକିଲ ଖୋଜନ୍ତୁ', findLawyerDesc: 'ଓକିଲମାନଙ୍କୁ ଦେଖନ୍ତୁ', legalKnowledge: 'ଆଇନଗତ ଜ୍ଞାନ', legalKnowledgeDesc: 'ଆପଣଙ୍କ ଅଧିକାର ଜାଣନ୍ତୁ', legalTemplates: 'ଟେମ୍ପଲେଟଗୁଡିକ', legalTemplatesDesc: 'ଡକ୍ୟୁମେଣ୍ଟ୍ ଡାଉନଲୋଡ୍ କରନ୍ତୁ', myAppointments: 'ମୋର ଆପଏଣ୍ଟମେଣ୍ଟଗୁଡିକ', myAppointmentsDesc: 'ପରାମର୍ଶ ଦେଖନ୍ତୁ', comingSoon: 'ଖୁବ୍ ଶୀଘ୍ର ଆସୁଛି', comingSoonDesc: 'ନୂଆ ବିଶେଷତ୍ୱଗୁଡିକ।', lawyerPortal: 'ଲୟର ପୋର୍ଟାଲ୍', statsRating: 'ରେଟିଂସ୍', statsReviews: 'ରିଭ୍ୟୁସ୍', statsVerified: 'ଯାଞ୍ଚ ହୋଇଛି', statsExperience: 'ଅଭିଜ୍ଞତା', profileDetails: 'ବିବରଣୀ', editProfile: 'ପ୍ରୋଫାଇଲ୍ ଏଡିଟ୍ କରନ୍ତୁ', city: 'ସହର:', fee: 'ଫିସ୍:', specializations: 'ବିଶେଷଜ୍ଞତା:', languages: 'ଭାଷାଗୁଡ଼ିକ:', completeProfile: 'ସମ୍ପୂର୍ଣ୍ଣ କରନ୍ତୁ', completeProfileDesc: 'ପ୍ରୋଫାଇଲ୍ ସେଟ୍ ଅପ୍ କରନ୍ତୁ।', lawyerComingSoon: 'ଖୁବ୍ ଶୀଘ୍ର ଆସୁଛି', lawyerComingSoonDesc: 'ଅନୁରୋଧ ପରିଚାଳନା କରନ୍ତୁ।' },
  lawyersPage: { title: 'ଓକିଲ ଖୋଜନ୍ତୁ', subtitle: 'ଓକିଲମାନଙ୍କୁ ବ୍ରାଉଜ୍ କରନ୍ତୁ।', searchPlaceholder: 'ଖୋଜନ୍ତୁ...', filters: 'ଫିଲ୍ଟର୍ ଗୁଡ଼ିକ', experience: 'ଅଭିଜ୍ଞତା', fees: 'ଫିସ୍', languages: 'ଭାଷା', availability: 'ଉପଲବ୍ଧତା', verifiedOnly: 'କେବଳ ଯାଞ୍ଚ ହୋଇଥିବା ପ୍ରଫେସନାଲ୍ସ', clearFilters: 'ଫିଲ୍ଟର୍ ଗୁଡ଼ିକୁ ସଫା କରନ୍ତୁ', noLawyers: 'କୌଣସି ଓକିଲ ମିଳିଲେ ନାହିଁ।', bookConsultation: 'ବୁକ୍ କରନ୍ତୁ', viewProfile: 'ପ୍ରୋଫାଇଲ୍ ଦେଖନ୍ତୁ', reviews: 'ରିଭ୍ୟୁସ୍', rating: 'ରେଟିଂସ୍', location: 'ସ୍ଥାନ' }
};

const pa: Translation = {
  nav: { lawyers: 'ਵਕੀਲ', knowledge: 'ਜਾਣਕਾਰੀ', templates: 'ਟੈਂਪਲੇਟਸ', rights: 'ਆਪਣੇ ਹੱਕ ਜਾਣੋ', login: 'ਲਾਗਇਨ', signup: 'ਸਾਈਨ ਅੱਪ' },
  hero: { title: 'ਮਿੰਟਾਂ ਵਿੱਚ ਕਾਨੂੰਨੀ ਮਦਦ ਪ੍ਰਾਪਤ ਕਰੋ', subtitle: 'Get Legal Help in Minutes', searchLaw: 'ਕਾਨੂੰਨ ਦੁਆਰਾ ਵਕੀਲ ਲੱਭੋ', searchCity: 'ਸ਼ਹਿਰ ਜਾਂ ਪਿਨਕੋਡ', searchBtn: 'ਖੋਜ ਕਰੋ', forCitizens: 'ਨਾਗਰਿਕਾਂ ਲਈ', forLawyers: 'ਵਕੀਲਾਂ ਲਈ' },
  features: { title: 'ਤੁਹਾਨੂੰ ਲੋੜੀਂਦੀ ਹਰ ਚੀਜ਼', subtitle: 'ਪ੍ਰਮਾਣਿਤ ਵਕੀਲਾਂ ਤੱਕ ਪਹੁੰਚ ਕਰੋ।', f1Title: 'ਵਕੀਲ ਲੱਭੋ', f1Desc: 'ਨੇੜਲੇ ਵਕੀਲ ਲੱਭੋ।', f2Title: 'ਸਲਾਹ ਮਸ਼ਵਰਾ ਬੁੱਕ ਕਰੋ', f2Desc: 'ਮਾਹਰਾਂ ਨਾਲ ਗੱਲ ਕਰੋ।', f3Title: 'ਮੁਫਤ ਕਾਨੂੰਨੀ ਜਾਣਕਾਰੀ', f3Desc: 'ਆਪਣੇ ਅਧਿਕਾਰਾਂ ਨੂੰ ਸਮਝੋ।', f4Title: 'ਟੈਂਪਲੇਟਸ', f4Desc: 'ਕਾਨੂੰਨੀ ਦਸਤਾਵੇਜ਼ ਡਾਊਨਲੋਡ ਕਰੋ।' },
  howItWorks: { title: 'LexIndia ਕਿਵੇਂ ਕੰਮ ਕਰਦਾ ਹੈ', subtitle: 'ਤਿੰਨ ਆਸਾਨ ਕਦਮਾਂ ਵਿੱਚ ਮਦਦ ਪ੍ਰਾਪਤ ਕਰੋ।', s1Title: 'ਖੋਜ ਕਰੋ', s1Desc: 'ਵਕੀਲ ਲੱਭੋ।', s2Title: 'ਪ੍ਰੋਫਾਈਲਾਂ ਦੀ ਸਮੀਖਿਆ ਕਰੋ', s2Desc: 'ਅਨੁਭਵ ਅਤੇ ਫੀਸਾਂ ਦੀ ਜਾਂਚ ਕਰੋ।', s3Title: 'ਬੁੱਕ ਕਰੋ ਅਤੇ ਗੱਲ ਕਰੋ', s3Desc: 'ਆਪਣੇ ਕੇਸ ਬਾਰੇ ਚਰਚਾ ਕਰੋ।' },
  categories: { title: 'ਮੁਹਾਰਤ ਦੁਆਰਾ ਵਕੀਲ ਲੱਭੋ', subtitle: 'ਵੱਖ-ਵੱਖ ਕਾਨੂੰਨੀ ਖੇਤਰਾਂ ਵਿੱਚ ਚੋਟੀ ਦੇ ਵਕੀਲਾਂ ਨੂੰ ਬ੍ਰਾਊਜ਼ ਕਰੋ।', viewAll: 'ਸਭ ਦੇਖੋ', c1: 'ਅਪਰਾਧਿਕ ਕਾਨੂੰਨ', c2: 'ਪਰਿਵਾਰਕ ਕਾਨੂੰਨ', c3: 'ਜਾਇਦਾਦ ਕਾਨੂੰਨ', c4: 'ਕਾਰਪੋਰੇਟ ਕਾਨੂੰਨ', c5: 'ਸਿਵਲ ਕਾਨੂੰਨ', c6: 'ਸਾਈਬਰ ਕਾਨੂੰਨ', lawyers: 'ਵਕੀਲ' },
  testimonials: { title: 'ਕੀ ਤੁਸੀਂ ਤਿਆਰ ਹੋ?', subtitle: 'ਹਜ਼ਾਰਾਂ ਨਾਗਰਿਕਾਂ ਨਾਲ ਜੁੜੋ।', startBtn: 'ਸ਼ੁਰੂ ਕਰੋ', quote: "LexIndia ਨੇ ਇਸਨੂੰ ਬਹੁਤ ਆਸਾਨ ਬਣਾ ਦਿੱਤਾ!", role: 'ਗਾਹਕ' },
  footer: { desc: 'ਕਾਨੂੰਨੀ ਮਦਦ ਨੂੰ ਪਹੁੰਚਯੋਗ ਬਣਾਉਣਾ।', forCitizens: 'ਨਾਗਰਿਕਾਂ ਲਈ', findLawyer: 'ਵਕੀਲ ਲੱਭੋ', knowledge: 'ਜਾਣਕਾਰੀ', templates: 'ਟੈਂਪਲੇਟਸ', rights: 'ਅਧਿਕਾਰ ਜਾਣੋ', forLawyers: 'ਵਕੀਲਾਂ ਲਈ', joinDir: 'ਡਾਇਰੈਕਟਰੀ ਵਿੱਚ ਸ਼ਾਮਲ ਹੋਵੋ', dashboard: 'ਡੈਸ਼ਬੋਰਡ', pricing: 'ਕੀਮਤਾਂ', company: 'ਕੰਪਨੀ', about: 'ਸਾਡੇ ਬਾਰੇ', contact: 'ਸੰਪਰਕ ਕਰੋ', privacy: 'ਗੋਪਨੀਯਤਾ', terms: 'ਸ਼ਰਤਾਂ', rightsRes: 'ਸਾਰੇ ਹੱਕ ਰਾਖਵੇਂ ਹਨ।', disclaimer: 'ਕਾਨੂੰਨੀ ਸਲਾਹ ਦਾ ਬਦਲ ਨਹੀਂ ਹੈ।' },
  common: { search: 'ਖੋਜ ਕਰੋ', loading: 'ਲੋਡ ਹੋ ਰਿਹਾ ਹੈ...', noResults: 'ਕੋਈ ਨਤੀਜਾ ਨਹੀਂ ਮਿਲਿਆ', viewDetails: 'ਵੇਰਵੇ ਦੇਖੋ', save: 'ਸੇਵ ਕਰੋ', cancel: 'ਰੱਦ ਕਰੋ', back: 'ਪਿੱਛੇ', continue: 'ਜਾਰੀ ਰੱਖੋ', error: 'ਇੱਕ ਗਲਤੀ ਆਈ', success: 'ਸਫਲਤਾ!', filterBy: 'ਫਿਲਟਰ ਕਰੋ', sort: 'ਕ੍ਰਮਬੱਧ ਕਰੋ', all: 'ਸਾਰੇ' },
  auth: { loginTitle: 'ਲਾਗਇਨ ਕਰੋ', loginSub: 'ਆਪਣੇ ਡੈਸ਼ਬੋਰਡ ਤੱਕ ਪਹੁੰਚ ਕਰੋ।', signupTitle: 'ਖਾਤਾ ਬਣਾਓ', signupSub: 'ਸਾਡੇ ਨਾਲ ਜੁੜੋ।', emailLabel: 'ਈਮੇਲ', passLabel: 'ਪਾਸਵਰਡ', nameLabel: 'ਨਾਮ', forgotPass: 'ਪਾਸਵਰਡ ਭੁੱਲ ਗਏ?', loginBtn: 'ਲਾਗਇਨ ਕਰੋ', signupBtn: 'ਖਾਤਾ ਬਣਾਓ', noAccount: "ਖਾਤਾ ਨਹੀਂ ਹੈ?", hasAccount: 'ਕੀ ਤੁਹਾਡੇ ਕੋਲ ਪਹਿਲਾਂ ਹੀ ਖਾਤਾ ਹੈ?', continueGoogle: 'Google ਨਾਲ ਜਾਰੀ ਰੱਖੋ', roleCitizen: 'ਮੈਂ ਨਾਗਰਿਕ ਹਾਂ', roleLawyer: 'ਮੈਂ ਵਕੀਲ ਹਾਂ', emailPh: 'ਤੁਸੀਂ@example.com', passPh: 'ਘੱਟੋ-ਘੱਟ 8 ਅੱਖਰ', namePh: 'ਤੁਹਾਡਾ ਨਾਮ', passRequirements: 'ਘੱਟੋ-ਘੱਟ 8 ਅੱਖਰ' },
  knowledge: { title: 'ਕਾਨੂੰਨੀ ਜਾਣਕਾਰੀ', subtitle: 'ਕਾਨੂੰਨਾਂ ਨੂੰ ਸਮਝੋ।', searchPlaceholder: 'ਖੋਜ ਕਰੋ...', categories: 'ਸ਼੍ਰੇਣੀਆਂ', popular: 'ਵਿਸ਼ੇ', readMore: 'ਹੋਰ ਪੜ੍ਹੋ', backToList: 'ਪਿੱਛੇ ਜਾਓ', related: 'ਸੰਬੰਧਿਤ ਲੇਖ', wasHelpful: 'ਕੀ ਇਹ ਮਦਦਗਾਰ ਸੀ?', yes: 'ਹਾਂ', no: 'ਨਹੀਂ' },
  templates: { title: 'ਟੈਂਪਲੇਟਸ', subtitle: 'ਫਾਰਮੈਟ ਡਾਊਨਲੋਡ ਕਰੋ।', searchPlaceholder: 'ਖੋਜ ਕਰੋ...', downloadBtn: 'ਡਾਊਨਲੋਡ ਕਰੋ', preview: 'ਝਲਕ', category: 'ਸ਼੍ਰੇਣੀ', format: 'ਫਾਰਮੈਟ', size: 'ਆਕਾਰ', requirements: 'ਲੋੜਾਂ', instructions: 'ਹਦਾਇਤਾਂ' },
  dashboard: { title: 'ਡੈਸ਼ਬੋਰਡ', welcome: 'ਜੀ ਆਇਆਂ ਨੂੰ', appointments: 'ਮੁਲਾਕਾਤਾਂ', profile: 'ਪ੍ਰੋਫਾਈਲ', settings: 'ਸੈਟਿੰਗਜ਼', messages: 'ਸੁਨੇਹੇ', viewAll: 'ਸਭ ਦੇਖੋ', upcoming: 'ਆਉਣ ਵਾਲੀਆਂ', past: 'ਪਿਛਲੀਆਂ', noAppointments: 'ਕੋਈ ਮੁਲਾਕਾਤ ਨਹੀਂ', signOut: 'ਸਾਈਨ ਆਊਟ', quickActions: 'ਤੁਰੰਤ ਕਿਰਿਆਵਾਂ', findLawyer: 'ਵਕੀਲ ਲੱਭੋ', findLawyerDesc: 'ਵਕੀਲਾਂ ਨੂੰ ਬ੍ਰਾਊਜ਼ ਕਰੋ', legalKnowledge: 'ਕਾਨੂੰਨੀ ਗਿਆਨ', legalKnowledgeDesc: 'ਆਪਣੇ ਹੱਕ ਜਾਣੋ', legalTemplates: 'ਟੈਂਪਲੇਟਸ', legalTemplatesDesc: 'ਦਸਤਾਵੇਜ਼ ਡਾਊਨਲੋਡ ਕਰੋ', myAppointments: 'ਮੇਰੀਆਂ ਮੁਲਾਕਾਤਾਂ', myAppointmentsDesc: 'ਸਲਾਹ ਮਸ਼ਵਰੇ ਦੇਖੋ', comingSoon: 'ਜਲਦੀ ਆ ਰਿਹਾ ਹੈ', comingSoonDesc: 'ਨਵੀਆਂ ਵਿਸ਼ੇਸ਼ਤਾਵਾਂ।', lawyerPortal: 'ਲਾਇਰ ਪੋਰਟਲ', statsRating: 'ਰੇਟਿੰਗ', statsReviews: 'ਸਮੀਖਿਆਵਾਂ', statsVerified: 'ਪ੍ਰਮਾਣਿਤ', statsExperience: 'ਤਜਰਬਾ', profileDetails: 'ਵੇਰਵੇ', editProfile: 'ਸੋਧੋ', city: 'ਸ਼ਹਿਰ:', fee: 'ਫੀਸ:', specializations: 'ਮੁਹਾਰਤਾਂ:', languages: 'ਭਾਸ਼ਾਵਾਂ:', completeProfile: 'ਪੂਰਾ ਕਰੋ', completeProfileDesc: 'ਪ੍ਰੋਫਾਈਲ ਸੈੱਟਅੱਪ ਕਰੋ।', lawyerComingSoon: 'ਜਲਦੀ ਆ ਰਿਹਾ ਹੈ', lawyerComingSoonDesc: 'ਬੇਨਤੀਆਂ ਦਾ ਪ੍ਰਬੰਧਨ ਕਰੋ।' },
  lawyersPage: { title: 'ਵਕੀਲ ਲੱਭੋ', subtitle: 'ਵਕੀਲਾਂ ਨੂੰ ਬ੍ਰਾਊਜ਼ ਕਰੋ।', searchPlaceholder: 'ਖੋਜ ਕਰੋ...', filters: 'ਫਿਲਟਰ', experience: 'ਅਨੁਭਵ', fees: 'ਫੀਸ', languages: 'ਭਾਸ਼ਾਵਾਂ', availability: 'ਉਪਲਬਧਤਾ', verifiedOnly: 'ਸਿਰਫ਼ ਪ੍ਰਮਾਣਿਤ ਪੇਸ਼ੇਵਰ', clearFilters: 'ਸਾਫ਼ ਕਰੋ', noLawyers: 'ਕੋਈ ਵਕੀਲ ਨਹੀਂ ਮਿਲਿਆ।', bookConsultation: 'ਬੁੱਕ ਕਰੋ', viewProfile: 'ਪ੍ਰੋਫਾਈਲ ਦੇਖੋ', reviews: 'ਸਮੀਖਿਆਵਾਂ', rating: 'ਰੇਟਿੰਗ', location: 'ਸਥਾਨ' }
};

const ml: Translation = {
  nav: { lawyers: 'അഭിഭാഷകർ', knowledge: 'വിവരങ്ങൾ', templates: 'ടെംപ്ലേറ്റുകൾ', rights: 'നിങ്ങളുടെ അവകാശങ്ങൾ അറിയുക', login: 'ലോഗിൻ', signup: 'സൈൻ അപ്പ്' },
  hero: { title: 'മിനിറ്റുകൾക്കുള്ളിൽ നിയമസഹായം നേടുക', subtitle: 'Get Legal Help in Minutes', searchLaw: 'നിയമപ്രകാരം അഭിഭാഷകരെ തിരയുക', searchCity: 'നഗരം അല്ലെങ്കിൽ പിൻകോഡ്', searchBtn: 'തിരയുക', forCitizens: 'പൗരന്മാർക്ക്', forLawyers: 'അഭിഭാഷകർക്ക്' },
  features: { title: 'നിങ്ങൾക്ക് ആവശ്യമുള്ളതെല്ലാം', subtitle: 'പരിശോധിച്ചുറപ്പിച്ച അഭിഭാഷകരെ കണ്ടെത്തുക.', f1Title: 'അഭിഭാഷകനെ കണ്ടെത്തുക', f1Desc: 'അടുത്തുള്ള അഭിഭാഷകരെ കണ്ടെത്തുക.', f2Title: 'കൺസൾട്ടേഷൻ ബുക്ക് ചെയ്യുക', f2Desc: 'വിദഗ്ധരുമായി സംസാരിക്കുക.', f3Title: 'സൗജന്യ നിയമ വിവരങ്ങൾ', f3Desc: 'നിങ്ങളുടെ അവകാശങ്ങൾ മനസ്സിലാക്കുക.', f4Title: 'ടെംപ്ലേറ്റുകൾ', f4Desc: 'നിയമപ്രമാണങ്ങൾ ഡൗൺലോഡ് ചെയ്യുക.' },
  howItWorks: { title: 'LexIndia എങ്ങനെ പ്രവർത്തിക്കുന്നു', subtitle: 'മൂന്ന് എളുപ്പ ഘട്ടങ്ങളിലൂടെ സഹായം നേടുക.', s1Title: 'തിരയുക', s1Desc: 'അഭിഭാഷകരെ കണ്ടെത്തുക.', s2Title: 'പ്രൊഫൈലുകൾ പരിശോധിക്കുക', s2Desc: 'പരിചയസമ്പത്തും ഫീസും പരിശോധിക്കുക.', s3Title: 'ബുക്ക് ചെയ്ത് സംസാരിക്കുക', s3Desc: 'നിങ്ങളുടെ കേസ് ചർച്ച ചെയ്യുക.' },
  categories: { title: 'വൈദഗ്ധ്യമനുസരിച്ച് അഭിഭാഷകരെ കണ്ടെത്തുക', subtitle: 'വിവിധ നിയമ മേഖലകളിലെ മികച്ച അഭിഭാഷകരെ തിരയുക.', viewAll: 'എല്ലാം കാണുക', c1: 'ക്രിമിനൽ നിയമം', c2: 'കുടുംബ നിയമം', c3: 'വസ്തു നിയമം', c4: 'കോർപ്പറേറ്റ് നിയമം', c5: 'സിവിൽ നിയമം', c6: 'സൈബർ നിയമം', lawyers: 'അഭിഭാഷകർ' },
  testimonials: { title: 'നിങ്ങൾ തയ്യാറാണോ?', subtitle: 'ആയിരക്കണക്കിന് പൗരന്മാർക്കൊപ്പം ചേരുക.', startBtn: 'തുടങ്ങുക', quote: "LexIndia ഇത് വളരെ എളുപ്പമാക്കി!", role: 'ക്ലയൻ്റ്' },
  footer: { desc: 'നിയമസഹായം പ്രാപ്യമാക്കുന്നു.', forCitizens: 'പൗരന്മാർക്ക്', findLawyer: 'അഭിഭാഷകനെ കണ്ടെത്തുക', knowledge: 'വിവരങ്ങൾ', templates: 'ടെംപ്ലേറ്റുകൾ', rights: 'അവകാശങ്ങൾ അറിയുക', forLawyers: 'അഭിഭാഷകർക്ക്', joinDir: 'ഡയറക്ടറിയിൽ ചേരുക', dashboard: 'ഡാഷ്‌ബോർഡ്', pricing: 'വിലവിവരങ്ങൾ', company: 'കമ്പനി', about: 'ഞങ്ങളെക്കുറിച്ച്', contact: 'ബന്ധപ്പെടുക', privacy: 'സ്വകാര്യത', terms: 'നിബന്ധനകൾ', rightsRes: 'എല്ലാ അവകാശങ്ങളും നിക്ഷിപ്തം.', disclaimer: 'നിയമോപദേശത്തിന് പകരമാവില്ല.' },
  common: { search: 'തിരയുക', loading: 'ലോഡുചെയ്യുന്നു...', noResults: 'ഫലങ്ങളൊന്നും കണ്ടെത്തിയില്ല', viewDetails: 'വിശദാംശങ്ങൾ കാണുക', save: 'സേവ് ചെയ്യുക', cancel: 'റദ്ദാക്കുക', back: 'പുറകോട്ട്', continue: 'തുടരുക', error: 'ഒരു പിശക് സംഭവിച്ചു', success: 'വിജയം!', filterBy: 'ഫിൽട്ടർ ചെയ്യുക', sort: 'ക്രമീകരിക്കുക', all: 'എല്ലാം' },
  auth: { loginTitle: 'ലോഗിൻ ചെയ്യുക', loginSub: 'നിങ്ങളുടെ ഡാഷ്‌ബോർഡ് ആക്‌സസ് ചെയ്യുക.', signupTitle: 'അക്കൗണ്ട് സൃഷ്ടിക്കുക', signupSub: 'ഞങ്ങളോടൊപ്പം ചേരുക.', emailLabel: 'ഇമെയിൽ', passLabel: 'പാസ്‌വേഡ്', nameLabel: 'പേര്', forgotPass: 'പാസ്‌വേഡ് മറന്നോ?', loginBtn: 'ലോഗിൻ ചെയ്യുക', signupBtn: 'അക്കൗണ്ട് സൃഷ്ടിക്കുക', noAccount: "അക്കൗണ്ട് ഇല്ലേ?", hasAccount: 'നിങ്ങൾക്ക് ഇതിനകം അക്കൗണ്ട് ഉണ്ടോ?', continueGoogle: 'Google ഉപയോഗിച്ച് തുടരുക', roleCitizen: 'ഞാൻ വെറുമൊരു പൗരനാണ്', roleLawyer: 'ഞാൻ ഒരു അഭിഭാഷകനാണ്', emailPh: 'നിങ്ങൾ@example.com', passPh: 'കുറഞ്ഞത് 8 പ്രതീകങ്ങൾ', namePh: 'നിങ്ങളുടെ പേര്', passRequirements: 'കുറഞ്ഞത് 8 പ്രതീകങ്ങൾ' },
  knowledge: { title: 'നിയമ വിവരങ്ങൾ', subtitle: 'നിയമങ്ങൾ മനസ്സിലാക്കുക.', searchPlaceholder: 'തിരയുക...', categories: 'വിഭാഗങ്ങൾ', popular: 'വിഷയങ്ങൾ', readMore: 'കൂടുതൽ വായിക്കുക', backToList: 'പുറകോട്ടേക്ക് പോവുക', related: 'അനുബന്ധ ലേഖനങ്ങൾ', wasHelpful: 'ഇത് സഹായകരമായിരുന്നോ?', yes: 'അതെ', no: 'അല്ല' },
  templates: { title: 'ടെംപ്ലേറ്റുകൾ', subtitle: 'ഫോർമാറ്റുകൾ ഡൗൺലോഡ് ചെയ്യുക.', searchPlaceholder: 'തിരയുക...', downloadBtn: 'ഡൗൺലോഡ് ചെയ്യുക', preview: 'പ്രിവ്യൂ', category: 'വിഭാഗം', format: 'ഫോർമാറ്റ്', size: 'വലുപ്പം', requirements: 'ആവശ്യകതകൾ', instructions: 'നിർദ്ദേശങ്ങൾ' },
  dashboard: { title: 'ഡാഷ്‌ബോർഡ്', welcome: 'സ്വാഗതം', appointments: 'അപ്പോയിൻ്റ്മെൻ്റുകൾ', profile: 'പ്രൊഫൈൽ', settings: 'ക്രമീകരണങ്ങൾ', messages: 'സന്ദേശങ്ങൾ', viewAll: 'എല്ലാം കാണുക', upcoming: 'വരാനിരിക്കുന്നവ', past: 'കഴിഞ്ഞവ', noAppointments: 'അപ്പോയിൻ്റ്മെൻ്റുകളൊന്നുമില്ല', signOut: 'സൈൻ ഔട്ട് ചെയ്യുക', quickActions: 'ദ്രുത പ്രവർത്തനങ്ങൾ', findLawyer: 'അഭിഭാഷകനെ കണ്ടെത്തുക', findLawyerDesc: 'അഭിഭാഷകരെ തിരയുക', legalKnowledge: 'നിയമവിവരങ്ങൾ', legalKnowledgeDesc: 'നിങ്ങളുടെ അവകാശങ്ങൾ അറിയുക', legalTemplates: 'ടെംപ്ലേറ്റുകൾ', legalTemplatesDesc: 'രേഖകൾ ഡൗൺലോഡ് ചെയ്യുക', myAppointments: 'എൻ്റെ അപ്പോയിൻ്റ്മെൻ്റുകൾ', myAppointmentsDesc: 'കൺസൾട്ടേഷനുകൾ കാണുക', comingSoon: 'ഉടൻ വരുന്നു', comingSoonDesc: 'പുതിയ സവിശേഷതകൾ.', lawyerPortal: 'ലോയർ പോർട്ടൽ', statsRating: 'റേറ്റിംഗ്', statsReviews: 'അവലോകനങ്ങൾ', statsVerified: 'പരിശോധിച്ചു', statsExperience: 'പരിചയസമ്പത്ത്', profileDetails: 'വിശദാംശങ്ങൾ', editProfile: 'എഡിറ്റ് ചെയ്യുക', city: 'നഗരം:', fee: 'ഫീസ്:', specializations: 'വൈദഗ്ധ്യങ്ങൾ:', languages: 'ഭാഷകൾ:', completeProfile: 'പൂർത്തിയാക്കുക', completeProfileDesc: 'പ്രൊഫൈൽ സജ്ജീകരിക്കുക.', lawyerComingSoon: 'ഉടൻ വരുന്നു', lawyerComingSoonDesc: 'അഭ്യർത്ഥനകൾ കൈകാര്യം ചെയ്യുക.' },
  lawyersPage: { title: 'അഭിഭാഷകരെ കണ്ടെത്തുക', subtitle: 'അഭിഭാഷകരെ തിരയുക.', searchPlaceholder: 'തിരയുക...', filters: 'ഫിൽട്ടറുകൾ', experience: 'പരിചയസമ്പത്ത്', fees: 'ഫീസ്', languages: 'ഭാഷകൾ', availability: 'ലഭ്യത', verifiedOnly: 'പരിശോധിച്ചുറപ്പിച്ച പ്രൊഫഷണലുകൾ മാത്രം', clearFilters: 'മായ്ക്കുക', noLawyers: 'അഭിഭാഷകരെ കണ്ടെത്തിയില്ല.', bookConsultation: 'ബുക്ക് ചെയ്യുക', viewProfile: 'പ്രൊഫൈൽ കാണുക', reviews: 'അവലോകനങ്ങൾ', rating: 'റേറ്റിംഗ്', location: 'സ്ഥലം' }
};

const bho: Translation = {
  nav: { lawyers: 'वकील', knowledge: 'ज्ञानकोष', templates: 'टेम्पलेट', rights: 'आपन अधिकार जानीं', login: 'लॉग इन', signup: 'साइन अप' },
  hero: { title: 'मिनटों में कानूनी मदद पाईं', subtitle: 'Get Legal Help in Minutes', searchLaw: 'कानून के हिसाब से वकील खोजीं', searchCity: 'शहर या पिनकोड', searchBtn: 'खोजीं', forCitizens: 'नागरिक लोगन खातिर', forLawyers: 'वकील लोगन खातिर' },
  features: { title: 'कानूनी शांति के लिए आपको जो कुछ भी चाहिए', subtitle: 'सत्यापित वकीलों, मुफ्त कानूनी जानकारी और आवश्यक दस्तावेज़ टेम्पलेट्स तक एक ही स्थान पर पहुंच प्राप्त करीं।', f1Title: 'वकील खोजीं', f1Desc: 'विशेषज्ञता और समीक्षाओं के आधार पर अपने आस-पास सत्यापित, शीर्ष-रेटेड वकील खोजीं।', f2Title: 'परामर्श बुक करीं', f2Desc: 'नियुक्तियां निर्धारित करीं और कानूनी पेशेवरों के साथ सुरक्षित रूप से चैट करीं।', f3Title: 'मुफ्त कानूनी जानकारी', f3Desc: 'हमनी के द्विभाषी ज्ञानकोष के साथ आपन अधिकार समझीं।', f4Title: 'टेम्प्लेट्स', f4Desc: 'प्राथमिकी, हलफनामा और नोटिस जइसन मानक कानूनी प्रारूप डाउनलोड करीं।' },
  howItWorks: { title: 'LexIndia कइसे काम करेला', subtitle: 'तीन आसान चरण में आवश्यक कानूनी सहायता प्राप्त करीं।', s1Title: 'खोजीं और फ़िल्टर करीं', s1Desc: 'प्रासंगिक वकीलों के खोजे खातिर आपन कानूनी मुद्दा और स्थान दर्ज करीं।', s2Title: 'प्रोफ़ाइल देखीं', s2Desc: 'सही विकल्प चुने खातिर अनुभव, फीस और ग्राहक समीक्षा के जांच करीं।', s3Title: 'बुक करीं अउर बात करीं', s3Desc: 'परामर्श निर्धारित करीं और आपन केस के बारे में सुरक्षित रूप से चर्चा करीं।' },
  categories: { title: 'विशेषज्ञता के अनुसार वकील खोजीं', subtitle: 'विभिन्न कानूनी डोमेन में शीर्ष-रेटेड अधिवक्ताओं के ब्राउज़ करीं।', viewAll: 'सब देखीं', c1: 'आपराधिक कानून', c2: 'पारिवारिक कानून', c3: 'संपत्ति कानून', c4: 'कॉर्पोरेट कानून', c5: 'नागरिक कानून', c6: 'साइबर कानून', lawyers: 'वकील' },
  testimonials: { title: 'का रउरा आपन कानूनी मुद्दा सुलझावे खातिर तैयार बानी?', subtitle: 'हजारों नागरिक लोग के साथ जुड़ीं जे LexIndia के माध्यम से सफलतापूर्वक सही कानूनी प्रतिनिधित्व पा चुकल बाड़ें।', startBtn: 'अभी शुरू करीं', quote: "हम दिल्ली में एक विश्वसनीय संपत्ति वकील खोजे खातिर संघर्ष करत रहनी। LexIndia एकरा के प्रोफाइल के तुलना करे, समीक्षा पढ़े, और परामर्श बुक करे खातिर अविश्वसनीय रूप से आसान बना दिहलस। अत्यधिक अनुशंसित!", role: 'संपत्ति विवाद ग्राहक' },
  footer: { desc: 'हर भारतीय नागरिक खातिर कानूनी मदद के सुलभ, पारदर्शी और कुशल बनावल।', forCitizens: 'नागरिक खातिर', findLawyer: 'वकील खोजीं', knowledge: 'ज्ञानकोष', templates: 'कानूनी टेम्प्लेट्स', rights: 'आपन अधिकार जानीं', forLawyers: 'वकील खातिर', joinDir: 'निर्देशिका में शामिल होईं', dashboard: 'वकील डैशबोर्ड', pricing: 'कीमत निर्धारण', company: 'कंपनी', about: 'हमनी के बारे में', contact: 'संपर्क करीं', privacy: 'गोपनीयता नीति', terms: 'सेवा के शर्त', rightsRes: 'सर्वाधिकार सुरक्षित।', disclaimer: 'अस्वीकरण: ई मंच केवल सूचनात्मक उद्देश्य खातिर बा और पेशेवर कानूनी सलाह के विकल्प नइखे।' },
  common: { search: 'खोजीं', loading: 'लोड हो रहल बा...', noResults: 'कौनों परिणाम ना मिलल', viewDetails: 'विवरण देखीं', save: 'सेव करीं', cancel: 'रद्द करीं', back: 'पीछे', continue: 'जारी रखीं', error: 'त्रुटि भइल', success: 'सफलता!', filterBy: 'फ़िल्टर करीं', sort: 'क्रमबद्ध करीं', all: 'सब' },
  auth: { loginTitle: 'LexIndia में साइन इन करीं', loginSub: 'परामर्श बुक करे और दस्तावेज प्रबंधित करे खातिर आपन डैशबोर्ड तक पहुँच प्राप्त करीं।', signupTitle: 'एक खाता बनाईं', signupSub: 'हजारों नागरिक लोग के साथ जुड़ीं जे सुलभ कानूनी मदद प्राप्त करत बाड़ें।', emailLabel: 'ईमेल पता', passLabel: 'पासवर्ड', nameLabel: 'पूरा नाम', forgotPass: 'पासवर्ड भूल गईनी?', loginBtn: 'साइन इन करीं', signupBtn: 'खाता बनाईं', noAccount: "का राउर खाता नइखे?", hasAccount: 'का राउर पहिलहीं से खाता बा?', continueGoogle: 'Google के साथ जारी रखीं', roleCitizen: 'हम नागरिक बानी', roleLawyer: 'हम वकील बानी', emailPh: 'रउवा@example.com', passPh: 'कम से कम 8 अक्षर', namePh: 'राउर नाम', passRequirements: 'कम से कम 8 अक्षर होखे के चाहीं' },
  knowledge: { title: 'कानूनी जानकारी', subtitle: 'सरल शब्द में आपन अधिकार, कानूनी प्रक्रिया और भारतीय कानून के समझीं।', searchPlaceholder: 'लेख, कानून, अधिकार खोजीं...', categories: 'श्रेणियाँ', popular: 'लोकप्रिय विषय', readMore: 'लेख पढ़ीं', backToList: 'ज्ञानकोष पर वापस जाईं', related: 'संबंधित लेख', wasHelpful: 'का इ मददगार रहल?', yes: 'हाँ', no: 'ना' },
  templates: { title: 'कानूनी दस्तावेज टेम्प्लेट्स', subtitle: 'उपयोग खातिर तैयार मानकीकृत कानूनी प्रारूप, नोटिस और समझौता डाउनलोड करीं।', searchPlaceholder: 'टेम्प्लेट्स खोजीं (जइसे कि, रेंटल एग्रीमेंट, एनडीए)...', downloadBtn: 'टेम्प्लेट डाउनलोड करीं', preview: 'पूर्वावलोकन', category: 'श्रेणी', format: 'प्रारूप', size: 'आकार', requirements: 'आवश्यकता', instructions: 'निर्देश' },
  dashboard: { title: 'डैशबोर्ड', welcome: 'वापस स्वागत बा', appointments: 'अपॉइंटमेंट', profile: 'प्रोफाइल', settings: 'सेटिंग्स', messages: 'संदेश', viewAll: 'सब देखीं', upcoming: 'आवे वाला', past: 'बीतल', noAppointments: 'कौनों अपॉइंटमेंट नइखे निर्धारित', signOut: 'साइन आउट', quickActions: 'त्वरित कार्रवाई', findLawyer: 'वकील खोजीं', findLawyerDesc: '4+ सत्यापित वकील के ब्राउज़ करीं', legalKnowledge: 'कानूनी ज्ञान', legalKnowledgeDesc: 'आपन कानूनी अधिकार जानीं', legalTemplates: 'कानूनी टेम्प्लेट्स', legalTemplatesDesc: 'मुफ्त दस्तावेज डाउनलोड करीं', myAppointments: 'हमर अपॉइंटमेंट', myAppointmentsDesc: 'आवे वाला परामर्श देखीं', comingSoon: 'जल्दी आवत बा', comingSoonDesc: 'अपॉइंटमेंट बुकिंग, केस ट्रैकिंग और दस्तावेज भंडारण अगला अपडेट में उपलब्ध होई।', lawyerPortal: 'वकील पोर्टल', statsRating: 'रेटिंग', statsReviews: 'समीक्षा', statsVerified: 'सत्यापित', statsExperience: 'अनुभव', profileDetails: 'प्रोफाइल विवरण', editProfile: 'प्रोफाइल संपादित करीं', city: 'शहर:', fee: 'फीस:', specializations: 'विशेषज्ञता:', languages: 'भाषा:', completeProfile: 'आपन प्रोफाइल पूरा करीं', completeProfileDesc: 'आपन वकील प्रोफाइल सेट अप करीं ताकि ग्राहक रउरा के खोज सकस और बुक कर सकस।', lawyerComingSoon: 'अपॉइंटमेंट प्रबंधन जल्दी आवत बा', lawyerComingSoonDesc: 'अगला अपडेट में क्लाइंट अपॉइंटमेंट अनुरोध देखीं और प्रबंधित करीं।' },
  lawyersPage: { title: 'सत्यापित वकील खोजीं', subtitle: 'भारत में विभिन्न कानूनी डोमेन में शीर्ष-रेटेड अधिवक्ताओं के ब्राउज़ करीं।', searchPlaceholder: 'नाम, विशेषज्ञता, या स्थान से खोजीं...', filters: 'फ़िल्टर', experience: 'अनुभव', fees: 'परामर्श फीस', languages: 'बोलल जाए वाला भाषा', availability: 'उपलब्धता', verifiedOnly: 'सिर्फ सत्यापित पेशेवर', clearFilters: 'फ़िल्टर साफ़ करीं', noLawyers: 'राउर मानदंड से मेल खाए वाला कौनों वकील ना मिलल।', bookConsultation: 'परामर्श बुक करीं', viewProfile: 'प्रोफाइल देखीं', reviews: 'समीक्षा', rating: 'रेटिंग', location: 'स्थान' }
};

const bh: Translation = {
  nav: { lawyers: 'वकील', knowledge: 'जानकारी', templates: 'टेम्प्लेट', rights: 'अपन अधिकार जानीं', login: 'लॉगिन', signup: 'साइन अप' },
  hero: { title: 'मिनटों में कानूनी मदद पाईं', subtitle: 'Get Legal Help in Minutes', searchLaw: 'कानून के अनुसार वकील खोजीं', searchCity: 'शहर भा पिनकोड', searchBtn: 'खोजीं', forCitizens: 'नागरिक लेल', forLawyers: 'वकील लेल' },
  features: { title: 'रउरा के जवन चाहीं', subtitle: 'सत्यापित वकील तक पहुंच प्राप्त करीं।', f1Title: 'वकील खोजीं', f1Desc: 'नजदीकी वकील खोजीं।', f2Title: 'परामर्श बुक करीं', f2Desc: 'विशेषज्ञ से बात करीं।', f3Title: 'मुफ्त कानूनी जानकारी', f3Desc: 'अपन अधिकार समझीं।', f4Title: 'टेम्प्लेट्स', f4Desc: 'कानूनी दस्तावेज डाउनलोड करीं।' },
  howItWorks: { title: 'LexIndia कइसे काम करैत अछि', subtitle: 'तीन आसान चरण में मदद पाईं।', s1Title: 'खोजीं', s1Desc: 'वकील खोजीं।', s2Title: 'प्रोफाइल देखीं', s2Desc: 'अनुभव अउर फीस चेक करीं।', s3Title: 'बुक करीं अउर बात करीं', s3Desc: 'अपन केस के बारे में चर्चा करीं।' },
  categories: { title: 'विशेषज्ञता के अनुसार वकील खोजीं', subtitle: 'विभिन्न कानूनी क्षेत्र में शीर्ष वकील के ब्राउज़ करीं।', viewAll: 'सब देखीं', c1: 'आपराधिक कानून', c2: 'पारिवारिक कानून', c3: 'संपत्ति कानून', c4: 'कॉर्पोरेट कानून', c5: 'नागरिक कानून', c6: 'साइबर कानून', lawyers: 'वकील' },
  testimonials: { title: 'की रउरा तैयार बानी?', subtitle: 'हजारों नागरिक लोग के साथ जुड़ीं।', startBtn: 'शुरू करीं', quote: "LexIndia एकरा के बहुत आसान बना दिहलस!", role: 'ग्राहक' },
  footer: { desc: 'कानूनी मदद के सुलभ बनावल।', forCitizens: 'नागरिक लेल', findLawyer: 'वकील खोजीं', knowledge: 'जानकारी', templates: 'टेम्प्लेट्स', rights: 'अधिकार जानीं', forLawyers: 'वकील लेल', joinDir: 'डायरेक्टरी में शामिल होईं', dashboard: 'डैशबोर्ड', pricing: 'कीमत', company: 'कंपनी', about: 'हमनी के बारे में', contact: 'संपर्क करीं', privacy: 'गोपनीयता', terms: 'शर्त', rightsRes: 'सर्वाधिकार सुरक्षित।', disclaimer: 'कानूनी सलाह के विकल्प नइखे।' },
  common: { search: 'खोजीं', loading: 'लोड हो रहल बा...', noResults: 'कौनों परिणाम ना मिलल', viewDetails: 'विवरण देखीं', save: 'सेव करीं', cancel: 'रद्द करीं', back: 'पीछे', continue: 'जारी रखीं', error: 'त्रुटि भइल', success: 'सफलता!', filterBy: 'फ़िल्टर करीं', sort: 'क्रमबद्ध करीं', all: 'सब' },
  auth: { loginTitle: 'लॉगिन करीं', loginSub: 'अपन डैशबोर्ड तक पहुँच प्राप्त करीं।', signupTitle: 'खाता बनाईं', signupSub: 'हमनी के साथ जुड़ीं।', emailLabel: 'ईमेल', passLabel: 'पासवर्ड', nameLabel: 'नाम', forgotPass: 'पासवर्ड भूल गईनी?', loginBtn: 'लॉगिन करीं', signupBtn: 'खाता बनाईं', noAccount: "खाता नइखे?", hasAccount: 'की राउर पहिलहीं से खाता बा?', continueGoogle: 'Google के साथ जारी रखीं', roleCitizen: 'हम नागरिक बानी', roleLawyer: 'हम वकील बानी', emailPh: 'रउवा@example.com', passPh: 'कम से कम 8 अक्षर', namePh: 'राउर नाम', passRequirements: 'कम से कम 8 अक्षर' },
  knowledge: { title: 'कानूनी जानकारी', subtitle: 'कानून के समझीं।', searchPlaceholder: 'खोजीं...', categories: 'श्रेणियाँ', popular: 'विषय', readMore: 'अउर पढ़ीं', backToList: 'पीछे जाईं', related: 'संबंधित लेख', wasHelpful: 'की इ मददगार रहल?', yes: 'हाँ', no: 'ना' },
  templates: { title: 'टेम्प्लेट्स', subtitle: 'प्रारूप डाउनलोड करीं।', searchPlaceholder: 'खोजीं...', downloadBtn: 'डाउनलोड करीं', preview: 'पूर्वावलोकन', category: 'श्रेणी', format: 'प्रारूप', size: 'आकार', requirements: 'आवश्यकता', instructions: 'निर्देश' },
  dashboard: { title: 'डैशबोर्ड', welcome: 'स्वागत बा', appointments: 'अपॉइंटमेंट', profile: 'प्रोफाइल', settings: 'सेटिंग्स', messages: 'संदेश', viewAll: 'सब देखीं', upcoming: 'आवे वाला', past: 'बीतल', noAppointments: 'कौनों अपॉइंटमेंट नइखे', signOut: 'साइन आउट', quickActions: 'त्वरित कार्रवाई', findLawyer: 'वकील खोजीं', findLawyerDesc: 'वकील के ब्राउज़ करीं', legalKnowledge: 'कानूनी ज्ञान', legalKnowledgeDesc: 'अपन अधिकार जानीं', legalTemplates: 'टेम्प्लेट्स', legalTemplatesDesc: 'दस्तावेज डाउनलोड करीं', myAppointments: 'हमर अपॉइंटमेंट', myAppointmentsDesc: 'परामर्श देखीं', comingSoon: 'जल्दी आवत बा', comingSoonDesc: 'नया सुविधा।', lawyerPortal: 'वकील पोर्टल', statsRating: 'रेटिंग', statsReviews: 'समीक्षा', statsVerified: 'सत्यापित', statsExperience: 'अनुभव', profileDetails: 'विवरण', editProfile: 'संपादित करीं', city: 'शहर:', fee: 'फीस:', specializations: 'विशेषज्ञता:', languages: 'भाषा:', completeProfile: 'पूरा करीं', completeProfileDesc: 'प्रोफाइल सेट अप करीं।', lawyerComingSoon: 'जल्दी आवत बा', lawyerComingSoonDesc: 'अनुरोध प्रबंधित करीं।' },
  lawyersPage: { title: 'वकील खोजीं', subtitle: 'वकील के ब्राउज़ करीं।', searchPlaceholder: 'खोजीं...', filters: 'फ़िल्टर', experience: 'अनुभव', fees: 'फीस', languages: 'भाषा', availability: 'उपलब्धता', verifiedOnly: 'सिर्फ सत्यापित पेशेवर', clearFilters: 'साफ़ करीं', noLawyers: 'कौनों वकील ना मिलल।', bookConsultation: 'बुक करीं', viewProfile: 'प्रोफाइल देखीं', reviews: 'समीक्षा', rating: 'रेटिंग', location: 'स्थान' }
};

const allTranslations: Record<Language, Translation> = {
  en, hi, bn, te, mr, ta, ur, gu, kn, or, pa, ml, bho, bh
};

export function getTranslation(lang: Language): Translation {
  return allTranslations[lang] || en;
}
